### ISSUE TITLE
[question]: Websocket handshake issue.

### ISSUE THREAD

**Issue by rodrigopinto** [nginxinc/kubernetes-ingress#1001]
Hey there, I am currently running a graphql apollo server on k8s with nginx ingress in front of it. 

While trying to get the websocket(graphql subscription) connection between the client and server, I getting an error of handshake: `Error during WebSocket handshake: Unexpected response code: 400`.

We already followed the [websocket example](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket) and also added few other annotations to make a longer timeout for the proxy read and proxy sent timout, but the issue continue. 

My ingress look like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: graphql
  namespace: $NAMESPACE
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: public
    nginx.org/websocket-services: "graphql" # also tried nginx.ingress.kubernetes.io/websocket-services as I was not sure.
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    
     #...
spec:
  rules:
    - host: $DOMAIN
      http:
        paths:
          - path: /
            backend:
              serviceName: graphql
              servicePort: 80

```

Am I missing anything?
