### ISSUE TITLE
Exposing Redis with Ingress Nginx Controller Not Working

### ISSUE THREAD

**Issue by vforv** [nginxinc/kubernetes-ingress#1061]
Hello when I use node port to expose my redis service it works fine. I am able to access it. But if I try switch to Ingress Nginx controller it refuse to connect.. Other apps work fine with ingress.

Here is my service:

```
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
#  type: NodePort
  ports:
    - name: http
      port: 6379
      targetPort: 6379
      protocol: TCP
#      nodePort: 30007
  selector:
    app: redis

```

here is ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redis-ing
  annotations:
     kubernetes.io/ingress.class: "nginx"
     ingress.kubernetes.io/ssl-redirect: "true"
     nginx.ingress.kubernetes.io/ssl-redirect: "true"
     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
     cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #  nginx.ingress.kubernetes.io/enable-cors: "true"
    #  nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    #  nginx.ingress.kubernetes.io/cors-allow-origin: "https://test.hefest.io"
    #  nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
  - secretName: letsencrypt-prod
    hosts:
      - redis-dev.domain.com
  rules:
  - host: redis-dev.domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: redis-svc
          servicePort: 6379
```

Any idea what can be an issue?

**Comment by lucacome** [comment]
Hi @vforv 

Based on your annotations I believe you're using the [community Ingress Controller](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md). Can you please make sure you're using the right one?

Thanks

**Comment by vforv** [comment]
@lucacome I sure I am using nginxinc/kubernetes-ingress

Installed following docs: https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/

**Comment by lucacome** [comment]
@vforv thanks for confirming! We don't support `nginx.ingress.kubernets.io` annotations, please take a look at the supported ones [here](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/).

To load balance redis you would need to use TCP load balancing with stream snippets (you can find an example [here](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/tcp-udp)) or using [TransportServer Resource](https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/) (equivalent example [here](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/basic-tcp-udp))

Using TransportServer Resource it would look something like this:

```apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis-tcp
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis-tcp
  selector:
    app: redis
```


```apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: redis-tcp
spec:
  listener:
    name: redis-tcp 
    protocol: TCP
  upstreams:
  - name: redis-app
    service: redis
    port: 6379
  action:
    pass: redis-app
```
```
kind: GlobalConfiguration 
metadata:
  name: nginx-configuration
  namespace: nginx-ingress
spec:
  listeners:
  - name: redis-tcp
    port: 6379
    protocol: TCP
```
And make sure to enable the `-global-configuration` command-line argument.
 
Let me know if it makes sense
