### ISSUE TITLE
Attempt to acquire IP from cloud provider is forbidden

### ISSUE THREAD

**Issue by frgomes** [nginxinc/kubernetes-ingress#1062]
**Describe the bug**

We need multiple namespaces have the ability to obtain separate IP addresses allocated from the cloud infrastructure.
We've employed instructions (slightly adapted) from https://kubernetes.github.io/ingress-nginx/examples/static-ip/ which ended up on error

    No namespace with name j1111cc5555 found: namespaces "j1111cc5555" is forbidden: User "system:serviceaccount:ingress-nginx:ingress-nginx" cannot get resource "namespaces" in API group "" in the namespace "j1111cc5555"

**To Reproduce**

1. An ingress controller was deployed as usual in namespace ``ingress-nginx`` and it works fine as expected. However, this ingress controller only monitors namespace ``ingress-nginx``.

2. Now I would like to deploy a second ingress controller, for the purpose of obtaining a second IP address from the cloud infrastructure and for the purpose of monitoring a second namespace. Then, I've applied the yaml configurations below:

$ kubectl apply -f modified-static-ip-svc.yaml
```yaml
# This is the backend service
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: nginx-ingress-j1111cc5555
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    # Selects nginx-ingress-controller pods
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
```

$ kubectl apply -f second-nginx-ingress-controller.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.34.0
    helm.sh/chart: ingress-nginx-2.11.0
  name: nginx-ingress-j1111cc5555
  namespace: ingress-nginx
spec:
  minReadySeconds: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/name: ingress-nginx
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --publish-service=ingress-nginx/nginx-ingress-j1111cc5555
        - --election-id=ingress-controller-leader-ingress-nginx
        - --ingress-class=nginx-j1111cc5555
        - --configmap=ingress-nginx/nginx-ingress-j1111cc5555
        - --watch-namespace=j1111cc5555
        - --validating-webhook=:8443
        - --validating-webhook-certificate=/usr/local/certificates/cert
        - --validating-webhook-key=/usr/local/certificates/key
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.0@sha256:56633bd00dab33d92ba14c6e709126a762d54a75a6e72437adefeaaca0abb069
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /wait-shutdown
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 8443
          name: webhook
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsUser: 101
        volumeMounts:
        - mountPath: /usr/local/certificates/
          name: webhook-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      serviceAccountName: ingress-nginx
      terminationGracePeriodSeconds: 300
      volumes:
      - name: webhook-cert
        secret:
          secretName: ingress-nginx-admission
```

3. A second load balancer was allocated on Digital Ocean. 
```
ingress-nginx   nginx-ingress-j1111cc5555             LoadBalancer   10.245.0.84      138.68.119.239   80:31619/TCP,443:32174/TCP   1h
```

4. However, the pod crashed:
```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v0.34.0
  Build:         v20200709-ingress-nginx-2.10.0-28-g8693cdb89
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.1

-------------------------------------------------------------------------------

I0719 12:01:24.893687       7 flags.go:205] Watching for Ingress class: nginx-j1111cc5555
W0719 12:01:24.893768       7 flags.go:208] Only Ingresses with class "nginx-j1111cc5555" will be processed by this Ingress controller
W0719 12:01:24.894416       7 flags.go:250] SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)
W0719 12:01:24.894581       7 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0719 12:01:24.894852       7 main.go:231] Creating API client for https://10.245.0.1:443
I0719 12:01:24.907009       7 main.go:275] Running in Kubernetes cluster version v1.17 (v1.17.5) - git (clean) commit e0fccafd69541e3750d460ba0f9743b90336f24f - platform linux/amd64
F0719 12:01:24.913986       7 main.go:100] No namespace with name j1111cc5555 found: namespaces "j1111cc5555" is forbidden: User "system:serviceaccount:ingress-nginx:ingress-nginx" cannot get resource "namespaces" in API group "" in the namespace "j1111cc5555"
```

**Expected behavior**
I would expect to have the ingress controller able to manage the second allocated IP address.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit: v20200709-ingress-nginx-2.10.0-28-g8693cdb89
* Version of Kubernetes: v1.17.5
* Kubernetes platform: Digital Ocean
* Using NGINX or NGINX Plus: nginx/1.19.1

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by frgomes** [comment]
Maybe duplicate of #5758 ?

**Comment by frgomes** [comment]
As found on #5758, I've double checked an item mentioned there:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.34.0
    helm.sh/chart: ingress-nginx-2.11.0
  name: ingress-nginx
  namespace: ingress-nginx
rules:
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
```
