### ISSUE TITLE
Mistake in Doc-Web for App-Protect

### ISSUE THREAD

**Issue by MattDierick** [nginxinc/kubernetes-ingress#1082]
At the end of the page [https://github.com/nginxinc/kubernetes-ingress/blob/master/docs-web/app-protect/configuration.md], there is a mistaping.

You would add define that config in the spec of your APLogConf resource as follows:

```
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata: 
  name: logconf
spec:
  filter: 
    request_types: all
  content: 
    format: default
    max_request_size: any
    max_message_size: 5k
```

Mistake is on request_type directive. The right YAML is :

```
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata: 
  name: logconf
spec:
  filter: 
    request_type: all
  content: 
    format: default
    max_request_size: any
    max_message_size: 5k
```
