### ISSUE TITLE
Configure external proxy in Virtual server

### ISSUE THREAD

**Issue by saggiyogesh** [nginxinc/kubernetes-ingress#1084]
**Is your feature request related to a problem? Please describe.**
In VirtualServer `proxy_pass` is not supported in `location_snippets` of a path

**Describe the solution you'd like**
`proxy_path` or some other option must be there in the Virtual server path, so that can configure an external proxy.

```
 - path: /other-poxy
    location-snippets: |
      proxy_pass https://my-static-content.netlify.app/;
```        

Something like this is not supported. Any workaround to do this.

**Comment by pleshakov** [comment]
Hi @saggiyogesh 

For NGINX OSS, I think the following snippets workaround can work for you:
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  server-snippets: |
    location /other-proxy {
      proxy_set_header Host nginx.org;
      proxy_pass https://nginx.org/;
    }
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: "/tea"
    action:
      pass: tea
  - path: "/coffee"
    action:
      pass: coffee
```

Note: if the DNS name can't be resolved (for example, DNS server is down), than NGINX will fail to reload. Also, NGINX resolves DNS names only on start/reload. So if the IP address behind the DNS name changes, NGINX won't pick it up until the next reload. To mitigate this, consider using "Setting the Domain Name in a Variable" approach described here https://www.nginx.com/blog/dns-service-discovery-nginx-plus/

If you're using NGINX Plus, you can proxy to an external destination if you create an ExternalName service. Please take a look at this example https://github.com/nginxinc/kubernetes-ingress/tree/v1.8.0/examples/externalname-services#prerequisites It will work the same way for VirtualServer as for the Ingress resource.
