### ISSUE TITLE
Mergeable Ingress with subdomains?

### ISSUE THREAD

**Issue by alexgeek** [nginxinc/kubernetes-ingress#1086]
**Is your feature request related to a problem? Please describe.**
I need to use fewer static IP addresses as I have a limited quota. 
I tend to deploy similar workloads (same helm charts, different values) to different namespaces for each of our internal projects.
It would be great to use the Mergeable Ingress feature but redirect via hosts rather than paths.

**Describe the solution you'd like**
Have a master with a wildcard host like so:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-master
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
  - host: *.staging.example.com
```

Then minions for services in different namespaces:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-jenkins-minion
  namespace: jenkins-001
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: jenkins-001.staging.example.com
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-jenkins-minion
  namespace: jenkins-002
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: jenkins-002.staging.example.com
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
```

**Describe alternatives you've considered**
I've been struggling with this problem for a while and have not yet found a good solution. 
So far I've only had success using a loadbalancer per subdomain which is not a great solution.

**Additional context**
Using GKE.
