### ISSUE TITLE
Redirection issue 

### ISSUE THREAD

**Issue by saivikas408** [nginxinc/kubernetes-ingress#1106]
Hi All,

I have redirection issue from http to https , I am struck with this from 3 days

Here are my kubernetes yaml files
```
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# master-ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-master
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
    nginx.org/redirect-to-https: "True"
spec:
  rules:
  - host: myexample.com
---
# minion-ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-web-ingress-minion
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName=my-service rewrite=/"
spec:
  rules:
  - host: myexample.com
    http:
      paths:
      - path: /myapp
        backend:
          serviceName: my-service
          servicePort: 80
---
```
And also here is my nginx service

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-1:xxxxxxxxxxxxx:certificate/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 80
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress

``` 
when I use above files I am able to get the output as below ,but redirection is not happening
when i hit http://myexample.com/myapp --> Shows nginx homepage
when i hit https://myexample.com/myapp --> Shows nginx homepage

**Expected behavior**

when i hit http://myexample.com/myapp   it should redirect to https://myexample.com/myapp and it should display nginx homepage

**Your environment**
* Version of the Ingress Controller - release version or a specific commit  :  Version=1.7.2 GitCommit=ad92aa9d
* Version of Kubernetes   : 1.18.5
* Kubernetes platform (e.g. Mini-kube or GCP) : AWS 
* Using NGINX or NGINX Plus : NGINX 

Is there any documentation on how to use Amazon ACM certificates with nginx ?
