### ISSUE TITLE
Consistent hashing for stateful sets

### ISSUE THREAD

**Issue by defect** [nginxinc/kubernetes-ingress#1117]
**Is your feature request related to a problem? Please describe.**
This isn't really a feature request, more trying to find ideas on how to solve a specific problem.

We have a statefulset of a caching service, and each pod serves a subsection of the requests to the service. If a pod goes down it's not a huge deal, it'll just spawn somewhere else. We'd lose the cache of that pod but that's expected.

The problem is that the new pod gets a new IP, so if using the hash load balancing method everything gets shuffled around and we lose the entirety (or at least more than necessary) of the cache. What I'd like to do is hash based on the hostname of the pod since in a statefulset that'll be consistent.

**Describe the solution you'd like**
Really just ideas on how to solve this specific problem :)

**Describe alternatives you've considered**
I tried using `Service`s configured with `externalAddress`, but that doesn't seem to work here. I'm also not sure if you can list more than one hostname.

I've also looked at `EndpointSlice`s which do support FQDNs suprisingly. An option could be to write a endpointslice controller that creates objects with the pod hostnames of the statefulset, and have the ingress controller use those`EndpointSlice`s. Which would be fun but also a bit of work, so I wanted to check here if anyone has better ideas :)

Thanks!

**Comment by pleshakov** [comment]
Hi @defect 

What key do you use for the `hash` load balancing method? Have you tried to use the `consistent` parameter, which helps to minimize key remappings when upstreams servers are added/removed?

Perhaps the following approach can work for you?

The approach relies on the [VirtualServer](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/) resource which allows selecting endpoints based in pod labels and also configuring a [split _client](http://nginx.org/en/docs/http/ngx_http_split_clients_module.html#split_clients):

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: hello 
spec:
  host: hello.example.com
  upstreams:
  - name: hello-0
    service: hello 
    subselector:
      statefulset.kubernetes.io/pod-name: hello-0
    port: 8080
  - name: hello-1
    service: hello 
    subselector:
      statefulset.kubernetes.io/pod-name: hello-1
    port: 8080
  routes:
  - path: /
    splits:
    - weight: 50
      action:
        pass: hello-0 
    - weight: 50
      action:
        pass: hello-1 
```

For the backend, I used the following service and stateful set:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: hello
  selector:
    app: hello
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  serviceName: hello
  replicas: 2 
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
```

It is also necessary to deploy a [custom template](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/custom-templates/) for the VirtualServer resources with the following modification:
```
     . . .
    {{ range $sc := .SplitClients }}
    split_clients $request_uri {{ $sc.Variable }} {
        {{ range $d := $sc.Distributions }}
        {{ $d.Weight }} {{ $d.Value }};
        {{ end }}
    }
    {{ end }}
    . . .
```
Here we changed the split clients directive to use `$request_uri`. Unfortunately, it's not yet possible to configure the split clients key in the VirtualServer resource.

Now, if I try to send requests to `hello.example.com`, I will get stickiness per URI:

```
$ curl http://hello.example.com/123
Server address: 10.8.0.33:8080
Server name: hello-1
. . .
Request ID: 4ea2b0a8511b83dd5bd3090577d2fc26
$ curl http://hello.example.com/123
Server address: 10.8.0.33:8080
Server name: hello-1
. . .
Request ID: 170037671fe3149e6426a99eb7627f0f
$ curl http://hello.example.com/123
Server address: 10.8.0.33:8080
Server name: hello-1
. . .
Request ID: 3d2d7680bd6deee126e5d449ec85565f
$ curl http://hello.example.com/abc
Server address: 10.8.1.106:8080
Server name: hello-0
. . .
Request ID: e2732d14bb7bc72b16f9c99820adae1c
$ curl http://hello.example.com/abc
Server address: 10.8.1.106:8080
Server name: hello-0
. . .
Request ID: 311d0a57262756da7c0fd449efb1c217
$ curl http://hello.example.com/abc
Server address: 10.8.1.106:8080
Server name: hello-0
. . .
```

With this approach, if a hello pod goes down or become unavailable, NGINX will start returning 502s until the pod is back up again.
