### ISSUE TITLE
Nginx Ingress Transparent Reverse Proxy To Preserve Request Path

### ISSUE THREAD

**Issue by rkapoor028** [nginxinc/kubernetes-ingress#1143]
We are trying to route from a namespace(MajorVersion: /v1/) to another namespace(MinorVersion: /v1.1/).  This is a requirement for us as the MinorVersions would be expired and removed but MajorVersion will always be updated to point to the latest Minorversion.

We are trying to achieve what is described here trying to do a transparent rewrite and not set the Location header as we want to preserve the /v1/ path but rewrite the request to the backend in another namespace as /v1.1/

https://www.linuxrecruit.co.uk/blog?title=Kubernetes%20Nginx%20Ingress%3A%20Traffic%20Redirect%20Using%20Annotations%20Demystified&id=132

curl -v https://services-test.example.com/tasks/v1/
 ``` Trying 52.251.X.X...
* TCP_NODELAY set
* Connected to services-test.example.com (52.251.10.38) port 443 (#0)
* schannel: SSL/TLS connection with services-test.example.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 199 bytes...
* schannel: sent initial handshake data: sent 199 bytes
* schannel: SSL/TLS connection with services-test.example.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with services-test.example.com port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 193
* schannel: encrypted data buffer: offset 193 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with services-test.example.com port 443 (step 2/3)
* schannel: encrypted data got 121
* schannel: encrypted data buffer: offset 314 length 4096
* schannel: sending next handshake data: sending 93 bytes...
* schannel: SSL/TLS connection with services-test.example.com port 443 (step 2/3)
* schannel: encrypted data got 274
* schannel: encrypted data buffer: offset 274 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with services-test.example.com port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /tasks/v1/ HTTP/1.1
> Host: services-test.example.com
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 607
* schannel: encrypted data buffer: offset 607 length 103424
* schannel: decrypted data length: 578
* schannel: decrypted data added: 578
* schannel: decrypted data cached: offset 578 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 578 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 578
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 308 Permanent Redirect
< Server: nginx/1.19.2
< Date: Sun, 13 Sep 2020 20:56:21 GMT
< Content-Type: text/html
< Content-Length: 171
< Connection: keep-alive
< Set-Cookie: route=1600030582.108.1430.650625; Path=/; SameSite=None; Secure; HttpOnly
< **Location: https://services-test.example.com/tasks/v1.1/**
< Strict-Transport-Security: max-age=15724800; includeSubDomains
< 
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.19.2</center>
</body>
</html>
```

We think if we can avoid the Location header as being modified above, it can help us. Any suggestions how to do this?

**Comment by rkapoor028** [comment]
Major Version Namespace, we are using ExternalName type Service to forward the request: /tasks/v1/(.*) to another namespace and by nginx.ingress.kubernetes.io/rewrite-target: /tasks/v1.1/$1

```apiVersion: v1
kind: Service
metadata:
  name: tasks-v1-service
  # labels:
  #  app: tasks-v1-ingress
spec:
  type: ExternalName
  externalName: msvctaskseu2-test.example.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tasks-v1-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /tasks/v1.1/$1
# cookie based session affinity
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-path: "/; SameSite=None"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header  X-Tasks-MS-Version  "v1.1" always;
spec:
  tls:
  - hosts:
    -  https://services-test.example.com
    secretName: ingress-tls
  - hosts:
    - msvctaskseu2-test.example.com
    secretName: ingress-tls
  rules:
  - host: services-test.example.com
    http:
      paths:
      - path: /tasks/v1/(.*)
        backend:
          serviceName: tasks-v1-service
          servicePort: 80
  - host: msvctaskseu2-test.example.com
    http:
      paths:
      - path: /tasks/v1/(.*)
        backend:
          serviceName: tasks-v1-service
          servicePort: 80```
```

MinorVersion Namespace, we are serving requests from /tasks/v1.1/(.*) to the backend service ticket-web but by rewring the request to nginx.ingress.kubernetes.io/rewrite-target: /$1 as the backend api expects it as /$1

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ticket
  name: ticket-web
  namespace: tasks-v1-1
spec:
  clusterIP: 10.X.211.X
  ports:
  - name: query-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ticket
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/session-cookie-path: /; SameSite=None
  generation: 1
  labels:
    app: ticket
  name: tasks-v1-1-ingress
  namespace: tasks-v1-1
spec:
  rules:
  - host: services.example.com
    http:
      paths:
      - backend:
          serviceName: ticket-web
          servicePort: 80
        path: /tasks/v1.1/(.*)
  - host: msvctaskseu2-prod.example.com
    http:
      paths:
      - backend:
          serviceName: ticket-web
          servicePort: 80
        path: /tasks/v1.1/(.*)
  tls:
  - hosts:
    - services.example.com
    secretName: ingress-tls
  - hosts:
    - msvctaskseu2-prod.example.com
    secretName: ingress-tls
status:
  loadBalancer:
    ingress:
    - {}
```

All of this works fine with nginx ingress controller 0.27(quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.27.0) but stops to work after that version.

Any insights will be greatly appreciated.
