### ISSUE TITLE
Cannot connect to websockets with SignalR client with nginx-ingress

### ISSUE THREAD

**Issue by charconstpointer** [nginxinc/kubernetes-ingress#1172]
**Describe the bug**
Cannot connect to websockets (SignalR) with nginx-ingress in front of my service
```
WebSocket connection to 'ws://foobar.com/player/schedule-ws?id=LcSVQ_OEJ2O44Khh3rzKjA' failed: Error during WebSocket handshake: Unexpected response code: 503
```
**To Reproduce**
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "4m"
    nginx.org/rewrites: "serviceName=player-svc rewrite=/;"
    nginx.org/websocket-services: "player-svc"
  name: rk-ingress
spec:
  rules:
    - host: "foobar.com"
      http:
        paths:
          - path: /player/
            backend:
              serviceName: player-svc
              servicePort: 5030
```
svc
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: player
spec:
  replicas: 2
  selector:
    matchLabels:
      app: player
  template:
    metadata:
      labels:
        app: player
    spec:
      containers:
        - name: player
          image: playerimage
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
          ports:
            - containerPort: 5030
---
apiVersion: v1
kind: Service
metadata:
  name: player-svc
spec:
  selector:
    app: player
  ports:
    - port: 5030
      targetPort: 5030
```

These are the headers my server receives
```
POST /schedule-ws/negotiate?negotiateVersion=1                 
Key: Connection Value :close                                   
Key: Content-Type Value :text/plain;charset=UTF-8              
Key: Accept Value :*/*                                         
Key: Accept-Encoding Value :gzip, deflate                      
Key: Accept-Language Value :en-US,en;q=0.9,pl;q=0.8            
Key: Host Value :foobar.com                                    
Key: Referer Value :http://foobar.com/                         
Key: User-Agent Value :Mozilla/5.0 (Windows NT 10.0; Win64; x6 
Key: DNT Value :1                                              
Key: Origin Value :http://foobar.com                           
Key: Content-Length Value :0                                   
Key: X-Real-IP Value :172.16.121.136                           
Key: X-Forwarded-For Value :172.16.121.136                     
Key: X-Forwarded-Host Value :foobar.com                        
Key: X-Forwarded-Port Value :80                                
Key: X-Forwarded-Proto Value :http                             
Key: X-Requested-With Value :XMLHttpRequest  
                  
POST /schedule-ws/negotiate?negotiateVersion=1                 
Key: Connection Value :close                                   
Key: Content-Type Value :text/plain;charset=UTF-8              
Key: Accept Value :*/*                                         
Key: Accept-Encoding Value :gzip, deflate                      
Key: Accept-Language Value :en-US,en;q=0.9,pl;q=0.8            
Key: Host Value :foobar.com                                    
Key: Referer Value :http://foobar.com/                         
Key: User-Agent Value :Mozilla/5.0 (Windows NT 10.0; Win64; x6 
Key: DNT Value :1                                              
Key: Origin Value :http://foobar.com                           
Key: Content-Length Value :0                                   
Key: X-Real-IP Value :172.16.121.136                           
Key: X-Forwarded-For Value :172.16.121.136                     
Key: X-Forwarded-Host Value :foobar.com                        
Key: X-Forwarded-Port Value :80                                
Key: X-Forwarded-Proto Value :http                             
Key: X-Requested-With Value :XMLHttpRequest     
```
This is how my headers look like whenever i run my app with just docker run and expose the port, below snippet is from working application(successful connection over ws)
```
POST /schedule-ws/negotiate?negotiateVersion=1
Key: Host Value :foobar.com
Key: User-Agent Value :Microsoft.AspNetCore.Http.Connections.Client/3.1.7
Key: Content-Length Value :0
Key: X-Requested-With Value :XMLHttpRequest
POST /schedule-ws/negotiate?negotiateVersion=1
Key: Host Value :foobar.com
Key: User-Agent Value :Microsoft.AspNetCore.Http.Connections.Client/3.1.7
Key: Content-Length Value :0
Key: X-Requested-With Value :XMLHttpRequest
GET /schedule-ws?id=jbz69KJ9hIJmGze9D8K04Q
Key: Accept Value :text/event-stream
Key: Host Value :foobar.com
Key: User-Agent Value :Microsoft.AspNetCore.Http.Connections.Client/3.1.7
Key: X-Requested-With Value :XMLHttpRequest
POST /schedule-ws?id=jbz69KJ9hIJmGze9D8K04Q
Key: Host Value :foobar.com
Key: User-Agent Value :Microsoft.AspNetCore.Http.Connections.Client/3.1.7
Key: Content-Length Value :32
Key: X-Requested-With Value :XMLHttpRequest
POST /schedule-ws?id=jbz69KJ9hIJmGze9D8K04Q
Key: Host Value :foobar.com
Key: User-Agent Value :Microsoft.AspNetCore.Http.Connections.Client/3.1.7
Key: Content-Length Value :11
Key: X-Requested-With Value :XMLHttpRequest
```

**Your environment**
This is how i install the controller
 helm install release nginx-stable/nginx-ingress --set controller.kind=daemonset
```
Image:         nginx/nginx-ingress:1.8.1
Image ID:      docker.io/nginx/nginx-ingress@sha256:62dbfa55922efaaa1044da6b97459faabe013abd810559486abe0c9df5a7eeef
Ports:         80/TCP, 443/TCP, 9113/TCP, 8081/TCP
Host Ports:    80/TCP, 443/TCP, 0/TCP, 0/TCP
```
k8s v1.18.9 
Bare metal with metalLB and calico
