### ISSUE TITLE
Unable to made Proxy protocol work

### ISSUE THREAD

**Issue by pichouk** [nginxinc/kubernetes-ingress#118]
I'm using Kubernetes with nginx-ingress-controller on my nodes and I managed to setup proxy protocol.

I configured this DaemonSet :
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
spec:
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - image: nginxdemos/nginx-ingress
        name: nginx-ingress-lb
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=default/default-http-backend
        - --nginx-configmap=default/nginx
      nodeSelector:
         type: node
```
with the following ConfigMap
```
apiVersion: v1
data:
  body-size: 256m
  http2: "True"
  proxy-protocol: "True"
  real-ip-header: proxy_protocol
  set-real-ip-from: 10.108.0.0/19
kind: ConfigMap
metadata:
  name: nginx
  namespace: default
```

I tried to reach a simple webserver `test.mydomain.com`, my loadbalancer is configured to reach my node with an IP addr from `10.108.0.0/19`.
In my ingress controller logs, I have the following :
```
10.108.5.159 - - [20/Feb/2017:14:28:29 +0000] "PROXY TCP4 10.108.5.159 178.38.81.13 5939 80" 400 0 "-" "-" "-"
```
So my ingress controller get an HTTP 400 error when I tried to reach `test.mydomain.com` (which redirect to the public loadbalancer IP).

It seems that I have an issue with the ProxyProtocol configuration, because the nginx configuration file in my ingress container look like this : 
```
upstream default-webtest-test.mydomain.com-webtest {
        server 10.40.0.60:80;
}

server {
        listen 80;
        server_name test.mydomain.com;

        location / {
                proxy_http_version 1.1;
                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;
                proxy_pass http://default-webtest-test.mydomain.com-webtest;
        }
}
```

I don't understand what I did wrong, but it seems that the nginx ingress controller doesn't have the right configuration for Proxy Protocol.

Any ideas ?
