### ISSUE TITLE
Session affinity is not working in new version

### ISSUE THREAD

**Issue by MartinsPuspurs** [nginxinc/kubernetes-ingress#1191]
**Describe the bug**
Session affinity is not working for services with 2 or more replicas and returns session timeout error

**To Reproduce**
Deploy latest controller with helm 3
Deploy service with at least 2 pods
Try connecting it

**Expected behavior**
Sticky session should work

**Your environment**
* Version of the Ingress Controller - latest 1.8.1
* Version of Kubernetes - 1.16.13-gke.1
* Kubernetes platform - GCP
* Using NGINX 

**Additional context**
My configs
Nginx controller args:
```
containers:
      - args:
        - -nginx-plus=false
        - -nginx-configmaps=$(POD_NAMESPACE)/nginx-ingress-nginx-ingress
        - -default-server-tls-secret=$(POD_NAMESPACE)/nginx-ingress-nginx-ingress-default-server-secret
        - -ingress-class=nginx
        - -use-ingress-class-only=false
        - -health-status=false
        - -health-status-uri=/nginx-health
        - -nginx-debug=false
        - -v=1
        - -nginx-status=true
        - -nginx-status-port=8080
        - -nginx-status-allow-cidrs=127.0.0.1
        - -report-ingress-status
        - -external-service=nginx-ingress-nginx-ingress
        - -enable-leader-election=true
        - -leader-election-lock-name=nginx-ingress-nginx-ingress-leader-election
        - -enable-prometheus-metrics=true
        - -prometheus-metrics-listen-port=9113
        - -enable-custom-resources=true
        - -enable-tls-passthrough=false
```
Ingress annotations
```
annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: release
    meta.helm.sh/release-namespace: release-ns
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/session-cookie-expires: "17280"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-max-age: "17280"
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/session-cookie-path: '/'
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/hsts: "false"
    nginx.org/server-tokens: "true"
    nginx.org/websocket-services: my-service
```
Ingress spec:
```
spec:
  rules:
  - host: my.host.com
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: app-port
        path: /
  tls:
  - hosts:
    - my.host.com
    secretName: my-service-tls-le
```
Nginx configmap
```
data:
  allow-backend-server-header: "true"
  body-size: 15m
  client-max-body-size: 15m
  custom-http-errors: 404,502,503,504
  enable-vts-status: "true"
  proxy-body-size: 15m
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  server-name-hash-bucket-size: "1024"
  ssl-redirect: "false"
  ssl_prefer_server_ciphers: "true"
  use-forwarded-headers: "true"
  use-proxy-protocol: "true"
```

Also when opening developer console I cannot see my cookie being present at all, not to mention that also whitelisting isn't working. ExternalTraffickPolicy is set to local
