### ISSUE TITLE
how can i add this secrets auth_basic_user_file "/var/run/secrets/nginx.org/auth-basic-file";

### ISSUE THREAD

**Issue by alirezaDavid** [nginxinc/kubernetes-ingress#120]
I want using basic auth in nginx ingress , i tried for annotations but didn't work.
tried like this:

```
  annotations:
    # type of authentication
    ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropiate context why the authentication is required
    ingress.kubernetes.io/auth-realm: "Authentication Required"
```

i using `kubernetes-ingress`   image.

i saw this in example:
```
   nginx.org/location-snippets: |
        if ($ssl_client_verify = SUCCESS) {
            set $auth_basic off;
        }
        if ($ssl_client_verify != SUCCESS) {
            set $auth_basic "Restricted";
        }
        auth_basic $auth_basic;
        auth_basic_user_file "/var/run/secrets/nginx.org/auth-basic-file";
```
My main question is how can i add basic auth file to `/var/run/secrets/nginx.org/auth-basic-file` location?
Thanks
