### ISSUE TITLE
Is path rewriting supported in virtual server?

### ISSUE THREAD

**Issue by hyc3z** [nginxinc/kubernetes-ingress#1218]
**Is your feature request related to a problem? Please describe.**

Is path rewriting supported in virtual server?
The following example posted on https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/

```
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    action:
      pass: tea
  - path: /coffee
    action:
      pass: coffee
  - path: ~ ^/decaf/.*\\.jpg$
    action:
      pass: coffee
  - path: = /green/tea
    action:
      pass: tea
```

requests to cafe.example.com/tea will be redirected to `tea` service, however, we want it seems to be `'/'` , not` '/tea'` that is actually exposed to the service. I can't find descriptions about this in the document, am  I missing?
