### ISSUE TITLE
Support pod security policies

### ISSUE THREAD

**Issue by mofm** [nginxinc/kubernetes-ingress#1234]
**Is your feature request related to a problem? Please describe.**
I have bare-metal k8s cluster with restricted psp and gives failedcreate error when deploy nginx-ingress with helm.

`$ helm install my-ingress05 nginx-stable/nginx-ingress --set controller.kind=daemonset --set controller.service.type=LoadBalancer --set rbac.create=true --set controller.setAsDefaultIngress=true -n nginx-ingress`

error logs:
`nginx-ingress    30s         Warning   FailedCreate       daemonset/my-ingress05-nginx-ingress   Error creating: pods "my-ingress05-nginx-ingress-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added spec.containers[0].hostPort: Invalid value: 80: Host port 80 is not allowed to be used. Allowed ports: [] spec.containers[0].hostPort: Invalid value: 443: Host port 443 is not allowed to be used. Allowed ports: [] spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed]`

**Describe the solution you'd like**
It would be great if the PSP pertaining to nginx-ingress are included in the deployment and documentation. for example; https://kubernetes.github.io/ingress-nginx/examples/psp/ .
I could not find any documentations.

**Comment by rossbachp** [comment]
Enable PSP:

podSecurityPolicy:
  enabled: true

**Comment by mofm** [comment]
@rossbachp Could you please explain this?

**Comment by mofm** [comment]
I have created 'ClusterRole' with privileged psp and rolebinding:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-psp-clusterrole
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use

```
`$ kubectl -n nginx-ingress create rolebinding ingress-psp-clusterrole-rolebinding --clusterrole=ingress-psp-clusterrole --group=system:serviceaccounts:nginx-ingress`

After, nginx-ingress has been deployed successfully.  I know that it's risky with privileged psp. But I didn't want to bother too much.

I am waiting documentations and psp for restricted psp.
