### ISSUE TITLE
v1.19.0 the hosts or paths can not  match the HTTP request by nginx-ingress

### ISSUE THREAD

**Issue by pangwawa** [nginxinc/kubernetes-ingress#1251]
**Describe the bug**

I try to visit my service running on kubernetes  cluster by ingress，but faill

tell me why please, thanks

**To Reproduce**
 cat faskapp-deployment.yaml 
`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-1
spec:
  selector:
    matchLabels:
      run: flaskapp-1
  replicas: 1
  template:
    metadata:
      labels:
        run: flaskapp-1
    spec:
      containers:
      - name: flaskapp-1
        image: jcdemo/flaskapp
        ports:
        - containerPort: 5000
```
`

cat faskapp-service.yaml

```

apiVersion: v1
kind: Service
metadata:
  name: flaskapp-1
  labels:
    run: flaskapp-1
spec:
  ports:
  - port: 5000
    name: web
    targetPort: 5000 
  selector:
    run: flaskapp-1
```

cat faskapp-ingress.yaml 

`
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: faskapp-ingress
  #kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: mydemo.com     
    http:
      paths:
      - path: /
        backend:
          serviceName: flaskapp-1  
          servicePort: 5000 
```

kubectl describe ingress 
```
Name:             faskapp-ingress
Namespace:        default
Address:          192.168.161.121
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  mydemo.com  
              /   flaskapp-1:5000   10.244.97.193:5000)
Annotations:  <none>
Events:
  Type    Reason  Age                    From                      Message
  ----    ------  ----                   ----                      -------
  Normal  Sync    2m14s (x2 over 2m25s)  nginx-ingress-controller  Scheduled for sync

```
**Your environment**
kubernetes version : v1.19.0 
ingress-nginx version : v0.41.0
**Expected behavior**
I want to visit my service  through domain name  ' mydemo.com'   ，domain name resolution is ok

**Additional context**
the envirnoment is fine,  and I have tried to visit my service by "NodePort Type" , it work
