### ISSUE TITLE
invalid client header line when using underscores_in_headers + CURL / POSTMAN

### ISSUE THREAD

**Issue by jeanluclariviere** [nginxinc/kubernetes-ingress#1254]
**Describe the bug**
We're seeing what appears to be a bug on the ingress controller where POSTING to a an endpoint which requires a header with underscores works using the swagger-ui, but fails with a **client sent invalid header line** if we try and CURL / Postman. This is after setting the **underscores_in_headers on;** as part of the **nginx.org/server-snippets**.

App was developed with springboot framework.

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: example
  annotations:
    nginx.org/server-snippets: |
      underscores_in_headers on;
spec:
  rules:
  - host: abc.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: example-service
          servicePort: 8080
```

**To Reproduce**
1. Host a basic spring boot application that takes in a header "api_key" (with underscores). 
2. In the ingress rule, allow those underscores by adding annotations using server-snippets + underscores_in_headers on;
3. Try POSTing to your endpoint with the "api_key" header using swagger-ui and watch it succeed.
4. Try POSTing to your endpoint using CURL / Postman and the nginx ingress controller will complain: **client sent invalid header line**

**Expected behavior**
Prior to setting **underscores_in_headers on;** we would receive the error, but after setting this, the swagger-ui functions as expected and our request is successful. So we expect that setting **underscores_in_headers on;** and POSTing to the endpoint using CURL / Postman should function just like when we use swagger-ui.

**Your environment**
* Version of the Ingress Controller: nginx-ingress:1.5.3
* Version of Kubernetes: 1.18.8
* Kubernetes platform: bare-metal, kubeadm.
* Using NGINX or NGINX Plu: nginx

**Other**
We've also tried configuring **ignore_invalid_headers off;**, and we tried setting both of these at the ingress rule level and configmap level, neither of which solves the issue.
