### ISSUE TITLE
question about the Host in ingress resource

### ISSUE THREAD

**Issue by jackie-JD** [nginxinc/kubernetes-ingress#1268]
**Describe the bug**
Currently, I am trying to testing using the kubernetes-ingress. 
(1) I have deployed the kubernetes-ingress
(2) I deployed two backend services: hostname-svc and apache-svc and ingress resource
(3) My ingress yaml is as follows:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hostname.mydomain.com
      http:
        paths:
          - path: /login
            backend:
                serviceName: hostname-svc
                servicePort: 80
          - path: /cart
            backend:
                serviceName: apache-svc
                servicePort: 80
```

(4) For a Deployment ingress-controller, I deployed the service: loadbalancer-aws-elb.yaml service.
(5) Got the  LB's DNS : xxxxxxx07xxxx-xxxxxx.us-east-1.elb.amazonaws.com
(6)  I use the following method to access my service and are all OK:
`curl -I -H "Host: hostname.mydomain.com" http://xxxxxxx07xxxx-xxxxxx.us-east-1.elb.amazonaws.com/login`
`curl -I -H "Host: hostname.mydomain.com" http://xxxxxxx07xxxx-xxxxxx.us-east-1.elb.amazonaws.com/cart`

BUT, i do not want to use the host: hostname.mydomain.com to access the backed services.
I want to access them directly like: `curl http://xxxxxxx07xxxx-xxxxxx.us-east-1.elb.amazonaws.com/login` or `http://xxxxxxx07xxxx-xxxxxx.us-east-1.elb.amazonaws.com/cart`

I am very confuse about this and do know how to do it.
Could you help me to resolve this issue ?
Thank you very much.

**To Reproduce**
1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**
I do not want to use the host: hostname.mydomain.com to access the backed services.
I want to access them directly like:  `curl http://xxxxxxx07xxxx-xxxxxx.us-east-1.elb.amazonaws.com/login or http://xxxxxxx07xxxx-xxxxxx.us-east-1.elb.amazonaws.com/cart`
**Your environment**
* Version of the Ingress Controller - release version or a specific commit
* Version of Kubernetes
* Kubernetes platform (e.g. Mini-kube or GCP)
* Using NGINX or NGINX Plus

**Additional context**
Add any other context about the problem here. Any log files you want to share.

1. 
I tried to use the following ingress style:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-ingress
spec:
  rules:
    - http:
        paths:
          - path: /login
            backend:
              serviceName: hostname-svc
              servicePort: 80
          - path: /cart
            backend:
              serviceName: apache-svc
              servicePort: 80
```

When I access the backed service like:
```
curl http://xxxxxxx07xxxx-xxxxxx.us-east-1.elb.amazonaws.com/login
and I get the following errors:
HTTP/1.1 404 Not Found
Server: nginx/1.19.3
Date: Fri, 04 Dec 2020 16:44:55 GMT
Content-Type: text/html
Content-Length: 153
Connection: keep-alive
```

2. and I use the command:
kubectl describe ingress to check my ingress resource. I found that there is one warning in the event section:

```
C:\work\iso\CIS\docker>kubectl describe ingress
Name:             path-ingress
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /login   hostname-svc:80 (192.168.3.202:9376,192.168.77.75:9376)
              /cart    apache-svc:80 (192.168.15.172:9376,192.168.77.221:9376)
Annotations:  <none>
Events:
  Type     Reason    Age   From                      Message
  ----     ------    ----  ----                      -------
  Warning  Rejected  5s    nginx-ingress-controller  spec.rules[0].host: Required value
```

**Comment by pleshakov** [comment]
Hi @jackie-JD 

If you have only a single Ingress resource, I can suggest the following workaround as described here https://github.com/nginxinc/kubernetes-ingress/issues/209#issuecomment-581691384
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/server-snippets: "server_name ~^.*$;"
. . .
```

In general, your `curl` requests need to use the same host header as the host in your Ingress resource.

also, our Ingress Controller requires that the host field in Ingress resources in not empty

hope this helps
