### ISSUE TITLE
Specifying hosts under tls shouldn't be required when using a wildcard cert

### ISSUE THREAD

**Issue by xrl** [nginxinc/kubernetes-ingress#127]
I used the kubernetes-ingress for the first time today and ran in to an issue using a wildcard cert: I didn't want to have to specify the hosts. Here is my config:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysite-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: mysite-wildcard-cert
      hosts:
      - avatars.mysite.com
  rules:
  - host: avatars.mysite.com
    http:
      paths:
      - path: /
        backend:
          serviceName: avatars
          servicePort: 80
```

It would be nice if `mysite-wildcard-cert` secret was used without having to specify `avatars.mysite.com`.

The offending piece of code appears to be here: https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/nginx/configurator.go#L72-L77 , reading:

```
for _, host := range tls.Hosts {
  pems[host] = pemFileName
}
if len(tls.Hosts) == 0 {
  pems[emptyHost] = pemFileName
}
```

With the hosts list the config was stored under the `""` key... how can I use that for the ingress rule?
