### ISSUE TITLE
Regexps not be honoured

### ISSUE THREAD

**Issue by bechampion** [nginxinc/kubernetes-ingress#1279]
**Describe the bug**
When using regexps on the `path` the `location` parameter inside nginx doesn't contain `~*` , which means the regexps aren't evaluated

I've seen a lot of deliberation online about this issue ,  i basically had to resort to store my one chart (from the deprecated list , as this used to work before)
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4300", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-10-28T09:23:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
helm:
```test-ingress    default         1               2020-12-11 15:28:44.544882815 +0000 UTC deployed        nginx-ingress-edge      edge```

Location issue
```
~/Projects/si/kubernetes-ingress/deployments(master ✔) k exec -it test-ingress-nginx-ingress-785bc7fb89-n5lsz -- bash -c 'grep -R location /etc/nginx/conf.d/*'
        location /dada/(.*) {
```

Ingress:
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
    creationTimestamp: "2020-12-11T15:23:09Z"
    finalizers:
    - networking.gke.io/ingress-finalizer-V2
    generation: 1
    name: dada
    namespace: default
  spec:
    rules:
    - host: dada.com
      http:
        paths:
        - backend:
            serviceName: dada
            servicePort: 80
          path: /dada/(.*)
```

**Comment by pleshakov** [comment]
Hi @bechampion 

The annotation `nginx.ingress.kubernetes.io/use-regex: "true"` is supported by this Ingress Controller https://github.com/kubernetes/ingress-nginx , which is a different project. More about differences here -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md

If you'd like to use regex with our Ingress Controller,  it is supported in VirtualServerResource -- https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/
For example:
```yaml
  - path: ~ ^/decaf/.*\\.jpg$
    action:
      pass: coffee
```
