### ISSUE TITLE
Even though the ingress class is set as the default I still had to specify the ingress class in my application ingress

### ISSUE THREAD

**Issue by javapenguin** [nginxinc/kubernetes-ingress#1283]
**Describe the bug**
Even though the ingress class is set as the default I still had to specify the ingress class in my application ingress

**To Reproduce**
I create my ingress class and set it as the default:
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: nginx.org/ingress-controller
```
If I specify the ingress class in my application's ingress then it works:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apache-app
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: apache.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: apache-app
              servicePort: 80

```
If I remove the annotation (kubernetes.io/ingress.class: "nginx") from my application's ingress then it doesn't work.

**Expected behavior**
My expectation was that if the ingress class is set as the default, then it should work even if I don't specify the ingress class in my application's ingress

**My environment**
* Version of the Ingress Controller - v1.9.1
* Version of Kubernetes - v1.18.9
* Kubernetes platform - Amazon EKS 
* Using NGINX not NGINX Plus

**Comment by pleshakov** [comment]
Hi @javapenguin 

> If I remove the annotation (kubernetes.io/ingress.class: "nginx") from my application's ingress then it doesn't work.

> My expectation was that if the ingress class is set as the default, then it should work even if I don't specify the ingress class in my application's ingress

The default Ingress class will only be assigned to an Ingress on creation (as per documentation [here](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class)). In your case, it looks like you were expecting the class to be assigned after updating the Ingress.

**Comment by javapenguin** [comment]
I deleted my application's ingress  
Applied my ingress class again (obviously no changes)  
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: nginx.org/ingress-controller
```
Created my ingress without the ingress class specified
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apache-app
  namespace: default
spec:
  rules:
    - host: apache.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: apache-app
              servicePort: 80
```
Tested my application
```
# curl -I -H "host:apache.mydomain.com" http://internal-a8250e03dc09543b0b932dc5cf1c4a4d-1732105455.af-south-1.elb.amazonaws.com/
HTTP/1.1 404 Not Found
...
```
Not working  
Applied my ingress again, this time with the ingress class specified
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apache-app
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: apache.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: apache-app
              servicePort: 80

```
Tested my application again
```
# curl -I -H "host:apache.mydomain.com" http://internal-a8250e03dc09543b0b932dc5cf1c4a4d-1732105455.af-south-1.elb.amazonaws.com/
HTTP/1.1 200 OK
...
```
Working

**Comment by pleshakov** [comment]
@javapenguin 
Could you try to update the apiVersion to `apiVersion: networking.k8s.io/v1beta1` in your Ingresses? That should fix the problem

**Comment by javapenguin** [comment]
That fixed the problem
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apache-app
  namespace: default
spec:
  rules:
    - host: apache.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: apache-app
              servicePort: 80
```
**Thank you very much.**
