### ISSUE TITLE
http to https redirection while ssl termination at Load Balancer Level

### ISSUE THREAD

**Issue by niraj1234567890** [nginxinc/kubernetes-ingress#1296]
I am trying to achieve http to https redirection while SSL termination is happening at aws load balancer level. I have tried so many configurations but couldn't able to achieve what I want to. I am mentioning here the configuration which I feel should work(Maybe I am missing some small things).

I am trying to create/use one custom port(8000) on ingress controller, which can be used to redirect http requests to https. Below are the configuration files to better understand my use case.

## ingerss.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource-1
  annotations:
    nginx.org/websocket-services: "MyService"
spec:
  ingressClassName: nginx
  rules:
  - host: foo.com
    http:
      paths:
      - backend:
          serviceName: MyService
          servicePort: 80
```

## config.yaml
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: nginx.org/ingress-controller
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  proxy-protocol: "True"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "0.0.0.0/0"
  server-snippet: |
      listen 8000;
      return 308 https://$host$request_uri;

```

## daemon-set.yaml (only ports section)
```
ports:
        - name: http
          containerPort: 80
          hostPort: 80
       - name: http-to-https
          containerPort: 8000
          hostPort: 8000
        - name: https
          containerPort: 443
          hostPort: 443
```

## service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <aws-ssl-certificate-arn>
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 80
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
```

### What's happening:

AWS load balancer's status remains always inactive and the reason behind this is because I am trying to create/use a port no 8000 on ingress controller which is other than the default ones(80 and 443). If I don't use custom port 8000 then my service is working properly BUT then I am not able to figure out how to achieve redirection working.

**Comment by pleshakov** [comment]
Hi @niraj1234567890 

Could you try to use the `redirect-to-https` ConfigMap key? (see https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssl-tls )

with `redirect-to-https`, the redirect is based on the `X-Forwarded-Proto`, which the ELB sets.
However, it is necessary to use either `https` or `http` in ` service.beta.kubernetes.io/aws-load-balancer-backend-protocol`

**Comment by niraj1234567890** [comment]
Hi @pleshakov , Thanks for the response. BUT I can't use http or https as a load-balancer-backend-protocol because my application is using websockets. I have to use tcp in my case. Otherwise your suggested solution would have been definitely worked for me.

**Comment by pleshakov** [comment]
with the workaround described here https://github.com/nginxinc/kubernetes-ingress/issues/1209#issuecomment-716894309 it should be possible to issue a redirect if ELB handled the connection on its http port. Could you see if it can work for you?

**Comment by niraj1234567890** [comment]
@pleshakov, I have tried implementing the given work around. BUT my nginx configuration is not getting updated due to one error and logs from the nginx-config says: 

**Error**: variable **server** is not defiend

My updated configMap file:

```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: nginx.org/ingress-controller
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  proxy-protocol: "True"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "0.0.0.0/0"
  redirect-to-https: "True"
  ingress-template: |
        {{- if $server.RedirectToHTTPS}}
        if ($proxy_protocol_server_port != '443') {
          return 301 https://$host$request_uri;
        }
        {{- end}}
```
as it can be understood, this error is refering to **$server.RedirectToHTTPS** but I am not able to understand the reason behind this error.
Is there anything else I need to change in order to achieve the redirection other than changing the config-map the way I just did.
