### ISSUE TITLE
Path based routing breaks with two similar paths

### ISSUE THREAD

**Issue by jeanluclariviere** [nginxinc/kubernetes-ingress#1305]
**Describe the bug**
We're implementing path based routing in a single namespace and are seeing odd behavior when trying to add two separate ingress rules with similar paths. Routing will break to "abc-frontend" when we add the ingress which routes traffic to "abc-backend"

**To Reproduce**
Consider the following two ingress rules for a backend and frontend services, sharing the same host. When we apply these two separate ingress rules, traffic stops being forwarded to the "/abc-ui/" service entirely. If we remove the backend-ingress however, traffic for the frontend resumes.

**Backend ingress**
```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: abc-backend-ingress
  namespace: abc
  annotations:
    nginx.org/client-max-body-size: "0"
spec:
  rules:
  - host: abc.example.com
    http:
      paths:
      - path: /abc/
        backend:
          serviceName: abc-backend-service
          servicePort: 8080
```

**frontend-ingress**
```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: abc-frontend-ingress
  namespace: abc
spec:
  rules:
  - host: abc.example.com
    http:
      paths:
      - path: /abc-ui/
        backend:
          serviceName: abc-frontend-service
          servicePort: 8080
```

**Expected behavior**
I expect traffic matching the path in the backend-ingress to route traffic to the backend service, and the frontend-ingress to route traffic to the frontend ingress.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
nginx-ingress:1.5.3

* Version of Kubernetes
1.18.8

* Kubernetes platform (e.g. Mini-kube or GCP)
Kubeadm baremetal

* Using NGINX or NGINX Plus
Nginx

**Additional context**
If we configure both paths in a single rule, as follows, this works around the issue, but has the downside of having to manage both applications in a single ingress (we would need to duplicate this file across multiple projects which isn't good), and the annotations used for the backend (in this case client-max-body-size) are now also being applied to the frontend, which we don't want.

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: abc-ingress
  namespace: abc
  annotations:
    nginx.org/client-max-body-size: "0"
spec:
  rules:
  - host: abc.example.com
    http:
      paths:
      - path: /abc-ui/
        backend:
          serviceName: abc-frontend-service
          servicePort: 8080
      - path: /abc/
        backend:
          serviceName: abc-backend-service
          servicePort: 8080
```
