### ISSUE TITLE
Obtaining the IP/URL Address of the ingress nginx controller

### ISSUE THREAD

**Issue by farisrj** [nginxinc/kubernetes-ingress#1313]
### **Describe the issue**
how to get the ingress-nginx controller url to access the application.

I have running Kubernetes Cluster with one master and two worker nodes located on my LAN as follows:
	 - k8s-master       :  192.168.100.100
	 - worker-node-1 :  192.168.100.101
	 - worker-node-2 :  192.168.100.102

**It's just an on-premise Kubernetes setup , and I need the actual K8S ingress URL to hand it to network guy to place it in public f5 load balancer for internet traffic .**
N.B : nothing on the Cloud.

For, I have managed to setup the ingress nginx controller as mentioned from this url:
		[LINK](https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-457B1569-DFDC-4849-959C-72EDA72030AD.html)

### **To Reproduce**
Steps to reproduce the behavior
- Install the NGINX Ingress controller using Helm
   helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
   helm install ingress-nginx ingress-nginx/ingress-nginx
- Create and deploy an ingress resource with an ingress rule and path named **ingress-hello.yaml**
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hello
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: hello
          servicePort: 80
```
- Create and deploy a hello test app and service named **ingress-hello-test.yaml**
```
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
```

**I list all services deployed for now by execute below commands.**
 kubectl get svc
```
NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
hello                                NodePort       10.106.135.111   <none>        80:32138/TCP                 6h28m
ingress-nginx-controller             LoadBalancer   10.105.69.251    <pending>     80:30815/TCP,443:31480/TCP   6h37m
ingress-nginx-controller-admission   ClusterIP      10.97.248.10     <none>        443/TCP                      6h37m
kubernetes                           ClusterIP      10.96.0.1        <none>        443/TCP                      14d
```

**All pods are running fine**
kubectl get pods -o wide
```
NAME                                        READY   STATUS    RESTARTS   AGE     IP          NODE            NOMINATED NODE   READINESS GATES
hello-685445b9db-9vw7f                      1/1     Running   1          7h1m    10.5.2.6    worker-node-2   <none>           <none>
hello-685445b9db-g8ckd                      1/1     Running   1          7h1m    10.5.1.16   worker-node-1   <none>           <none>
hello-685445b9db-t8s4k                      1/1     Running   1          7h1m    10.5.1.14   worker-node-1   <none>           <none>
ingress-nginx-controller-56c75d774d-dc4pz   1/1     Running   1          7h10m   10.5.2.5    worker-node-2   <none>           <none>
```
**For ingress workload:**
  kubectl get ingress

```
NAME            CLASS    HOSTS   ADDRESS   PORTS   AGE
ingress-hello   <none>   *                 80      6h48m
```

kubectl describe  ingress ingress-hello

```
Name:             ingress-hello
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /hello   hello:80 (10.5.1.14:80,10.5.1.16:80,10.5.2.6:80)
Annotations:  kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /
Events:
  Type    Reason  Age                 From                      Message
  ----    ------  ----                ----                      -------
  Normal  Sync    6h49m               nginx-ingress-controller  Scheduled for sync
  Normal  Sync    114s (x3 over 54m)  nginx-ingress-controller  Scheduled for sync
```
