### ISSUE TITLE
doesn't work on kubeadm and kubernetes 1.6.1?

### ISSUE THREAD

**Issue by domino14** [nginxinc/kubernetes-ingress#136]
I can't get this ingress controller to work on the above described setup. It works fine in minikube. The main issue seems to be that somehow it doesn't detect the services or the SSL certs; the `conf.d` directory is empty and the generated `nginx.conf` is minimal:

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server_names_hash_max_size 512;


    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }







    include /etc/nginx/conf.d/*.conf;
}
```

My ingress-rc yaml file has the `hostNetwork: true` in it.

Anyone know what I can do? I'm kind of out of ideas. At some point I added a bunch of the rbac stuff that I found on this thread (https://github.com/kubernetes/ingress/issues/575) and got the logs in the ingress-rc pod to display this:

```
I0415 07:01:02.000192       1 utils.go:78] Syncing default/myapp-ingress
I0415 07:01:02.000262       1 controller.go:554] Syncing default/myapp-ingress
I0415 07:01:02.000292       1 controller.go:569] Adding or Updating Ingress: default/myapp-ingress
E0415 07:01:02.009954       1 utils.go:63] Requeuing default/myapp-ingress after 5s, err Error retrieving secret tls-secret for Ingress myapp-ingress: the server does not allow access to the requested resource (get secrets tls-secret)
``` 

I'm at a loss as to what to do here though, but at least it looks like it tried to get the ssl stuff. Does this have to do with k8s 1.6 and the roles?

**Comment by domino14** [comment]
This config fixes it, YMMV:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - configmaps
  - secrets
  - services
  - endpoints
  - ingresses
  - nodes
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  - "extensions"
  resources:
  - ingresses
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  - services
  verbs:
  - create
  - list
  - update
  - get
- apiGroups:
  - "extensions"
  resources:
  - ingresses/status
  - ingresses
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ingress-ns
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ingress-ns-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-ns
subjects:
  - kind: ServiceAccount
    name: ingress
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress
subjects:
  - kind: ServiceAccount
    name: ingress
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress
subjects:
  - kind: ServiceAccount
    name: ingress
    namespace: kube-system

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-rc
  labels:
    k8s-app: nginx-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: nginx-ingress-controller
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-controller
    spec:
      hostNetwork: true
      serviceAccountName: ingress
      containers:
      - image: nginxdemos/nginx-ingress:0.8.0
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps
        # args:
         # - -v=3
         #- -nginx-configmaps=default/nginx-config
```

**Comment by pleshakov** [comment]
@domino14 
`E0415 07:01:02.009954       1 utils.go:63] Requeuing default/myapp-ingress after 5s, err Error retrieving secret tls-secret for Ingress myapp-ingress: the server does not allow access to the requested resource (get secrets tls-secret)`, looks like the controller tries to get a secret, but it is not permitted. The controller must be able to get secrets, as well as configmaps, services, endpoints, ingresses and pods. This controller doesn't update or create resources.

**Comment by xrl** [comment]
I have a `nginx-ingress` namespace and I used a more minimal clusterrole to get things working:

```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "endpoints", "ingresses", "pods"]
  verbs: ["get", "list", "watch"]
---
# This role binding allows "system:serviceaccount:nginx-ingress:default" to read pods in the "default" namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx-ingress-service-account
subjects:
- kind: ServiceAccount
  name: default
  namespace: nginx-ingress
roleRef:
  kind: ClusterRole
  name: ingress-role
  apiGroup: rbac.authorization.k8s.io
```
