### ISSUE TITLE
"client closed connection while waiting for request" using websockets (EOF)

### ISSUE THREAD

**Issue by jeanluclariviere** [nginxinc/kubernetes-ingress#1434]
**Describe the bug**
Our application is hosting 2 rest endpoints behind a single service, example.com/api and example.com/ws. Having exposed our service using node ports, we can connect to both endpoints, /api using http and /ws using websockets.

We followed this article to enable websockets on our ingress:
https://github.com/nginxinc/kubernetes-ingress/tree/v1.10.0/examples/websocket

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: example
  annotations:
    nginx.org/websocket-services: "example-service"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: example-service
          servicePort: 8080
```

This is the resulting nginx conf:
```
location / {


                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;

                proxy_connect_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;

                proxy_pass http://redacted;


        }
```

Unfortunately, if we try to access the service using the ingress rule, we are hit with the following on the nginx-ingress. Our client sees an ` unexpected EOF`
```
2021/03/05 19:49:50 [info] 298#298: *31 client closed connection while waiting for request, client: 10.10.10.61, server: 0.0.0.0:80
```

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
nginx-ingress:1.5.3

* Version of Kubernetes
1.19.7

* Kubernetes platform (e.g. Mini-kube or GCP)
Bare-metal, kubeadm

* Using NGINX or NGINX Plus
Nginx
