### ISSUE TITLE
upgrade from 1.9.1, seeing issues with RUN CGO_ENABLED=0 GOFLAGS='-mod=vendor'

### ISSUE THREAD

**Issue by johnjbateman** [nginxinc/kubernetes-ingress#1460]
**Describe the bug**
Downloaded release 1.10, using NGINX Plus, getting an error in this step running the following:

```
#20 [builder 3/3] RUN CGO_ENABLED=0 GOFLAGS='-mod=vendor' 	go build -installsuffix cgo -ldflags "-w -X main.version=1.10.0 -X main.gitCommit=35772b7d" -o /nginx-ingress
#20 sha256:07122080f2877eeea8791d1435a7ca9737b8639ba5251afba9d2ef9e3f29a57f
#20 0.977 ../../vendor/k8s.io/client-go/discovery/discovery_client.go:30:2: cannot find package "." in:
#20 0.977 	/go/src/github.com/nginxinc/kubernetes-ingress/nginx-ingress/vendor/github.com/googleapis/gnostic/openapiv2
#20 ERROR: executor failed running [/bin/sh -c CGO_ENABLED=0 GOFLAGS='-mod=vendor' 	go build -installsuffix cgo -ldflags "-w -X main.version=${VERSION} -X main.gitCommit=${GIT_COMMIT}" -o /nginx-ingress]: exit code: 1
```

**To Reproduce**
1. Build image via Azure Dev Ops:

make clean
make DOCKERFILE=DockerfileForPlus PREFIX=myprivate.registry/nginx-plus-ingress TAG=1234

**Expected behavior**
On 1.9.1, this built and pushed my image to my private container registry

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
1.10
* Version of Kubernetes
v1.19.3

* Kubernetes platform (e.g. Mini-kube or GCP)
Azure Kubernetes Service
* Using NGINX or NGINX Plus
NGINX Plus

Tried building on ubuntu 18.04 and 16.04, same error

**Additional context**
Build [log](https://gist.github.com/johnjbateman/594ec98ef2b95a7c8ed6e3dbc9f353d2)

**Comment by lucacome** [comment]
Hi @johnjbateman 

This seems like an error that we had a long time ago and has been fixed.
Looking at the logs I see a commit `35772b7d` that is not in our repo, have you done some modifications to the source code? Are you using sure you're using https://github.com/nginxinc/kubernetes-ingress/tree/v1.10.0?

**Comment by johnjbateman** [comment]
@lucacome Hi, the only commits in my local repo are pipeline yamls for our automated creation of the image in our container registry.  And yes, that is the release that I used.  I will try again.

**Comment by johnjbateman** [comment]
I removed all files from my repo, then cloned this repo again, checked out release-1.10 branch, copied those files into my repo.  then i run the make commands above.

**Comment by johnjbateman** [comment]
Well then.  All this got me thinking, why am I putting any of this repo in my local Azure DevOps Git?  Changed my pipelines to clone and build without storing locally and it works!  Here is a sample if anyone comes across this same issue:

```yaml
parameters:
- name: branchName
  type: string
- name: imageName
  type: string
- name: dockerFileName
  type: string
- name: azureSubscription
  type: string
- name: keyVaultName
  type: string
- name: secretsFilter
  type: string

jobs:
- job: Job_1
  displayName: 'Make: Build Image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      git clone -b ${{ parameters.branchName }} https://github.com/nginxinc/kubernetes-ingress.git $(Build.SourcesDirectory)/nginx
    displayName: 'Git: Clone NGINX Ingress branch ${{ parameters.branchName }}'
   - task: Docker@2
     displayName: 'Login to ACR'
     inputs:
       containerRegistry: 'myacr.azurecr.io'
       command: login
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      keyVaultName: ${{ parameters.keyVaultName }}
      secretsFilter: '${{ parameters.secretsFilter }}'
    displayName: 'Download secrets from KeyVault'
  - script: |
      cd $(Build.SourcesDirectory)/nginx
      echo $(nginx-repo-crt) > nginx-repo.crt
      echo $(nginx-repo-key) > nginx-repo.key

      make clean
      make DOCKERFILE=${{ parameters.dockerFileName }} PREFIX=myacr.azurecr.io/${{ parameters.imageName }} TAG=$(Build.BuildId)

      rm nginx-repo.crt
      rm nginx-repo.key
    displayName: 'Make: Build ${{ parameters.imageName }}'
```
