### ISSUE TITLE
Specify custom ciphers in Helm

### ISSUE THREAD

**Issue by gurdeepsira** [nginxinc/kubernetes-ingress#1485]
Hi,
I am using NGINX ingress with Helm. I want to specify custom ciphers but I can't quite understand how to. Is there an example anywhere?

Thanks

**Comment by pleshakov** [comment]
Hi @gurdeepsira 

To configure ciphers, it is necessary to use the config map -- see  https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssl-tls

For [helm](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/), it will look like this in the values file:
```
controller:
  config:
    entries:
      ssl-ciphers: "HIGH:!aNULL:!MD5"
 ```

**Comment by johnoloughlin** [comment]
> Hi @gurdeepsira
> 
> To configure ciphers, it is necessary to use the config map -- see https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssl-tls
> 
> For [helm](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/), it will look like this in the values file:
> 
> ```
> controller:
>   config:
>     entries:
>       ssl-ciphers: "HIGH:!aNULL:!MD5"
> ```
This is what worked for me. 
```
controller:
  config:
      ssl-ciphers: "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
      ssl-protocols: "TLSv1.2"
```
