### ISSUE TITLE
Can't get proxy-body-size to apply

### ISSUE THREAD

**Issue by darye** [nginxinc/kubernetes-ingress#150]
So I've been getting the 413 request entity too large. So in the past on previous k8s clusters, I've just set the proxy-body-size setting on the nginx ingress as an annotation: `ingress.kubernetes.io/proxy-body-size: 20m`. However for some reason on a new cluster I've setup it isn't applying at all. I've also set `proxy-body-size: 20m` in the config map for the nginx ingress controller.

My nginx controller is in the default namespace, while my ingress is in a ci namespace. I thought this could be an issue so I created a new nginx controller/backend/ingress using helm in the ci namespace, and same issue. I tried restarting pods, etc.

The nginx controller logs isn't showing any 413 errors. Max upload is set in rails way above 1m, so I know it's not rails causing the issue, plus it works locally when testing with just rails.

This is in AWS btw.

```
    apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/proxy-body-size: 20m
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/force-ssl-redirect: "true"
    name: ci-nginx-service
    namespace: ci
  spec:
    rules:
      - host: ci.host-name.com
        http:
          paths:
            - backend:
                serviceName: ci-web-service
                servicePort: 80
              path: /
```
Am I missing something? Read all the documentation I can find on the topic, and everyone says just thrown the annotation in there. Not sure if there was some update applied that is causing a new issue.

Thanks
