### ISSUE TITLE
Ingress Custom annotation allowed-ips 

### ISSUE THREAD

**Issue by quadrinho** [nginxinc/kubernetes-ingress#1535]
**Describe the bug**
Ingress Custom annotations doesn't work

**To Reproduce**
1. Deploy nginxinc helm chart version 0.9.1 using this values.yaml:

```
---
controller: 
  kind: "deployment"
  nginxplus: false
  appprotect: 
    enable: false
  image: 
    repository: "nginx/nginx-ingress"
    tag: "1.11.1"
    pullPolicy: "IfNotPresent"
  serviceAccount: 
    imagePullSecretName: ""
  defaultTLS: 
    secret: "sit/aip-acn"
  ingressClass: "nginx"
  useIngressClassOnly: false
  enableCustomResources: true
  enableSnippets: true
  globalConfiguration: 
    create: true
  watchNamespace: "sit"
  service: 
    create: true
    type: "LoadBalancer"
    externalTrafficPolicy: Local
    httpPort: 
      enable: true
      port: "80"
    httpsPort: 
      enable: true
      port: "443"
imageDefault: true
prometheus: 
  create: false
  port: "9113"
```

After the deploy i create this configmap (following this guide https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/custom-annotations/):

```
apiVersion: v1
data:
  ingress-template: |-
    {{range $ip := split (index $.Ingress.Annotations "custom.nginx.org/allowed-ips") ","}}
        allow {{trim $ip}};
    {{end}}
    deny all;
kind: ConfigMap
  name: nginx-config
  namespace: sit
```

Then i create this ingress resource:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    custom.nginx.org/allowed-ips: 80.104.107.109,80.104.106.109
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: myservice-ssl
  namespace: sit
spec:
  rules:
  - host: myservice.test.com
    http:
      paths:
      - backend:
          serviceName: myservice-ssl
          servicePort: 9543
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - myservice.test.com
    secretName: mycertificate
```

But it seems doens't work; in the path (inside the pod) /etc/nginx/conf.d/, i found the conf file of my ingress but in this conf file there aren't the public ip that i write in the annotation and my ingress is reachble by anyone.

**Expected behavior**
I expected that my service is reachble by only that ip and the other source ip recieve an error (403 Forbidden maybe).

Can anyone help me?

**Your environment**
* Version of the Ingress Controller - release version or a specific commit --> helm chart version 0.9.1
* Version of Kubernetes  --> 1.18
* Kubernetes platform (e.g. Mini-kube or GCP)  --> Azure
* Using NGINX or NGINX Plus --> NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.
