### ISSUE TITLE
Setup kuberenetes dashboard

### ISSUE THREAD

**Issue by weihan1394** [nginxinc/kubernetes-ingress#1558]
I am trying to set up Kubernetes with bare machine and I have deployed my Nginx in the default namespace and I am trying to create a virtual server to route the dashboard. However, when I try to access the URL, it directed me to error 404 and when I view the logs from the pod it seems to be having a broken header. I came across [https://github.com/kubernetes/ingress-nginx/issues/3996](https://github.com/kubernetes/ingress-nginx/issues/3996) and they were giving suggestion to add the proxy protocol and if I were to add the below snippet to my config map, the other routes will fail.

```
proxy-protocol: "True"
real-ip-header: "proxy_protocol"
set-real-ip-from: "0.0.0.0/0"
```

```
2021/04/27 07:43:28 [error] 145#145: *155 broken header: "▬♥☺☻☺☺�♥♥�#�↓�|��-�B�d�s�HZ��]!��↨��☻ O|����%���o�/k��R       ��¶�u�♂����VI"��‼☺‼☻‼♥�+�/�,�0̨̩�‼�¶��/" while reading PROXY protocol, client: 192.168.254.9, server: 0.0.0.0:443  
```

nginx-ingress-configmap
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-cm
  namespace: default
data:
  http2: "true"
  ssl-protocols: TLSv1.2 TLSv1.3
  ssl-prefer-server-ciphers: "true"
  ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  set-real-ip-from: 0.0.0.0/0
  real-ip-header: X-Forwarded-For
  server-snippets: |
    proxy_hide_header Strict-Transport-Security;
    add_header Strict-Transport-Security "max-age=31536000" always;

```

Any hints what I have done wrongly? Thanks in advance.

**Comment by pleshakov** [comment]
Hi @weihan1394 

The proxy protocol is only needed if you front Ingress Controller pods with a load balancer like ELB, which uses proxy protocol to pass the client IP to NGINX:
clients -> ELB -> NGINX IC -> backends

Is that the case?

**Comment by serhiiromaniuk** [comment]
Hello there! So, what's the true way to reach Clients IPs @pleshakov  ? https://github.com/nginxinc/kubernetes-ingress/issues/1561

**Comment by weihan1394** [comment]
Hi @pleshakov, I am currently using this way: clients -> NGINX IC -> backends. Apparently, this configuration works for all my application but currently I am trying to setup the kubernetes [dashboard ](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) with their default [yaml](https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml)

**Comment by pleshakov** [comment]
@weihan1394 
Could you remove all the proxy protocol related configuration (`proxy-protocol`,  `real-ip-header` and  `set-real-ip-from`)?
 Could you share the Ingress or VirtualServer resource you used for the dashboard? 
 Could you also try again to access the dashboard and share the output and the corresponding log lines?
 Could you also share how you try to access the dashboard? For example, a curl command

**Comment by weihan1394** [comment]
Hi @pleshakov Thanks for your kind help in advance.  I have removed those proxy protocols. I am trying to access the dashboard from google chrome.

virtual server for dashboard.yaml
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: kubernetes-dashboard-vs
  namespace: kubernetes-dashboard
spec:
  host: k8.moonshot.com
  tls:
    secret: nginx-tls-secret
    redirect:
      enable: true
      code: 301
  upstreams:
  - name: kubernetes-dashboard
    service: kubernetes-dashboard
    port: 443
  routes:
  - path: /
    action:
      pass: kubernetes-dashboard
```

dashboard service yaml
```
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
```

Logs:
```
2021/04/28 00:05:05 [error] 162#162: *225 readv() failed (104: Connection reset by peer) while reading upstream, client: 192.168.254.9, server: k8.moonshot.com, request: "GET / HTTP/2.0", upstream: "http://192.168.253.130:8443/", host: "k8.moonshot.com"       
192.168.254.9 - - [28/Apr/2021:00:05:05 +0000] "GET / HTTP/2.0" 400 48 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-"
```

**Comment by pleshakov** [comment]
the `400` response code is because NGINX sent an HTTP request to the HTTPs port on the dashboard. To fix that, it is necessary to enable HTTPs between NGINX and the dashboard.

Could you update the VS to do that?
```
  - name: kubernetes-dashboard
    service: kubernetes-dashboard
    port: 443
    tls:
      enable: true
 ```

**Comment by weihan1394** [comment]
@pleshakov oh wow! kudos, it works now. May I check if I understand my setup of the virtual server correctly?

I have deployed my NGINX in the default namespace, but I have also created 2 applications in 2 different namespaces. Let call it dev and prod. Am I right to say that I can just simply create the virtual server on the respective namespace? I will just need to create all the resources required in their own namespace. 

dev:
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: hellok8s-app-vs-2
  namespace: dev
spec:
  host: helloworld2.moonshot.com
  tls:
    secret: nginx-tls-secret
    redirect:
      enable: true
      code: 301
  upstreams:
  - name: hellok8s-2
    service: hellok8s-service-2
    port: 8080
  routes:
  - path: /
    action:
      pass: hellok8s-2
```


prod:
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: hellok8s-app-vs-2
  namespace: prod
spec:
  host: helloworld2.moonshot.com
  tls:
    secret: nginx-tls-secret
    redirect:
      enable: true
      code: 301
  upstreams:
  - name: hellok8s-2
    service: hellok8s-service-2
    port: 8080
  routes:
  - path: /
    action:
      pass: hellok8s-2
```
