### ISSUE TITLE
Cannot retrieve client's Public Ip

### ISSUE THREAD

**Issue by serhiiromaniuk** [nginxinc/kubernetes-ingress#1561]
**Describe the bug**
The Latest Nginx Helm chart returns EKS (latest too) nodes private Ip, rather then from browser client.

**To Reproduce**
1. Deploy latest EKS 19.6
2. Deploy the latest Nginx Helm Chart 0.9.1 with 0 customizations
3. Deploy Sample app with `kubernetes.io/ingress.class: nginx`
4. See the bug

**Expected behavior**
Expect public client's IP.

**Additional context**
Verified on a lot of versions of Helm charts, tried a lot of versions of app (1.10, 1.6.1, 1.5.0) and chart respectively.

When I add to values
```
    entries:
      set-real-ip-from: "0.0.0.0/0"
      proxy-protocol: "True"
```
![image](https://user-images.githubusercontent.com/45049898/116315210-dee06100-a7b8-11eb-8db8-fbc58f532b15.png)

**Comment by pleshakov** [comment]
Hi @serhiiromaniuk 

Did you enable the proxy protocol on the ELB/NLB?  https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/service/annotations/#proxy-protocol-v2  and https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/service/nlb_ip_mode/#protocols

Once Proxy protocol is enabled on the ELB/NLB, the errors in NGINX logs related to Proxy protocol should go away and you will be able to see the clients real ip address.

**Comment by serhiiromaniuk** [comment]
@pleshakov Ok, have been added
```
service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```
to nginx svc. Also on startup nginx brings nor NLB, ALB, but only Classic.
Also, when turn this annotations on, all of the cluster endpoints become unreachable.

**Comment by serhiiromaniuk** [comment]
Not it web pages returns `ERR_SSL_PROTOCOL_ERROR`.

**Comment by serhiiromaniuk** [comment]
Cert-manager configured correctly. 

` aws elb describe-load-balancer-policies --load-balancer-name < NAME >`
```json
{
    "PolicyDescriptions": [
        {
            "PolicyName": "k8s-proxyprotocol-enabled",
            "PolicyTypeName": "ProxyProtocolPolicyType",
            "PolicyAttributeDescriptions": [
                {
                    "AttributeName": "ProxyProtocol",
                    "AttributeValue": "true"
                }
            ]
        }
    ]
}

```

**Comment by serhiiromaniuk** [comment]
Nginx Controller
```
  ports:
  - name: http
    nodePort: 30814
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32520
    port: 443
    protocol: TCP
    targetPort: 443
```

**Comment by serhiiromaniuk** [comment]
OK, fixed.
### < Nginx's SVC annotations >
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

### < values.yaml >
```
controller:
    entries:
      proxy-protocol: "True"
      real-ip-header: "proxy_protocol"
      set-real-ip-from:  "< VPC CIDR block >"
```
