### ISSUE TITLE
NginxIngressController - nodeSelector and tolerations

### ISSUE THREAD

**Issue by alrf** [nginxinc/kubernetes-ingress#1562]
**Is your feature request related to a problem? Please describe.**
There is no way to define `nodeSelector` and `tolerations` for `NginxIngressController` when the nginx-ingress-controller deployed by OLM.

**Describe the solution you'd like**
I deploy the nginx-ingress-controller in Openshift using OLM:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nginx-ingress-operator
  namespace: ingress-nginx
spec:
  targetNamespaces:
  - ingress-nginx
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nginx-ingress-operator
  namespace: ingress-nginx
spec:
  channel: alpha
  name: nginx-ingress-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
```

In `NginxIngressController` yaml-manifest it would be great to have `nodeSelector` and `tolerations` fields like:
```
apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
......
spec:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - key: "infra"
        operator: "Exists"
        effect: "NoExecute"
.....
```

At the moment it's not possible to put nginx-ingress-controller pods to specific nodes.
