### ISSUE TITLE
http/https request failed randomly from client side

### ISSUE THREAD

**Issue by pkchuyen** [nginxinc/kubernetes-ingress#1579]
http/https request failed randomly when using helm chart version 0.9.1
and I am unable to find the cause.

I deployed `nginx-ingress-controller` following this step and values.yaml file.

values.yaml
```
controller:
  service:
    annotations:
      cloud.google.com/load-balancer-type: "Internal"

    loadBalancerIP: "10.116.100.46"
    loadBalancerSourceRanges:
      - 0.0.0.0/0

  publishService:
    enabled: true
```

installing
```
helm upgrade --install nginx-ingress-internal nginx-stable/nginx-ingress --version 0.9.1 --values ./values.yaml --namespace nginx
```

Error facing when I access from my laptop:
```
curl -XGET -I https://prometheus.example.io/graph -v
*   Trying 10.116.100.46...
* TCP_NODELAY set
* Connection failed
* connect to 10.116.100.46 port 443 failed: Operation timed out
* Failed to connect to prometheus.example.io port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to prometheus.example.io port 443: Operation timed out
```
after a few hits, the request went thought and failed again. I cannot work out why it happens randomly.
the rate of successful request is around 20%

However, It works fine (100%) when I tested to curl from a pod inside the GKE cluster
```
jenkins-76b7df86b-vsfkg:/$ curl -XGET  https://prometheus.example.io/graph -I -v
*   Trying 10.116.100.46...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55de79d0efb0)
* Connected to prometheus.example.io (10.116.100.46) port 443 (#0)
...
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: nginx/1.19.1
Server: nginx/1.19.1

```

What may be the issue and how to fix it?
Since the request succeeded/failed randomly, I don't think network or firewall is the issue.

GKE version: 1.17.17-gke
