### ISSUE TITLE
no host in upstream - unable to access TCP exposed ports from pods

### ISSUE THREAD

**Issue by evenme** [nginxinc/kubernetes-ingress#1582]
**Describe the bug**
We have redis, postgresql and memcached running into pods on N namespaces as <service-namespace>, each configured also with a service to expose their ports and nginx config to reach those. However, after upgrading to k8s 1.16 (EKS) and nginx-ingress >=1.6 (currently at 1.7.2, before was 1.5.X), we're now unable to reach those services. As a POC (on k8s 1.15), I followed the documentation for tcp/udp example (installed using helm) with a simple rails server exposing 3000 port and was able to reproduce the problem, which shows in nginx logs as:

```
2021/05/07 20:54:19 [error] 32#32: *19 no host in upstream "", client: 127.0.0.1, server: 0.0.0.0:3000, bytes from/to client:0/0, bytes from/to upstream:0/0
127.0.0.1 [07/May/2021:20:54:19 +0000] TCP 500 0 0 0.032 "-"
- -- 127.0.0.1 -nginx-nginx-ingress-5db7bf9b9d-6dvh9 -127.0.0.1 -- -- -[07/May/2021:20:54:19 +0000] TCP 500 0 0 0.032
89.X.X.X - - [07/May/2021:20:54:51 +0000] "GET / HTTP/1.1" 404 153 "-" "-" "-"
```

And logs from the postgresql pod as example:

```72.X.X.X [07/May/2021:20:59:15 +0000] TCP 500 0 0 0.014 "-"
- -- 72.39.69.92 -nginx-nginx-ingress-8dbd4967-sg6cn -10.0.3.246 -- -- -[07/May/2021:20:59:15 +0000] TCP 500 0 0 0.014
2021/05/07 20:59:15 [error] 6797#6797: *35655 no host in upstream "", client: 72.X.X.X, server: 0.0.0.0:5432, bytes from/to client:0/0, bytes from/to upstream:0/0
```

**To Reproduce**
1. Deploy application with exposed TCP port (non-http/https)
2. Deploy nginx-ingress as deployment with TCP/UDP using snippets
3. curl application:port url.

**Expected behavior**
Application being accessible.

****
* Version of the Ingress Controller - 1.7.2 (same issue also on 1.6.0)
* Version of Kubernetes - both 1.15 and 1.16
* Kubernetes platform - AWS/EKS
* Using NGINX or NGINX Plus - NGINX

**Additional context**

POC rails application:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: app
          image: brightbox/rails-hello-world
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
kind: Service
apiVersion: v1
metadata:
  name: hello-example
  namespace: example
spec:
  selector:
    app: hello-world
  ports:
    - name: tcp-hello
      protocol: TCP
      port: 3000
      targetPort: tcp-hello
```

nginx config (same as used for postgres/redis/memcached, just limited to this one application):
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  server-names-hash-bucket-size: "128"
  proxy-buffer-size: "128K"
  proxy-buffers: "4 256k"
  stream-snippets: |
    log_format basic '$ssl_preread_server_name -- $remote_addr -$hostname -$server_addr -$proxy_protocol_addr -$upstream_addr -[$time_local] ' '$protocol $status $bytes_sent $bytes_received ' '$session_time';
    access_log /var/log/nginx/access.log basic;
    map $ssl_preread_server_name $hello_name {
      hello.example.tcp.DOMAIN 127.0.0.1:1005;
    }

    server {
      listen 3000;
      ssl_preread on;
      proxy_pass $hello_name;
    }

    upstream tcp-hello-example {
      server hello-example.example.svc.cluster.local:3000;
    }

    server {
      listen 1005 ssl;
      allow 127.0.0.1;
      deny all;
      access_log off;
      ssl_certificate /etc/nginx/secrets/default;
      ssl_certificate_key /etc/nginx/secrets/default;
      ssl_protocols TLSv1.2;
      proxy_pass tcp-hello-example;
    }
```

values.yaml:
```
controller:
  kind: deployment
  nginxplus: false
  hostNetwork: false
  nginxDebug: false
  image:
    repository: nginx/nginx-ingress
    tag: "1.7.2"
    pullPolicy: IfNotPresent
  config:
    name: nginx-config
    entries: {}
  defaultTLS:
    cert: TLSCERT
    key: TLSKEY
  wildcardTLS:
    cert: ""
    key: ""
  nodeSelector: {}
  terminationGracePeriodSeconds: 30
  tolerations: []
  affinity: {}
  replicaCount: 2
  ingressClass: nginx
  useIngressClassOnly: false
  watchNamespace: ""
  enableCustomResources: false
  healthStatus: true
  nginxStatus:
    enable: true
    port: 8080
    allowCidrs: "127.0.0.1,VPCCIDR"
  service:
    create: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    loadBalancerIP: ""
    externalIPs: []
    loadBalancerSourceRanges: []
    name: nginx-ingress
    httpPort:
      enable: true
      port: 80
      nodePort: ""
      targetPort: 80
    httpsPort:
      enable: false
      port: 443
      nodePort: ""
      targetPort: 443
    customPorts:
      - port: 3000
        protocol: TCP
        name: hello
  serviceAccount:
    name: nginx
    imagePullSecrets: []
  reportIngressStatus:
    enable: true
    enableLeaderElection: true
  pod:
    annotations: {
      prometheus.io/scrape: 'true',
      prometheus.io/port:   '9000'
    }
rbac:
  create: true
prometheus:
  create: true
  port: 9000
```
