### ISSUE TITLE
Nginx Ingress reverse to TLS endpoints.

### ISSUE THREAD

**Issue by valentin2105** [nginxinc/kubernetes-ingress#159]
Hi,

I'm trying to make Nginx Ingress Controller expose in HTTPS a service in my Kubernetes cluster which is already in HTTPS too. 

For now, I got : 

```
400 Bad Request

The plain HTTP request was sent to HTTPS port
```

There is a way to say in the Ingress definition if the endpoint is in HTTPS or HTTP. ? 

Thanks.

**Comment by valentin2105** [comment]
Sorry for this issue,

It work with v0.9.0 and this doc https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services

**Comment by kabudu** [comment]
I know this is an old issue, but I'm having the same problem using version ```nginx-ingress-0.12.2```. My Ingress configuration is:

```
# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-web-ingress
  annotations:
    nginx.org/ssl-services: "example-web-service"
spec:
  tls:
    - hosts:
      - www.example.com
      secretName: tls-wildcard-example-com
  rules:
    - host: www.example.com
      http:
        paths:
        - backend:
            serviceName: example-web-service
            servicePort: 443
          path: /
```

Navigating to: www.example.com, results in:

````
400 Bad Request

The plain HTTP request was sent to HTTPS port
````

Any ideas?
