### ISSUE TITLE
Need a very simple localhost example that works without any rewrites

### ISSUE THREAD

**Issue by ankur6ue** [nginxinc/kubernetes-ingress#1590]
I modified the cafe-ingress example as follows:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    nginx.org/rewrite-target: /
spec:
  # ingressClassName: nginx # use only with k8s version >= 1.18.0
  rules:
  - http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```
nginx-ingress service is running as expected:
nginx-ingress   nginx-ingress   NodePort    10.111.11.156    <none>        80:31251/TCP,443:31535/TCP

When I do 
curl 127.0.0.1:31251/coffee

I get a 404. 
I expect that something as simple as this should just work.. 
Please provide either a solution to this, or a very simple example that just works on localhost with a simple curl, preferably without rewrites.
