### ISSUE TITLE
Restrict access to /admin location

### ISSUE THREAD

**Issue by Sarga** [nginxinc/kubernetes-ingress#161]
Hello.

I need to restrict access by ip to /admin location.
Is there a way to include file with allow/deny directives only in /admin location ?
Or add allow/deny directives in admin location only?
allow 1.1.1.1;
deny all;

```
apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: example-ingress
  spec:   
    rules:
    - host: dev.example.com
      http:   
        paths:    
        - backend:
            serviceName: test-service
            servicePort: 80
          path: / 
        - backend:
            serviceName: test-service
            servicePort: 80
          path: /admin
    tls:
    - hosts:
      - dev.example.com
      secretName: https-example
```

Thank you.
