### ISSUE TITLE
Fanout not working

### ISSUE THREAD

**Issue by d3athkai** [nginxinc/kubernetes-ingress#1645]
**Describe the bug**
I tried configuring a simple fanout with the Nginx controller setup using https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/
A HAProxy is setup outside of the cluster to port 80 and 443 of all worker nodes.
However, the fanout returns 404 Not found.

**To Reproduce**
1. I have deployed a nginx deployment along with its service:
```
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy-main
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-main
  template:
    metadata:
      labels:
        run: nginx-main
    spec:
      containers:
      - image: nginx
        name: nginx

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-main
```

I have also deploy the following ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - pathType: Prefix
        path: /test
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
```

2. View logs on the ingress:
```
Name:             nginx-ingress
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host           Path  Backends
  ----           ----  --------
 foo.example.com
                 /test   nginx-svc:80 (10.40.0.1:80)
Annotations:     kubernetes.io/ingress.class: nginx
                 nginx.ingress.kubernetes.io/rewrite-target: /
Events:
  Type    Reason          Age                From                      Message
  ----    ------          ----               ----                      -------
  Normal  AddedOrUpdated  27s (x2 over 54s)  nginx-ingress-controller  Configuration for default/nginx-ingress was added or updated
  Normal  AddedOrUpdated  27s (x2 over 54s)  nginx-ingress-controller  Configuration for default/nginx-ingress was added or updated
```

3. See error
Access http://foo.example.com/test or http://foo.example.com/test/ gives 404 Not Found.

**Expected behavior**
Requests are not routing from Nginx ingress controller to applications/services.

**Your environment**
* Version of the Ingress Controller - v1.11.3
* Version of Kubernetes: v1.20.7
* Kubernetes platform: kubeadm bootstrap Ubuntu 20.04.2 VMs
* Using NGINX

**Additional context**
This following ingress configuration works:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
```
Access http://foo.example.com works.

**Comment by pleshakov** [comment]
Hi @d3athkai 

We support a different annotation for URI rewriting. Please see https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/rewrites#example 

I believe the following Ingress should work:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/rewrites: "serviceName=nginx-svc rewrite=/"
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - pathType: Prefix
        path: /test/
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
```
