### ISSUE TITLE
Zero downtime upgrade nginx-ingress-controller

### ISSUE THREAD

**Issue by Sarga** [nginxinc/kubernetes-ingress#167]
Hello @pleshakov 

I'm using nginx-ingress-controller and hope to get zero downtime deployments. This means that nginx should also be upgraded without any downtime.

I have 3 baremetal servers and one daemon set with nginx-ingress-controller. 
The scheme is:
Cloudflare -> 3 pods with nginx-controller
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: nginx-ingress-controller
  name: nginx-ingress-controller
  namespace: default
spec:
  selector:
    matchLabels:
      name: nginx-ingress-controller
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nginx-ingress-controller
    spec:
      containers:
      - args:
        - -nginx-configmaps=default/nginx-config
        image: myregistry.example.com/nginx-ingress:0.9.0
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/custom-snippets/
          name: config-volume
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: access-list
        name: config-volume
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

When I change the template of daemon set or change the version of docker image, my pods with nginx  start restarting one by one, so I lost some clients queries for a few seconds.

I know how to upgrade nginx binary on baremetal without downtime, but how to do that in kubernetes?
Can you give some advice?
