### ISSUE TITLE
Opening port25 in IKS without GlobalConfiguration and TransportServer to receive emails - Questions Clarification

### ISSUE THREAD

**Issue by prempp** [nginxinc/kubernetes-ingress#1719]
Hello
I am trying to set up email service in order to relay email in iks . Following approach reference earlier in email port forwarding (25) for GlobalConfiguration yaml , after creating deployment and service trying to create have this GlobalConfiguration configured in my cluster . It seems it is throwing an error 

no matches for kind "GlobalConfiguration" in version "k8s.nginx.org/v1alpha1"

below is my yml config
```
apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration
metadata:
  name: emailsever-test
  namespace: emailsever
spec:
  listeners:
  - name: postfix-tcp
    port: 25
    protocol: TCP
```

same is happening when i am applying TransportServer yaml 

Error below
no matches for kind "TransportServer" in version "k8s.nginx.org/v1alpha1"

Basic stuff i am trying to open port 25 , so question is without these 2 options as explained above for GlobalConfiguration and 
TransportServer would i be able to open port 25 or not? Need help here

**Comment by pleshakov** [comment]
Hi @prempp 

> no matches for kind "GlobalConfiguration" in version "k8s.nginx.org/v1alpha1"
> no matches for kind "TransportServer" in version "k8s.nginx.org/v1alpha1"

Make sure that the the GlobalConfiguration and TransportServer CRDs are created in the cluster. Please see https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/#create-custom-resources 

> Basic stuff i am trying to open port 25 , so question is without these 2 options as explained above for GlobalConfiguration and
TransportServer would i be able to open port 25 or not? Need help here

Yes, that should work.  Additionally, if you use a Service to expose IC pods, you will also need to add port 25 on that service. For example:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  -  port: 443
    targetPort: 443
    protocol: TCP
    name: https
 -  port: 25
    targetPort: 25
    protocol: TCP 
  selector:
    app: nginx-ingress
```
