### ISSUE TITLE
backend-protocol: HTTPS not working

### ISSUE THREAD

**Issue by xiaoyier** [nginxinc/kubernetes-ingress#1724]
**Describe the bug**
ingress annotation  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" not working

**To Reproduce**
1. ingress yaml  
```
apiVersion: networking.k8s.io/v1beta1 # for versions 1.14-1.18 use extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx-kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # 开启use-regex，启用path的正则匹配
    # nginx.ingress.kubernetes.io/use-regex: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/secure-backends: "true" #好像是版本0.20.0发布后被删除，请使用下面这行
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    #nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    #nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    #nginx.ingress.kubernetes.io/configuration-snippet: |-
    #  proxy_ssl_server_name on;
    #  proxy_ssl_name $host;
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    - dashboard.inconnecting-k8s.com
    secretName: kubernetes-dashboard-certs
  rules:
  - host: dashboard.inconnecting-k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
```

2. View logs on '....'   
```
47.242.84.133 - - [08/Jul/2021:11:06:51 +0000] "GET / HTTP/1.1" 400 59 "-" "curl/7.64.1" "-"
```
3. See error  
```
*   Trying 54.169.0.235...
* TCP_NODELAY set
* Connected to dashboard.inconnecting-k8s.com (54.169.0.235) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=SG; ST=Singapore; L=Singapore; O=Inconnecting; OU=Inconnecting; CN=*.inconnecting-k8s.com
*  start date: Jul  2 08:24:48 2021 GMT
*  expire date: Aug  1 08:24:48 2021 GMT
*  issuer: C=SG; ST=Singapore; L=Singapore; O=Inconnecting; OU=Inconnecting; CN=*.inconnecting-k8s.com
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: dashboard.inconnecting-k8s.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Server: nginx/1.21.0
< Date: Thu, 08 Jul 2021 11:06:51 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
<
Client sent an HTTP request to an HTTPS server.
* Connection #0 to host dashboard.inconnecting-k8s.com left intact
* Closing connection 0
```

**Expected behavior**

**Your environment**
* Version of the Ingress Controller：v1.12.0
* Version of Kubernetes: 1.18.9
* Kubernetes platform (e.g. Mini-kube or GCP): kubeadm
* Using NGINX or NGINX Plus: NGINX

**Additional context**
nginx config in nginx-ingress pod, proxy_pass http, not https
```
	location / {
		set $service "kubernetes-dashboard";


		proxy_http_version 1.1;


		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;

		proxy_pass http://kubernetes-dashboard-ingress-nginx-kubernetes-dashboard-dashboard.inconnecting-k8s.com-kubernetes-dashboard-443;


	}
```
