### ISSUE TITLE
Individual annotations/protocols for service ports

### ISSUE THREAD

**Issue by mstimvol** [nginxinc/kubernetes-ingress#1730]
**Is your feature request related to a problem? Please describe.**

I can use `controller.service.annotations` to specifiy the protocol of the load balancer, e.g.:

```yaml
controll
  service:
    annotations:
      load-balancer.hetzner.cloud/protocol: http
```

This creates a load balancer with two ports (80 and 443). Unfortunately both ports are marked with http, but the https port should be using the https protocol (annotation should be `load-balancer.hetzner.cloud/protocol: https`).  But the annotations-field applies to both service ports.

**Describe the solution you'd like**
There should be an option to specify port-specific annotations, e.g:

```yaml
controll
  service:
    httpPort:
      annotations:
        load-balancer.hetzner.cloud/protocol: http
    httpsPort:
      annotations:
        load-balancer.hetzner.cloud/protocol: https
```

So both ports are getting the correct protocol.
