### ISSUE TITLE
Activate gzip support

### ISSUE THREAD

**Issue by Uter1007** [nginxinc/kubernetes-ingress#179]
How can I activate gzip support. (currently I am editing it manually) but it is possible to use configmaps for this or is it possible to add gzip support via ingress files ? 

cheers

**Comment by pleshakov** [comment]
@Uter1007 There are snippets annotations and a ConfigMap keys that you can use to insert the gzip-related directives into generated NGINX config. See https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization and an example https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/customization/cafe-ingress-with-annotations.yaml

**Comment by Uter1007** [comment]
thx ;) I will try out

**Comment by stickperson** [comment]
@Uter1007 have you figured this out? I don't see any mention of compression in the links above.

**Comment by pleshakov** [comment]
@stickperson 
it is possible to configure that using *-snippets annotations and configmap keys, which allow you to use native NGINX configuration. For example:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.org/server-snippets: "gzip on;"
...
```
See http://nginx.org/en/docs/http/ngx_http_gzip_module.html to learn more about various gzip directives.
