### ISSUE TITLE
NGINX Controller crashes when the host field empty in an Ingress rule

### ISSUE THREAD

**Issue by pleshakov** [nginxinc/kubernetes-ingress#18]
For such Ingress resource...
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-no-host
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```
NGINX fails to reload because with ```nginx: [emerg] invalid number of arguments in \"server_name\" directive in /etc/nginx/conf.d/default-ingress-no-host.conf:12\n"```
