### ISSUE TITLE
Add response headers in nginx-ingress but conditionally

### ISSUE THREAD

**Issue by dhatri308** [nginxinc/kubernetes-ingress#1823]
I need to add few response headers in nginx-ingress but conditionally. I am trying to use a pod environment variable in nginx ConfigMap yaml. I want to use this env variable so I can enable/disable header just by changing this variable. But I am not sure if this is possible. Here's what I tried so far.

In nginx DaemonSet I have

```
 env:
       - name: HEADER_ENABLED
         value: "true"
       - name: HEADER_VALUE
         value: "Header Value" 
```

In nginx configMap yaml I have

```
  http-snippets: |-
    {{- if $(HEADER_ENABLED) }}
    add_header some-header "$(HEADER_VALUE)" always ;
    {{- end }}
```
But looks like this is not working. I know I can declare value in Values.yaml but I need to control using pod environment variables but not sure if its possible. The header I am trying to add is Content Security Policy. It could potentially break things so I want to control enabling/disabling this header. Any suggestions or ideas would be greatly appreciated. Thank you!
