### ISSUE TITLE
Path-based routing issue

### ISSUE THREAD

**Issue by rparke** [nginxinc/kubernetes-ingress#1852]
Description: I am trying to deploy an ingress object in Kubernetes using a helm chart. Kubernetes creates the ingress object  with the following spec with warning messages from the ingress controller:

```
spec:
  ingressClassName: nginx
  rules:
  - host: <hostname>.<work_address>.co.uk
    http:
      paths:
      - backend:
          service:
            name: thanostestone-receive
            port:
              name: remote-write
        path: /api/v1/receive
        pathType: ImplementationSpecific
  - host: <hostname>.<work_address>.co.uk
    http:
      paths:
      - backend:
          service:
            name: thanostestone-receive
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
```

When inspecting the ingress, this creates two path based routing rules with the same host and different paths. The nginx controller returns the following error message: `spec.rules[1].host: Duplicate value: "<hostname>.<work>.ac.uk"` The ingress fails to route traffic to the correct application (running inside a pod) and returns a 404 error.

1. Deploy the following helm chart https://github.com/bitnami/charts/tree/master/bitnami/thanos with the following config.yaml:

```
existingServiceAccount: "default"

image:
  registry: docker.io
  repository: bitnami/thanos
  tag: 0.22.0-scratch-r1
  pullPolicy: IfNotPresent



objstoreConfig: <dictionary containing object storage configuration>

query:
  enabled: true
  ingress:
    enabled: true
    hostname: <hostname>.<work>.co.uk

storegateway:
  enabled: true

receive:
  enabled: true
  tsdbRetention: 1d


  ingress:
    enabled: true
    hostname: <hostname>.<work>.co.uk
```

2. Inspect the ingress with `kubectl describe ingress <ingressname>`

Using this configuration I would expect an ingress object to be created with path-based routing rules, sharing a hostname, that can forward traffic to two different applications.

My environment
nginxinc version: 1.10.0
k8 version: 1.20.4
kubernetes platform: minikube
using nginx

Please let me know if you need more information
