### ISSUE TITLE
Health status

### ISSUE THREAD

**Issue by maticko** [nginxinc/kubernetes-ingress#188]
#90 and #100 add support for health check but I cannot see any instructions on how to use this. After some digging around the code, it looks like I would have to build an image on my own and set some flag to enable that. Is there a way that this could be enabled by annotations? 

Without this health endpoint, it's hard to setup zero-downtime deployments since we cannot setup readiness and liveness probes. Is there any other workaround?

**Comment by pleshakov** [comment]
@maticko 
Please add the argument `-health-status true` in the Ingress controller yaml. When enabled, you can check NGINX health via `<pod-ip>/nginx-health` URL.

**Comment by maticko** [comment]
@pleshakov Thanks for this.
Pasting my configuration if someone will have the same trouble. 
```
    spec:
      containers:
      - image: nginxdemos/nginx-ingress:0.9.0-alpine
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        readinessProbe:
          httpGet:
            path: /nginx-health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /nginx-health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
        args:
          - -health-status=true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
```

If you tell me where I can update examples documentation...
