### ISSUE TITLE
Configure multiple certificates for the same domain name

### ISSUE THREAD

**Issue by alexandersm** [nginxinc/kubernetes-ingress#1899]
Hello, 

In the Nginx documentation at http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate there is a possibility to specify _ssl_certificate / ssl_certificate_key_  directives multiple times for the same domain name.

Is it possible to configure Nginx Ingress to use more than one TLS secret for the same domain name ?
I've tried the following configuration :

```yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-for-ingress-ingress
 
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        -  my.domain.com
      secretName: es9gsmatest  

    - hosts:
        -  my.domain.com
      secretName: es9gsmatest2

  rules:
  - host: my.domain.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: httpservice
            port:
              number: 9050
```

but then I checked resulting Nginx configuration inside the ingress pod and found out that only certificate and key from the second secret is used.

Thanks in advance for the help
