### ISSUE TITLE
Default backend in Ingress Resource

### ISSUE THREAD

**Issue by pleshakov** [nginxinc/kubernetes-ingress#19]
Currently NGINX Controller doesn't handle default backends:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-default-backend
spec:
  backend:
    serviceName: testsvc
    servicePort: 80
```
