### ISSUE TITLE
Is the globalconfiguration and transportserver only for nginx plus ?

### ISSUE THREAD

**Issue by bkannadassan** [nginxinc/kubernetes-ingress#1900]
Hi All,

   We are using nginx ingress controller for UDP loadbalancing. Is it that the CRD's provided by nginx is only for Nginx Plus  ?. We are having GlobalConfiguration and Transport server and the same works fine with nginx=false in helm I hope this means its not an nginx plus feature am I rt?. We are having a lot of confusion on this for our deployment. Can you please clarify the same ?. Document clearly says some features like healthcheck is licensed and not others..

rgds
Balaji

**Comment by soneillf5** [comment]
Hi @bkannadassan,

Thanks for you query, TransportServers and GlobalConfiguration are not just for plus, they should be available and working for you. Can you post some more details and I can take a look? ( Config / logs )

**Comment by bkannadassan** [comment]
```
apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration
metadata:
  name: nginx-configuration
  namespace: kube-system
spec:
  listeners:
  - name: udp-lb
    port: 2123
    protocol: UDP
```

```
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: dns-udp
  namespace: test
spec:
  listener:
    name: udp-lb
    protocol: UDP
  upstreams:
  - name: dns-app
    service: external-traffic-data
    port: 21233
  upstreamParameters:
    udpRequests: 1
    udpResponses: 1
  action:
    pass: dns-app
```

Please find above is my configuration...
