### ISSUE TITLE
Disabling AllowedPrivilageAccess to false causes pod crash

### ISSUE THREAD

**Issue by bnnk** [nginxinc/kubernetes-ingress#1933]
Steps to Reproduce:

```
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
```
With Above configuration it crashes

**Expected behavior**
Looks like from other forums its mandatory. We have a customer requirement that this shouldn't be allowed privilage access. Any other way to get around the same ?

Any input on the same would be helpful..

rgds
BnnK
