### ISSUE TITLE
ConfigMap values don't appear to be applying

### ISSUE THREAD

**Issue by ElvenSpellmaker** [nginxinc/kubernetes-ingress#1950]
**Describe the bug**
Using Nginx Ingress when I try to apply `ssl-redirect` and `hsts` they don't seem to be working.

Going to foo.foo.com gives me http with no redirect.

**To Reproduce**
As per: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/

Note it says that `ssl-redirect` is on by default but it doesn't appear to be. 🤔 

A ConfigMap like the following:
![image](https://user-images.githubusercontent.com/2286713/132874484-d5d30bee-437c-42f2-be2b-03d55f569e11.png)

Nginx configuration like so:
```yml
        - name: nginx-ingress
          image: 'nginx/nginx-ingress:1.8.1'
          args:
            - '-nginx-configmaps=$(POD_NAMESPACE)/nginx-config'
            - '-default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret'
            - '-global-configuration=$(POD_NAMESPACE)/nginx-configuration'
```

(Note if the ConfigMap doesn't exist it will fail to start so it's clearly reading it but not doing anything with the values.)

VirtualServers like the following:
```yml
apiVersion: k8s.nginx.org/v1
metadata:
  name: foo
  namespace: foo
kind: VirtualServer
spec:
  host: foo.foo.com
  routes:
    - action:
        pass: foo
      path: /
  tls:
    secret: wildcard-tls
  upstreams:
    - name: foo
      port: 80
      service: foo
      tls:
        enable: false
```

**Expected behavior**
When going to foo.foo.com a SSL 301 redirect should be present and an HSTS header on the redirected content.
