### ISSUE TITLE
UDPResponse 0 not able to handle the response even with higher session timeout..

### ISSUE THREAD

**Issue by bnnk** [nginxinc/kubernetes-ingress#2005]
**Describe the bug**
As per the user guide if udpResponses is 0 even then reply packet will be handled till sessionTerminates. But apparently even with session timeout we see that the responses aren't handeled..

**To Reproduce**
udpResponses 0
udpRequests 1
Sessiontimeout 60s

A ping via nginx we see response coming to nginx but packet getting dropped.

**Expected behavior**
Since session timeout is 60s we shouldn't be seeing any packet drop.

**Your environment**
Kubernetes running nginx ingress controller 

**Additional context**
Since we need to pump at high rate and we have same source ip/port received. When receiving the packet we want to spray across upstream pods. When we have UDP req set to 1 and rsp to 0 we didn't see any drop and if we keep UDP Req and Resp high packets go to the same backend pods for so many requests. Shouldn't the Request when received the session should be retained ? why when UDP response is 0 not even a single response is handled.

rgds
bnnk

**Comment by brianehlert** [comment]
Can you please help us a bit by including the version of NGINX Ingress Controller, NGINX, and your configuration resources (if possible).
Also, was their anything telling in the logs?  Such as not being able to find the upstream (backing service).

**Comment by workhorse2020** [comment]
```
spec:
  action:
    pass: upstream-gw
  listener:
    name: udp-gw
    protocol: UDP
  sessionParameters:
    timeout: 60s
  upstreamParameters:
    nextUpstream: true
    nextUpstreamTimeout: 20s
    nextUpstreamTries: 1
    udpRequests: 1
    udpResponses: 0
  upstreams:
```
@brianehlert  Please find above is the config and from logs we don't see any issues..
