### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by suedschwede** [nginxinc/kubernetes-ingress#2046]
I use helm install "my-release nginx-stable/nginx-ingress"

My Ingress Definition

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openliberty-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "off"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
   - hosts:
     - openliberty2.mic.co.at
     secretName: mic.co.at
  rules:
  - host: openliberty2.mic.co.at
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openliberty-service
            port:
              number: 9443
```

Error in NGINX
`
2021/10/06 08:09:19 [error] 28#28: *36 upstream prematurely closed connection while reading response header from upstream, client: 172.29.16.1, server: openliberty2.mic.co.at, request: "GET / HTTP/1.1", upstream: "http://10.42.0.57:9443/", host: "openliberty2.mic.co.at"
172.29.16.1 - - [06/Oct/2021:08:09:19 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0" "-"
`

Error in the target POD
`[ERROR   ] CWWKO0801E: Unable to initialize SSL connection. Unauthorized access was denied or security settings have expired. Exception is javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:146)
	at sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:475)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:398)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:377)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInbound(SSLConnectionLink.java:560)
	at [internal classes]`

This error does not happen if i use the repository "https://kubernetes.github.io/ingress-nginx"
