### ISSUE TITLE
nginx.ingress.kubernetes.io/rewrite-target annotation doesn't redirect

### ISSUE THREAD

**Issue by Kristin0** [nginxinc/kubernetes-ingress#2057]
I have a pod that responds to requests to /

I want to do a rewrite where requests  where /dashboard go to /.

Using a nginx-ingess I  do it something like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /dashboard(/|$)(.*)
        backend:
          service:
            name: kubernetes-dashboard
            port: 
              number: 8443
```
But this only works when I manually add slash in the end: /dashboard/ 
Only after that it opens this URL:  https://192.168.x.x/dashboard/#/workloads?namespace=default
When I don't add slash in the end, it opens the white page in browser
When I curl from WSL it opens without any redirecting ( i think should not rely on wsl curl )
```
user@server:~$ curl -k -IL "https://192.168.99.100/dashboard"
HTTP/2 200
date: Thu, 07 Oct 2021 15:52:11 GMT
content-type: text/html; charset=utf-8
content-length: 1338
accept-ranges: bytes
cache-control: no-cache, no-store, must-revalidate
last-modified: Wed, 16 Jun 2021 10:53:38 GMT

user@server:~$ curl -k -IL "https://192.168.99.100/dashboard/"
HTTP/2 200
date: Thu, 07 Oct 2021 15:53:50 GMT
content-type: text/html; charset=utf-8
content-length: 1338
accept-ranges: bytes
cache-control: no-cache, no-store, must-revalidate
last-modified: Wed, 16 Jun 2021 10:53:38 GMT

```

nginx/controller:v1.0.0-beta.3@sha256:44a7a06b71187a4529b0a9edee5cc22bdf71b414470eff696c3869ea8d90a695 

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

minikube version: v1.23.2
commit: 0a0ad764652082477c00d51d2475284b5d39ceed
