### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by rawlingsj** [nginxinc/kubernetes-ingress#21]
We've deployed a docker registry and created an ingress rule to it's kubernetes service whilst using the nginx ingress controller.  When pushing larger images we quickly hit the nginx limits giving us the error below.
```
Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.9.14</center>\r\n</body>\r\n</html>\r\n"

```

I've forked the repo and hacked the [nginx config](https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/nginx/ingress.tmpl#L8) adding a `client_max_body_size` attribute so we can push larger images.  For a proper solution though, it might be nice to set a value in the kubernetes ingress rule and have that used when the nginx controller is updated?

**Comment by pleshakov** [comment]
We plan to add the ability to configure the global NGINX parameters through a ConfigMap.

To allow to customize the configuration per Ingress resource, we can leverage annotations. As an example,
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    nginx/client_max_body_size: 1m
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```
Will that work for your case?

**Comment by rawlingsj** [comment]
@pleshakov yeah that would be great!

**Comment by styxlab** [comment]
This already works with ConfigMaps such as:

```
apiVersion: v1
kind: ConfigMap
data:
  body-size: "0"
metadata:
  name: nginx-conf
```

Make sure to reference the ConfigMap in your ingress controller like so:

```
args:
        - /nginx-ingress-controller
        - --default-backend-service=default/default-http-backend
        - --nginx-configmap=default/nginx-conf
```

For more information on the available config parameters have a look at [here](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/custom-configuration).

**Comment by pleshakov** [comment]
We're adding this features as well as other NGINX configuration parameters soon. Stay tuned.

**Comment by pleshakov** [comment]
customization of NGINX configuration was added in https://github.com/nginxinc/kubernetes-ingress/pull/33

**Comment by pleshakov** [comment]
@rawlingsj  Please check the example on how to customize NGINX: https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization

**Comment by Hronom** [comment]
Not worked in `gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.2` and `gcr.io/google_containers/nginx-ingress-controller:0.8.3` I set value like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/client-max-body-size: "100m"
spec:
  rules:
  - host: test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: test
          servicePort: 8888
```

**Comment by pleshakov** [comment]
@Hronom the `google_containers/nginx-ingress-controller` images belong to a different project. Please see the documentation for that project available on this page https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md

The image for this project -- https://hub.docker.com/r/nginxdemos/nginx-ingress/tags/

**Comment by Hronom** [comment]
@pleshakov sorry guys, too many `kubernetes ingresses` over internet...

**Comment by misteruly** [comment]
@Hronom I'm setting it like that, but it doesn't work

**Comment by deesx** [comment]
same here

**Comment by lastcoolnameleft** [comment]
FYI, the annotation has changed and is now:
```
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
```

Also, I had to restart the nginx pod for the effect to take place.  It immediately started working after that.

**Comment by ryanrca** [comment]
Some of our containers were pushing over 250m.
Setting it to "0" makes the nginx post size unrestricted:
```
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
```

**Comment by jslay88** [comment]
Yeah... I still cant get this annotation to work at all.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
```
