### ISSUE TITLE
Error when trying example on GCP

### ISSUE THREAD

**Issue by felipear89** [nginxinc/kubernetes-ingress#210]
I'm trying the examples at `kubernetes-ingress/examples/complete-example/` 

When I run `kubectl create -f cafe-ingress.yaml` and I got this error on Google Cloud Platform

`Error 400: Invalid value for field 'namedPorts[0].port': '0'. Must be greater than or equal to 1`

I've changed the `cafe-ingress.yaml` to fix this. I added the annotation `kubernetes.io/ingress.class`

Here is the beginning of the file
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
```
I'd like to suggest add this in the documentation
