### ISSUE TITLE
VirtualServer unable to use defaultTLS

### ISSUE THREAD

**Issue by gogovan-vincentngai** [nginxinc/kubernetes-ingress#2126]
**Describe the bug**
Not sure this is expected or bug 
defaultTLS no working in VirtualServer but ingress 
and also working for giving a static secret name

**To Reproduce**
Helm install with Value 
```
  ## It is recommended to use your own TLS certificates and keys
  defaultTLS:
    cert: "" 
    key: ""
    secret: nginx-ingress/my-secret-tls
```

VirtualServer
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: dev-play
  namespace: dev-play
spec:
  host: dev-play.xyz.com
  ingressClassName: nginx
  upstreams:
  - name: dev-play
    service: dev-play
    port: 80
  routes:
  - path: /
    action:
      pass: dev-play
```
Already Try adding
```
...
  tls:
...
```
When i access **http://dev-play.xyz.com**  it return normal HTTP page 
however when i try access **https://dev-play.xyz.com** it return 404 to me 
When i delete the **VirtualServer** and deploy to use **ingress** , the default cert is working as expected

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: demo-ingress
 namespace: dev-play
 annotations:
   kubernetes.io/ingress.class: "nginx"
spec:
 tls:
 - hosts:
   - dev-play.xyz.com
 rules:
 - host: dev-play.xyz.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: dev-play.xyz.com
           port:
             number: 80
```

When i go back to VirtualServer
I copy the TLS secret to the namespace and then apply below in the config
The result is back to normal i can access both HTTP and HTTPS 
```
  tls:
    secret: my-secret-tls
```
However this means i need to copy the TLS cert to all namespace when i use VirtualServer

**Expected behavior**
Success access and return with HTTPS site for both VirtualServer and Ingress

**Your environment**
nginx/1.21.3 
Chart version 2.0.2
