### ISSUE TITLE
Proxy WebSockets

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#214]
I have my ingress working fine with standard HTTPS to my Web UI server, now I need to enable the ingress controller to proxy WebSocket calls from the Javascript running in the browser UI as well as https calls.  Any help would be appreciated.

**Comment by SiriusRed** [comment]
You should read this document for enabling WS(WSS) for ingress upstreams.
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket

If you use ingress with enabled TLS your URL to WS endpoint should started with "wss://" prefix.

**Comment by RudyBone** [comment]
My web app start page is accessed on the path /myspo/ui/.  I have 2 WebSocket endpoints as subpaths: /myspo/ui/exec and /myspo/ui/log.  How do I configure the ingress yaml to allow https access to /myspo/ui/ and websocket access to the ws endpoints?

**Comment by SiriusRed** [comment]
Dont worry and just set  in `nginx.org/websocket-services` annotation your service, which will be handle (or proxy) ws connection. Enable `nginx.org/websocket-services` allow to http(s) traffic (ws starts work in http-level).

If your WS services is different services, then you should configure ingress like in manifest

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.org/websocket-services: "ws-service1,ws-service2"
spec:
 tls:
    - secretName: your-tls-secret-name
      hosts:
      - hostname.com
  rules:
  - host: hostname.com
    http:
      paths:
      - path: /myspo/ui/
        backend:
          serviceName: web-app
          servicePort: 80
      - path:  /myspo/ui/log
        backend:
          serviceName: ws-service1
          servicePort: 8000
      - path: /myspo/ui/exec
        backend:
          serviceName: ws-service2
          servicePort: 8000
```

**Comment by RudyBone** [comment]
So basically I have to create 3 services instead of just 1.  I'll give this a try.

**Comment by SiriusRed** [comment]
No. If you have one service (e.g. web-app) should use next configuration:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.org/websocket-services: "web-app"
spec:
 tls:
    - secretName: your-tls-secret-name
      hosts:
      - hostname.com
  rules:
  - host: hostname.com
    http:
      paths:
      -  backend:
          serviceName: web-app
          servicePort: 80
```
