### ISSUE TITLE
kubernetes v1.16.3 couldn't install nginx-ingress-controller v1.12.0

### ISSUE THREAD

**Issue by zruijie** [nginxinc/kubernetes-ingress#2199]
**Describe the bug**
I install ingress controller followed by https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/

My steps is:

Prerequisites:

```
$ git clone https://github.com/nginxinc/kubernetes-ingress/
$ cd kubernetes-ingress/deployments
$ git checkout v1.12.0
```

1. Configure RBAC

```
$ kubectl apply -f common/ns-and-sa.yaml
$ kubectl apply -f rbac/rbac.yaml
```

2. Create Common Resources

```
$ kubectl apply -f common/default-server-secret.yaml
$ kubectl apply -f common/nginx-config.yaml
```

Create ingress-class err:

```
$ kubectl apply -f common/ingress-class.yaml
error: unable to recognize "common/ingress-class.yaml": no matches for kind "IngressClass" in version "networking.k8s.io/v1beta1"
```

My k8s version is v1.16.3, and IngressClass is new resource from v1.18.0:

> ref: https://v1-18.docs.kubernetes.io/docs/setup/release/notes/#extending-ingress-with-and-replacing-a-deprecated-annotation-with-ingressclass
> 
> In Kubernetes 1.18, there are two significant additions to Ingress: A new pathType field and a new IngressClass resource. The pathType field allows specifying how paths should be matched. In addition to the default ImplementationSpecific type, there are new Exact and Prefix path types.
> 
> The IngressClass resource is used to describe a type of Ingress within a Kubernetes cluster. Ingresses can specify the class they are associated with by using a new ingressClassName field on Ingresses. This new resource and field replace the deprecated kubernetes.io/ingress.class annotation.
> 

but nginx-ingress-controller release note said k8s v1.16 to 1.21 has been tested:

> ref: https://docs.nginx.com/nginx-ingress-controller/releases/
> 
> We will provide technical support for the NGINX Ingress Controller on any Kubernetes platform that is currently supported by its provider and which passes the Kubernetes conformance tests. This release was fully tested on the following Kubernetes versions: 1.16-1.21.

I just want nginx version v1.20+ in my cluster, but cann't upgrade k8s to v1.18.0. 

Anyone can help me to find a good  nginx-ingress controller version? 

Thank you very much.

**Comment by zruijie** [comment]
Actully, I just want to make nginx-ingress controller work well. 

Did the yaml in  https://github.com/nginxinc/kubernetes-ingress/ is wrong? or I misunderstand something important?

**Comment by lucacome** [comment]
Hi @zruijie 

with k8s 1.16 you don't need to deploy the IngressClass (since it doesn't exist in that version) you can just keep using the annotation `kubernetes.io/ingress.class`

Let me know if it makes sense.

**Comment by zruijie** [comment]
> Hi @zruijie
> 
> with k8s 1.16 you don't need to deploy the IngressClass (since it doesn't exist in that version) you can just keep using the annotation `kubernetes.io/ingress.class`
> 
> Let me know if it makes sense.

@lucacome thanks, it works for the mergeable-ingress-types demo: <https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types>. I can find a new conf default-cafe-ingress-master.conf in <nginx-ingress pod>:/etc/nginx/conf.d  The example is good enough. 

But my example is not worked, below is my yaml:

```yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: baas-blockchain-manager-master-ingress
  namespace: bcap-baas
  annotations:
    nginx.org/client-max-body-size: 500m
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
    - host: baasadmin.spdb.com
```

```yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: baas-blockchain-manager-minion-ingress
  namespace: bcap-baas
  annotations:
    nginx.org/client-max-body-size: 500m
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: baasadmin.spdb.com
      http:
        paths:
          - path: /baasapiv2
            backend:
              serviceName: baas-blockchain-manager-svc
              servicePort: 8085
```

create master-minion-ingress:

```
$ kubectl apply -f baas-blockchain-manager-master-ingress.yaml
$ kubectl apply -f baas-blockchain-manager-minion-ingress.yaml
```

kubectl cmd told me they were been created. However, I couldn't find my config in <nginx-ingress pod>:/etc/nginx/conf.d. The only two conf were there:

```
$ kubectl exec -it nginx-ingress-2pbnr -n nginx-ingress -- ls /etc/nginx/conf.d
default-cafe-ingress-master.conf  kube-system-kubernetes-dashboard-ingress.conf
```

My yaml is wrong? Thanks a lot.
