### ISSUE TITLE
Support 80 & 443 with same ingress

### ISSUE THREAD

**Issue by dannymk** [nginxinc/kubernetes-ingress#229]
How does one support both HTTP and HTTPS in the same ingress on separate hosts?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-https-ingress
  namespace: default
  annotations:
     nginx.org/ssl-services: "cas-service"
spec:
  tls:
  - hosts:
    - cas.mydomain.com
    secretName: my-global-certificate
    
  rules:
  - host: cas.mydomain.com
    http:
      paths:
      - backend:
          serviceName: cas-service
          servicePort: 443
          
  - host: glassfish.mydomain.com
    http:
      paths:
      - backend:
          serviceName: glassfish-service
          servicePort: 80
```

It sounds like this should be obvious and work out of the box but I cannot figure it out.
I have read the documentation and played with multiple examples over the past few months yet I cannot get this to work.  SSL works fine and any hosts that meets the SSL ingress works.  However when I try to introduce an HTTP (80) endpoint it does not work.

All I get when I try to access the host above at:  glassfish.mydomain.com is:

404 Not Found
nginx/1.13.7

obviously not very helpful.  

Now, I get the "SSL Services Support" [https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services](url)

But that is for the same host not for what I need.

An example would be great.   

I am using:  nginxdemos/nginx-ingress:1.1.0

Thank you.
