### ISSUE TITLE
question: VS routing to another namespace (VSR) by conditions

### ISSUE THREAD

**Issue by vakapral** [nginxinc/kubernetes-ingress#2306]
Seems that VS cannot route to another namespace (VSR) by conditions.
What I mean:
alcohol.yaml
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: alcohol
  namespace: alcohol
spec:
  host: foo.bar.com
  routes:
  - action:
      pass: vodka
    matches:
    - action:
        route: 'non-alcohol/'
      conditions:
      - cookie: non_alcohol
        value: always
    path: /
  upstreams:
  - name: vodka
    port: 80
    service: vodka-svc
```

non-alcohol.yaml
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: non-alcohol
  namespace: non-alcohol
spec:
  host: foo.bar.com
  upstreams:
  - name: milk
    service: milk-svc
    port: 80
  subroutes:
  - path: /
    action:
      pass: milk
```

I got:
`error validating data: ValidationError(VirtualServer.spec.routes[0].matches[0].action): unknown field "route" in org.nginx.k8s.v1.VirtualServer.spec.routes.matches.action`

Is there any other way to implement this kind of routing?
