### ISSUE TITLE
Does path rewriting support regex?

### ISSUE THREAD

**Issue by pistoolster** [nginxinc/kubernetes-ingress#2377]
My yaml file likes 
```yaml
spec:
  rules:
    - host: my-host
      http:
        paths:
          - path: /api/path1/
            backend:
              serviceName: dev-svc
              servicePort: 80
          - path: /api/path2/
            backend:
              serviceName: dev-svc
              servicePort: 80
```

Is there a way I can rewrite 
- `/api/path1/`  to `/api/v1/path1/`
- `/api/path2` to `/api/v1/path2/`?

I tried 
```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: dev-ingress
  namespace: dev
  annotations:
    nginx.org/rewrites: serviceName=dev-svc rewrite=/api/v1/$1
```
doesn't work.

Thanks.

Aha! Link: https://nginx.aha.io/features/IC-414
