### ISSUE TITLE
conflicting server name "api.dev.example.com" on 0.0.0.0:80, ignored

### ISSUE THREAD

**Issue by rjrhaverkamp** [nginxinc/kubernetes-ingress#244]
Hi @pleshakov 

We(as in the company I work for) have had contact with NGINX Plus support about this issue and they told us to open an issue at Github.

The issue we face is that we have multiple ingress resources separated over namespaces in the same cluster. initially we had two namespaces: `development` and `test`. The `development` namespace uses hostnames/domains such as: `api.dev.example.com` and `www.dev.example.com`.

In the `test` namespace we use hostnames/domains such as: `api.test.example.com` and `www.test.example.com`. This all works without issues.

However we added a third namespace called `platform-development`. In this namespace we added the following ingress together with a deployment and service:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: organisation-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.dev.example.com
    http:
      paths:
      - path: /organisation
        backend:
          serviceName: organisation-api-svc
          servicePort: 8081
```

Note that there is an ingress in the `development` namespace and `platform-development` namespace both using `api.dev.example.com`. 

With this setup we receive the following error message: 
```
 I0215 10:55:00.617237       1 nginx.go:278] NGINX configuration file had been updated
I0215 10:55:00.617306       1 nginx.go:334] executing nginx -t
2018/02/15 10:55:00 [warn] 759#759: conflicting server name "api.dev.example.com" on 0.0.0.0:80, ignored
2018/02/15 10:55:00 [warn] 759#759: conflicting server name "api.dev.example.com" on 0.0.0.0:80, ignored
I0215 10:55:00.633310       1 nginx.go:334] executing nginx -s reload
2018/02/15 10:55:00 [warn] 761#761: conflicting server name "api.dev.example.com" on 0.0.0.0:80, ignored
2018/02/15 10:55:00 [warn] 761#761: conflicting server name "api.dev.example.com" on 0.0.0.0:80, ignored
2018/02/15 10:55:00 [notice] 761#761: signal process started
2018/02/15 10:55:00 [notice] 14#14: signal 1 (SIGHUP) received from 761, reconfiguring
2018/02/15 10:55:00 [notice] 14#14: reconfiguring
I0215 10:55:00.649164       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"platform-dev", Name:"organisation-api", UID:"f5a67be7-0fdf-11e8-b939-42010aa40fc4", APIVersion:"extensions", ResourceVersion:"2689315", FieldPath:""}): type: 'Normal' reason: 'AddedOrUpdated' Configuration for platform-dev/organisation-api was added or updated
2018/02/15 10:55:00 [warn] 14#14: conflicting server name "api.dev.example.com" on 0.0.0.0:80, ignored
2018/02/15 10:55:00 [warn] 14#14: conflicting server name "api.dev.example.com" on 0.0.0.0:80, ignored 
```

Are we trying to do something that is unsupported or?

If you need any more information, let me know. 

_____________

currently running nginx-plus-r14-p1 (1.13.7) in a Google Kubernetes Engine (formerly known as Google Container Engine).

**Comment by pleshakov** [comment]
@rjrhaverkamp 
Is that correct that you have multiple Ingress controllers, one per namespace? Did you deploy them with the `-watch-namespace <namespace>` argument?

Also, please make sure that there are no other Ingress resources created in the namespace `platform-development` are for the `host: api.dev.example.com`.  The Ingress controller doesn't support multiple Ingress resources, defined for the same host.

**Comment by rjrhaverkamp** [comment]
@pleshakov 

No, we only use one ingress controller. But we have multiple ingresses(one per namespace).

>  The Ingress controller doesn't support multiple Ingress resources, defined for the same host.

So what we are trying to do is unsupported? Is there a practical reason for this or is it something that is possible in the future?

Thanks!

**Comment by rjrhaverkamp** [comment]
@pleshakov 
No, we do not run multiple ingress controllers. We have one controller located in `kube-system` and use one ingress resource per namespace.

> The Ingress controller doesn't support multiple Ingress resources, defined for the same host.
It doesn't support this cluster wide or only not in the same namespace? Is there a reason why this is not supported?

**Comment by pleshakov** [comment]
@rjrhaverkamp 
> So what we are trying to do is unsupported? 

correct

> Is there a practical reason for this or is it something that is possible in the future?

Behind one Ingress controller is a single NGINX. NGINX has a concept of the virtual server, which routes the requests for a particular host, for example `foo.example.com`. There is one to one correspondence between an Ingress resource and a virtual server. NGINX, by design, does not support multiple virtual servers for the same hostname. That's why the Ingress controller doesn't support multiple Ingress resources for the same hostname.

Potentially, we can merge all Ingress resources into one in the Ingress controller and then generate one virtual server in NGINX. However, we decided not to do that due to complexity of the implementation and that fact that merging was not a popular feature request.

**Comment by AndrewDi** [comment]
@pleshakov It seems like nginx-ingress could not merige multiple Ingresses resources for the same host name in different namespaces?

**Comment by pleshakov** [comment]
@AndrewDi 
how did you deploy your Ingress resources? Did you use `nginx.org/mergeable-ingress-type` annotation?

**Comment by AndrewDi** [comment]
I write two yaml like following as example:
Kube-Dashboard yaml：
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.dev.example.com
    http:
      paths:
      - path: /dashboard
        backend:
          serviceName: dashboard-service
          servicePort: 443
```

rook ceph dashboard yaml：
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ceph-ingress
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.dev.example.com
    http:
      paths:
      - path: /ceph
        backend:
          serviceName: rook-ceph-service
          servicePort: 8443
```

@pleshakov do you mean I should write like this one?
```yaml
annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type
```

**Comment by pleshakov** [comment]
@AndrewDi 
thanks for sharing. In your case you need to have 3 Ingress resources:
1 - master

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: master-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
  - host: api.dev.example.com
```

2.1 - minion for api.dev.example.com/dashboard

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: api.dev.example.com
    http:
      paths:
      - path: /dashboard
        backend:
          serviceName: dashboard-service
          servicePort: 443
```
2.2 - minion for api.dev.example.com/ceph
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ceph-ingress
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: api.dev.example.com
    http:
      paths:
      - path: /ceph
        backend:
          serviceName: rook-ceph-service
          servicePort: 8443
```

To enable SSL to backends, use `nginx.org/ssl-services` in minions. See also https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services
