### ISSUE TITLE
client intended to send too large chunked body

### ISSUE THREAD

**Issue by aprisniak** [nginxinc/kubernetes-ingress#246]
I'm running on nginxdemos/nginx-ingress:1.1.1. I'm trying to deploy docker registry. After I'll push my image I'm receiving this error: 
```
[error] 94#94: *114 client intended to send too large chunked body
```
My ingress rule looks like:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-tls
  namespace: registry
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1000m
    nginx.ingress.kubernetes.io/proxy-body-size: "0" // even try 1000m
spec:
  tls:
  - hosts:
      - registry.example.com
    secretName: registry-tls
  rules:
  - host: registry.example.com
    http:
      paths:
      - backend:
          serviceName: registry
          servicePort: 5000
        path: /
```

Looks like nginx.ingress.kubernetes.io/proxy-body-size annotation takes no effect.

This is config on nginx controller:
```
        location / {
                proxy_http_version 1.1;


                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_buffering on;

                proxy_pass http://registry-registry-tls-registry2.example.com-registry;

        }
```
