### ISSUE TITLE
Service nodePort values are not passed to manifest from Helm Chart values.yaml

### ISSUE THREAD

**Issue by MurzNN** [nginxinc/kubernetes-ingress#2495]
**Describe the bug**
I'm trying to set fixed `nodePort` to `nginx-ingress` service via following `values-override.yaml` file:
```yaml
controller:
  service:
    type: NodePort
    httpPort:
      nodePort: "30080"
    httpsPort:
      nodePort: "30443"
```
But Helm Chart generates the Service manifest without those values:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.17
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.1"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  ipFamilyPolicy: SingleStack
  ipFamilies: 
    - IPv4
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
```

**To Reproduce**
1. Create `values-override.yaml` file as above.
2. Install Helm Chart with those values
4. See that desired `nodePort` values are missing in Service manifest.

**Expected behavior**
The desired `nodePort` values must be presend in Service manifest.

**Your environment**
* Version of the Ingress Controller -  ingress-nginx-4.0.17
* Version of Kubernetes - v1.23.4
* Kubernetes platform - Self-Hosted
* Using NGINX
