### ISSUE TITLE
IP whitelist

### ISSUE THREAD

**Issue by aprisniak** [nginxinc/kubernetes-ingress#253]
Is there a way to configure whitelist IP's? Does this controller supports for this feature?

**Comment by pleshakov** [comment]
@aprisniak it is possible to configure that using *-snippets annotations and configmap keys, which allow you to use native NGINX configuration. For example:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.org/server-snippets: "allow 192.168.1.3; deny all;"
...
```

See http://nginx.org/en/docs/http/ngx_http_access_module.html to learn more about allow/deny directives.
