### ISSUE TITLE
Add support for escaping chars in APLogConf CRD

### ISSUE THREAD

**Issue by Binsabbar** [nginxinc/kubernetes-ingress#2601]
I am setting up my logs as json and I would like to escape certain charts. It is possible as explained here https://docs.nginx.com/nginx-app-protect/configuration-guide/configuration/#log-with-escaped-character-and-custom-list-prefix--delimiter--suffix

However, looking at https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/helm-chart/crds/appprotect.f5.com_aplogconfs.yaml, it is clearly not supported :( 

Adding support for the following keys under content
```
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: ap-logs-conf-json
  namespace: nginx-ingress
spec:
  filter:
    request_type: illegal
  content:
    format: user-defined
    format_string: "my json format goes here"
    max_request_size: any
    max_message_size: 5k
    escaping_characters:
      - from: '"'
        to: '\"'
    list_prefix: "["
    list_delimiter: ","
    list_suffix: "]"
````

As a workaround I am using Promtail pipelines-stages (`regex`, and `template` stages) to format the logs and do the escaping myself, which is annoying to be honest.

**Comment by Binsabbar** [comment]
I am not familiar with `Go` lang, however from browsing the code, I noticed that https://github.com/nginxinc/kubernetes-ingress/blob/main/internal/k8s/appprotect/app_protect_configuration.go#L165 is `Obj      *unstructured.Unstructured`

Does it mean if I only update CDR to support the field above, I will be able to render them in the generated config?

If that's the case, I am keen to submit an MR for that, otherwise, I will need to learn `Go` instead to contribute.

**Comment by Binsabbar** [comment]
> I am not familiar with `Go` lang, however from browsing the code, I noticed that https://github.com/nginxinc/kubernetes-ingress/blob/main/internal/k8s/appprotect/app_protect_configuration.go#L165 is `Obj *unstructured.Unstructured`
> 
> Does it mean if I only update CDR to support the field above, I will be able to render them in the generated config?
> 
> If that's the case, I am keen to submit an MR for that, otherwise, I will need to learn `Go` instead to contribute.

That worked for me. So I did the following in CDR:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: aplogconfs.appprotect.f5.com
spec:
  group: appprotect.f5.com
  names:
    kind: APLogConf
    listKind: APLogConfList
    plural: aplogconfs
    singular: aplogconf
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          description: APLogConf is the Schema for the APLogConfs API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: APLogConfSpec defines the desired state of APLogConf
              properties:
                content:
                  properties:
                    format:
                      enum:
                        - splunk
                        - arcsight
                        - default
                        - user-defined
                        - grpc
                      type: string
                    format_string:
                      type: string
                    list_prefix:
                      type: string
                    list_delimiter:
                      type: string
                    list_suffix:
                      type: string
                    escaping_characters:
                      items:
                        properties:
                          from:
                            type: string
                          to:
                            type: string
                        type: object
                      type: array 
                    max_message_size:
                      pattern: ^([1-9]|[1-5][0-9]|6[0-4])k$
                      type: string
                    max_request_size:
                      pattern: ^([1-9]|[1-9][0-9]|[1-9][0-9]{2}|1[0-9]{3}|20[1-3][0-9]|204[1-8]|any)$
                      type: string
                  type: object
                filter:
                  properties:
                    request_type:
                      enum:
                        - all
                        - illegal
                        - blocked
                      type: string
                  type: object
              type: object
          type: object
      served: true
      storage: true
```

and it worked fine as expected, here is example of the output 
```
{"attack_type": "[Abuse of Functionality]", "violations": "[Illegal meta character in URL]"}
```

```
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: ap-logs-conf-illegal-json
  namespace: nginx-ingress
spec:
  filter:
    request_type: illegal
  content:
    format: user-defined
    format_string: "{\"attack_type\": \"%attack_type%\", \"violations\": \"%violations%\"}"
    max_request_size: any
    max_message_size: 5k
    escaping_characters:
      - from: '"'
        to: '\"'
    list_prefix: "["
    list_delimiter: ","
    list_suffix: "]" 
```

Yes I know the array is not valid array, but that's fine for me for now. At least the escaping_charts is working as expected !
