### ISSUE TITLE
Customization of NGINX configuration

### ISSUE THREAD

**Issue by pleshakov** [nginxinc/kubernetes-ingress#27]
Currently, there is no way to customize NGINX configuration other than change the template file and rebuild the image.

Add support for customization of some NGINX parameters, such as `proxy_read_timeout`, `proxy_connect_timeout`, `client_max_body_size` (https://github.com/nginxinc/kubernetes-ingress/issues/21) and others via [ConfigMaps](http://kubernetes.io/docs/user-guide/configmap/)

Add the ability to redefine those parameters per Ingress Resource. Can be done via annotations --> https://github.com/nginxinc/kubernetes-ingress/issues/21

**Comment by pleshakov** [comment]
Added in https://github.com/nginxinc/kubernetes-ingress/pull/33

**Comment by edouardKaiser** [comment]
I prefer this NGINX Ingress Controller than the one in Kubernetes Contrib (https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) because this one is using the service Virtual IP instead of maintaining a list of Pods IP addresses.

Unfortunately, we can't use this one because of the lack of configuration options. We would love to be able to configure the log format too for example. Or add a HTTP authentication on the ingress rule.

In the Kubernetes Contrib, they do it through annotations:

```
  annotations:
    # type of authentication
    ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    ingress.kubernetes.io/auth-secret: http-basic-auth
    # message to display with an appropiate context why the authentication is required
    ingress.kubernetes.io/auth-realm: "Authentication Required"
```
