### ISSUE TITLE
Directive duplicate if tls-passthrough is enabled when using with F5 Big-IP.

### ISSUE THREAD

**Issue by f5-will** [nginxinc/kubernetes-ingress#2721]
When I test using KIC with F5 Big-IP following the official document, I found the KIC container can't be ready. I checked the logs and found there is directive duplicate.

```shell
I0526 02:46:16.385301       1 main.go:397] Using nginx version: nginx/1.21.3 (nginx-plus-r25)
nginx: [emerg] "real_ip_header" directive is duplicate in /etc/nginx/nginx.conf:87
```

I found that this is because I enabled tls-passthrough and this feature will also add "real_ip_header" in NGINX configuration. So it causes the directive duplicate.

I also opened a ticket to F5 support, the ticket number is C3810820, and they helped find the root cause.
I hope the official document could add a hint so that others can avoid this problem. Thanks.

Document Link:
[https://docs.nginx.com/nginx-ingress-controller/f5-ingresslink/](url)

KIC version: 2.0.3

The ConfigMap I used which follows the doc.
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  proxy-protocol: "True"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "10.244.20.0/24"
```

The Deployment I used which enables tls-passthrough
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
     #annotations:
       #prometheus.io/scrape: "true"
       #prometheus.io/port: "9113"
       #prometheus.io/scheme: http
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: private-registry.nginx.com/nginx-ic/nginx-plus-ingress:2.0.3
        imagePullPolicy: Never
        name: nginx-plus-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: dashboard
          containerPort: 8080
        - name: readiness-port
          containerPort: 8081
        - name: prometheus
          containerPort: 9113
        readinessProbe:
          httpGet:
            path: /nginx-ready
            port: readiness-port
          periodSeconds: 1
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 #nginx
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-plus
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
         #- -enable-app-protect
         #- -v=3 # Enables extensive logging. Useful for troubleshooting.
          - -report-ingress-status
          - -ingresslink=nginx-ingress
         #- -external-service=nginx-ingress
         #- -enable-prometheus-metrics
          - -global-configuration=$(POD_NAMESPACE)/nginx-configuration
          - -enable-tls-passthrough
          - -nginx-status-allow-cidrs=10.0.0.0/8
          - -ingress-class=nginx-plus
          - -enable-preview-policies
```

Aha! Link: https://nginx.aha.io/features/IC-474
