### ISSUE TITLE
LetsEncrypt support

### ISSUE THREAD

**Issue by xrl** [nginxinc/kubernetes-ingress#275]
Is there a recommended way to support fetching and using LetsEncrypt certificates? I'd like to be able to add "foo.bar.com" and have something in the ingress controller got out to fetch the certificate. The problem will be that there's a stampede of uncoordinated nginx pods trying to get their own copy of a certificate.

Has anyone solved this problem?

**Comment by pleshakov** [comment]
@xrl there are projects like https://github.com/jetstack/kube-lego that can fetch LetsEncypt certificate. That project is not compatible with this Ingress controller.

**Comment by mastrauckas** [comment]
I used [cert-manager](https://github.com/jetstack/cert-manager) because [kube-lego](https://github.com/jetstack/kube-lego) is in maintenance mode.

**Comment by dealproc** [comment]
@mastrauckas - do you have an example yml file on how you configured this ingress controller, as well as an example on how you authored one of your services to use the letsencrypt certificate?  i've used annotations in the past, and am unsure if this ingress uses them (e.g. `kubernetes.io/ingress.class:`; `kubernetes.io/tls-acme:`

as an example of what I have:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: [name-of-ingress]
  namespace: [namespace-of-pods]
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
spec:
  tls:
  - hosts: 
    - {host}.{domain}.{tld}
    secretName: [secret-name stored within k8s]
  rules:
  - host: {host}.{domain}.{tld}
    http:
      paths:
      - backend:
          serviceName: [name-of-service]
          servicePort: 5000
        path: /
```

as a "post" question to this... can you define an entry within `spec:` to configure tcp streams within a spec similar to this?
