### ISSUE TITLE
Expose mongo/redis url

### ISSUE THREAD

**Issue by sonnd08** [nginxinc/kubernetes-ingress#2750]
**Describe the bug**
Hi, I'm trying to expose a public domain for my MongoDB/Redis with VirtualServer but it does not work.
Could you guys take a look to see what is problem here?

```
mongodb://user:password@my-mongo-svc:27017/testdb => this work (internally)

mongodb://user:password@mongo.mydomain.com:80/testdb => Invalid message size: 1347703880, max allowed: 67108864

```

**To Reproduce**
```
apiVersion: v1
kind: Service
metadata:
  name: my-mongo-svc
  namespace: default
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: my-mongo

---

apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: mongo-domain
spec:
  host: mongo.mydomain.com
  upstreams:
    - name: my-mongo
      service: my-mongo-svc
      port: 27017
  routes:
    - path: /
      action:
        pass: my-mongo
```

Update:
May be related to this?
https://stackoverflow.com/questions/31853755/how-to-setup-mongodb-behind-nginx-reverse-proxy
