### ISSUE TITLE
could not build map_hash, you should increase map_hash_bucket_size: 64

### ISSUE THREAD

**Issue by ElvenSpellmaker** [nginxinc/kubernetes-ingress#2802]
**Describe the bug**
When enabling TLS Passthrough with `--enable-tls-passthrough` we end up with the following error one for each resource:
```
E0629 10:16:09.476844       1 controller.go:638] Error updating endpoints for [foo]: Error reloading NGINX when updating endpoints: nginx reload failed: Command /usr/sbin/nginx -s reload -e stderr stdout: ""
stderr: "2022/06/29 10:16:09 [emerg] 96#96: could not build map_hash, you should increase map_hash_bucket_size: 64\n"
```

We've tried upping the bucket size in the config by using the configmap:
```
  config:
    entries:
      http-snippets: |
        map_hash_bucket_size 1024;
```

We also tried to up the maximum hash size too just in case the pod thought the max was 64, but it always spits out the same error message.

We can see the changes taking effect in the `/etc/nginx/nginx.conf` but they're never applied as the server fails to `reload` like the above lines for a VirtualServer:
![image](https://user-images.githubusercontent.com/2286713/176454404-6f902228-13a7-434d-98be-c11953aa19e4.png)

**To Reproduce**
Enable TLS passthrough:
```yml
controller:
...
  enableTLSPassthrough: true
````

**Expected behavior**
Not to crash, or allow us to up the map size.

**Your environment**
* Version of the Ingress Controller:  0.13.0 helm chart
* Version of Kubernetes: 1.22
* Kubernetes platform: EKS (AWS)
* Using: NGINX

**Additional context**
My belief currently is that the controller is loading `VirtualServer` and `TransportServer` resources _before_ loading the `ConfigMap` (as is indicated by the logs), and so by the time it comes to reload for the config the map size is full and so fails to reload with  our increased config map_hash size of 1024.

The configmap should be the first thing loaded so root settings take effect before other resources are loaded or a way of overriding params for _boot_ time should be available.

**Comment by jasonwilliams14** [comment]
@ElvenSpellmaker hello there.
would it be possible for you to share one of your `resources` with us so we can review what you have configured?
Thanks

**Comment by ElvenSpellmaker** [comment]
Hey @jasonwilliams14, sure here's an example of one of the `VirtualServer`s we have for one component.

To give more context we have 78 `VirtualServer`s and 1 `TransportServer` (as a test for the pass-through we're trying to enable)

Each dev branch is a copy of each other effectively with any changes made on them and so each dev branch usually has 6 VSs in it.

(The vars get replaced at pipeline time using `a8m/envsubst`)

```yml
---
# defines ingress for both scim and http (directory)
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: pingdirectory
  namespace: ${NAMESPACE}
spec:
  ingressClassName: nginx
  host: ${DNS_NAME}
  tls:
    secret: ${TLS_WILDCARD_SECRET_NAME}
    redirect:
      enable: true
  server-snippets: |
    set $$hsts_header_content "";
    if ($$scheme = "https") {
      set $$hsts_header_content "max-age=${HSTS_MAX_AGE};";
    }
    add_header Strict-Transport-Security $$hsts_header_content;
  upstreams:
  - name: console
    service: pingdataconsole
    port: 443
  - name: pingdirectory
    service: pingdirectory
    port: 443
    tls:
      enable: true
  routes:
  - path: /console
    action:
      pass: console
  - path: /scim
    action:
      pass: pingdirectory
  - path: /directory
    action:
      pass: pingdirectory
```
