### ISSUE TITLE
VirtualServer proxy generates 405  - method not allowed

### ISSUE THREAD

**Issue by Nikolaj52** [nginxinc/kubernetes-ingress#2974]
When running VirtualServer with a proxy rewrite action - my calls to it generates a 405.
Calling the exact same container in Docker Desktop with the same call and method - but in localhost - runs smoothly.
Now looking into my IngressController Pod log gives me this:

xx.1xx.95.10 - - [25/Aug/2022:15:11:34 +0000] "POST /jsonhelper HTTP/1.1" 301 169 "-" "PostmanRuntime/7.29.2" "-"
xx.1xx.95.10 - - [25/Aug/2022:15:11:34 +0000] "GET /jsonhelper/ HTTP/1.1" 405 0 "https://api.example.com/jsonhelper" "PostmanRuntime/7.29.2" "-"

The first entry is a 301 which makes sense, but note, how the Http Method has been changed.
Below are my relevant yaml definitions:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: retail-vs
  namespace: backend
spec:
  host: api.example.com
  tls:
    secret: ssl-cert-production
  upstreams:
  - name: jsonhelper
    service: jsonhelper-svc
    port: 80
  routes:
  - path: /jsonhelper/
    action:
      proxy:
        upstream: jsonhelper
        rewritePath: /fix
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonhelper
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: jsonhelper
  template:
    metadata:
      labels:
        app: jsonhelper
    spec:
      containers:
      - name: jsonhelper
        image: jsonhelper:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 100Mi
            cpu: 70m
      nodeSelector:
        nodetype: apps
```

```
apiVersion: v1
kind: Service
metadata:
  name: jsonhelper-svc
spec:
  type: ClusterIP
  selector:
    app: jsonhelper
  ports:
    - port: 80
      targetPort: 80
      name: http
```
