### ISSUE TITLE
Controller support alternative configMaps

### ISSUE THREAD

**Issue by coolbry95** [nginxinc/kubernetes-ingress#2985]
**Is your feature request related to a problem? Please describe.**
It currently isn't possible to use a different configmap from the default created by the chart for the controller to use. We are using the nginx-ingress chart as a dependency and adding a template for a custom configmap. The custom configmap contains custom templates along with the config entries for the nginx-ingress chart.

The reason for having a custom configmap is that we only using the custom configmap conditionally. We have two deployment scenarios one we need to use a custom template and the other we don't.

**Describe the solution you'd like**
We would like to be able to specify the configmap for the controller to use.

```
nginx-ingress:
  controller:
    config:
      name: nginx-ingress
      # if customConfigName is set then the default config is ignored and the custom config is used
      customConfigName: custom-nginx-config
```

**Describe alternatives you've considered**
We can work around this in our service by setting the custom template as an entry. The issue with this is that we need to maintain the template out of band from the chart. The values file will also increase in size unreasonable due to the size of the templates. Updating the templates in the future is also more difficult because now it is embedded in YAML versus individual files for the template.

Another alternative is to vendor the nginx-ingress chart but that leads to diverging from upstream and maintaining the chart for ourselves. This is the current solution and updating the chart is difficult. It is hard to tell what we have changed versus what upstream has changed unless we annotate all changes.

```
nginx-ingress:
  controller:
    config:
      name: nginx-ingress
      entries:
        proxy-protocol: "False"
        main-template: |
           <template here>
        ingress-template: |
           <template here>
```
