### ISSUE TITLE
Server snippets don't apply to VirtualServer resources

### ISSUE THREAD

**Issue by 0m1xa** [nginxinc/kubernetes-ingress#2994]
**Describe the bug**
`server-snippets` with `VirtualServer` don't apply to the config file for the service.

**To Reproduce**
1. Deploy any application in your cluster
2. Apply `VirtualServer` configuration to expose the nginx (or any other app) adding `server-snippets` 
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: test-vs
  namespace: default
spec:
  host: test.localhost
  routes:
  - action:
      pass: app
    path: /
  server-snippets: |
    ssl_protocols TLSv1.2 TLSv1.3;
  tls:
    secret: nginx-tls
  upstreams:
  - name: app
    port: 80
    service: nginx
```
3. See the config file inside the ingress controller pod
There are no directives from the snippet

**Expected behavior**
The final config contains all server snippets and they work as expected

**Your environment**
* Version of the Ingress Controller - release version or a specific commit: v.2.3.0
* Version of Kubernetes: 1.21 
* Kubernetes platform (e.g. Mini-kube or GCP): EKS
* Using NGINX or NGINX Plus: NGINX

**Additional context**
Add any other context about the problem here—any log files you want to share.
