### ISSUE TITLE
Default backend:  defaultbackend-svc:443 (<error: endpoints "defaultbackend-svc" not found>)

### ISSUE THREAD

**Issue by Hadishamil** [nginxinc/kubernetes-ingress#2998]
Default backend configuration error!!  
issue: Ingress is not recognizing my externalName service (though i have added port to externalName service)
```
--------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: defaultbackend-svc
spec:
  type: ExternalName
  externalName: example.com
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: defaultbackend-ingress
spec:
  defaultBackend:
    service:
      name: defaultbackend-svc
      port:
        number: 443
-----------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------
```
