### ISSUE TITLE
Add lifecycle to controller container

### ISSUE THREAD

**Issue by coolbry95** [nginxinc/kubernetes-ingress#3006]
**Is your feature request related to a problem? Please describe.**
Add lifecycle configuration for the controller container. This allows preStop hooks to allow for draining of connections at the ingress.

**Describe the solution you'd like**
Add lifecycle configuration to the helm chart.

```
lifecycle:
   preStop:
      exec:
         command: ["/bin/sh","-c","sleep 10 && /usr/sbin/nginx -s reload"]
```

**Describe alternatives you've considered**
Related #267 

**Additional context**
