### ISSUE TITLE
[OpenShift] Annotation nginx.ingress.openshift.io/rewrite-target not recognized

### ISSUE THREAD

**Issue by devops-42** [nginxinc/kubernetes-ingress#307]
Hi,

I followed the steps to deploy the ingress router (nginx/nginx-ingress:1.2.0) in an OpenShift environment. I wrote an Ingress template to proxy two pods which have services run at port 8080 and 9090:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.baz
    http:
      paths:
      - path: /pod1
        backend:
          serviceName: pod1
          servicePort: 8080
      - path: /pod2
        backend:
          serviceName: pod2
          servicePort: 9090
```

When browsing to foo.bar.baz/pod1 the /pod1 URI part is not mapped to /. I looked into the generated config, no rewrite or different location rules where included. I already tried with different variations, such as:

```
   kubernetes.io/ingress.class: "nginx"
   ingress.kubernetes.io/rewrite-target: /
```

but with no luck.

Do you know whether OpenShift supports these annotations?

Thx for your help!
