### ISSUE TITLE
How to set the namespace of backend in one ingress?

### ISSUE THREAD

**Issue by kevin-jj** [nginxinc/kubernetes-ingress#317]
How to set the namespace of backend in one ingress?  The default http backend service was installed in kube-system namespace by GCP  while our other pods & services was in default namespace. Do I need to separate it into 2 ingress?

any idea? Thanks @pleshakov

**Comment by pleshakov** [comment]
@kevin-jj 
we don't support the default backend running in a different namespace. You need to deploy that backend in the same namespace.  To use the default backend, you must reference it in an Ingress resource:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
spec:
  backend:
    serviceName: default-backend
    servicePort: 80
  tls:
  - hosts:
    - cafe.example.com
    secretName: cafe-secret
  rules:
. . .
```
