### ISSUE TITLE
k8s ingress nginx 404 not-found

### ISSUE THREAD

**Issue by ducnpdev** [nginxinc/kubernetes-ingress#3195]
I have one bug when use nginx-ingress, open browser 404 not-found

yaml file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  type: ClusterIP #NodePort # NodePort ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    run: nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nginx
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx
            port:
              number: 80
```
kubectl get all -n develop
```
NAME                                         READY   STATUS    RESTARTS   AGE
pod/develop-nginx-ingress-86dbd9d4db-s5xjm   1/1     Running   0          4d11h
pod/nginx-78d94c8f7f-kd52g                   1/1     Running   0          21m

NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
service/develop-nginx-ingress   LoadBalancer   10.245.12.3     157.230.194.4   80:32041/TCP,443:31077/TCP   4d11h
service/nginx                   ClusterIP      10.245.187.54   <none>          80/TCP,443/TCP               26m

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/develop-nginx-ingress   1/1     1            1           4d11h
deployment.apps/nginx                   1/1     1            1           26m

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/develop-nginx-ingress-86dbd9d4db   1         1         1       4d11h
replicaset.apps/nginx-78d94c8f7f                   1         1         1       21m
replicaset.apps/nginx-8559b8674b                   0         0         0       26m
```

- kubectl describe ing -n develop nginx
```
Name:             nginx
Labels:           <none>
Namespace:        develop
Address:          157.230.194.4
Ingress Class:    nginx
Default backend:  <default>
Rules:
  Host        Path  Backends
  ----        ----  --------
  nginx       
              /   nginx:80 (<none>)
Annotations:  <none>
Events:
  Type    Reason          Age   From                      Message
  ----    ------          ----  ----                      -------
  Normal  AddedOrUpdated  27m   nginx-ingress-controller  Configuration for develop/nginx was added or updated
```

- kubectl describe svc -n develop nginx
```
Name:              nginx
Namespace:         develop
Labels:            run=nginx
Annotations:       <none>
Selector:          app=nginx
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.245.187.54
IPs:               10.245.187.54
Port:              http  80/TCP
TargetPort:        80/TCP
Endpoints:         10.244.0.5:80
Port:              https  443/TCP
TargetPort:        443/TCP
Endpoints:        10.244.0.5:443
Session Affinity:  None
Events:            <none>

```

- when open web: Ip-address of ingress: 157.230.194.4 -> 404 Not Found
- but: I use curl is OK
```
kubectl exec -it -n develop develop-nginx-ingress-86dbd9d4db-s5xjm -- curl -v -H "Host: nginx" localhost:80
```

**Comment by brianehlert** [comment]
You must provide a hostname. It must be an fqdn.
In the configuration and you must test with the same ( modification of local hosts might be necessary)
NGINX does hostname matching by default.

**Comment by ducnpdev** [comment]
I changed host ingress yaml from nginx to  nginx.example.com
and edit local in file /etc/hosts
But not work.

**Comment by freemankevin** [comment]
I have a same question here. 

this is IngressClass.
```shell
kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30680
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  selector:
    app: nginx-ingress
  clusterIP: xxxx
  clusterIPs:
    - xxxx
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
```

this is my service yml.
```yml
kind: Service
apiVersion: v1
metadata:
  name: sg-ui
  namespace: sg-dev
  labels:
    app: sg-ui
spec:
  ports:
    - name: tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: sg-ui
  clusterIP: xxxx
  clusterIPs:
    - xxxx
  type: ClusterIP
  sessionAffinity: None
```

this is my web app pod content and nginx.conf here.
```shell
/usr/share/nginx/html # ls -lh
total 8K
-rw-r--r--    1 root     root         497 Jan 25  2022 50x.html
drwxr-xr-x    5 root     root          85 Feb  9 10:16 gdassets
-rw-r--r--    1 root     root         615 Jan 25  2022 index.html
/usr/share/nginx/html # ls -lh gdassets/
total 76K
-rw-r--r--    1 root     root       66.1K Feb  9 10:07 favicon.ico
-rw-r--r--    1 root     root        6.7K Feb  9 10:07 index.html
drwxr-xr-x    3 root     root          57 Feb  9 10:09 onemap
drwxr-xr-x    7 root     root          83 Feb  9 10:07 static
drwxr-xr-x    3 root     root          57 Feb  9 10:09 system
/usr/share/nginx/html # cat /etc/nginx/conf.d/default.conf
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /gdassets {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /gdassets/index.html;
    }

    location = /basic_status {
        stub_status;
        access_log off;
    }
```


this is my ingress yml file.
```yml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: sg-dev-ingress
  namespace: sg-dev
spec:
  ingressClassName: nginx
  rules:
    - host: sg.dev.com
      http:
        paths:
          - path: /gdassets
            pathType: Prefix
            backend:
              serviceName: sg-ui
              servicePort: 80
```

this is my [uri:  http://NodeIP:30680/gdassets](http://NodeIP:30680/gdassets)

I want to access $uri or $uri/gdassets  through  ip:port . how should i  implement it ? i use ingress-nginx to implement it , and there seems to be no such problem.
