### ISSUE TITLE
How to setup ingress to serve static content on kubernetes?

### ISSUE THREAD

**Issue by kevin-jj** [nginxinc/kubernetes-ingress#323]
How to setup ingress to serve static content at my app? The following annotation does not work.  Since the Nginx ingress runs on a separate deployment with app pod,  it seems like it cloud not access static content in app pod.
@pleshakov 

annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/client-max-body-size: "2m"
    nginx.org/server-snippets: |
      location ~ ^/(assets)/{
        root /var/www/test/public;
        gzip_static on;
        expires max;
        add_header Cache-Control public;
      }

**Comment by isaachawley** [comment]
The Ingress Controller is not designed to serve static content. If you'd like to serve static content, consider having a separate Service for it.

See https://github.com/nginxinc/kubernetes-ingress/issues/257#issuecomment-402109791

**Comment by demidovsky** [comment]
I know that this is an old issue, but for some cases the answer on _"How to setup ingress to serve static content on kubernetes?"_ may be just setting **add-base-url: "true"** and **rewrite-target: /**, annotations,

e.g. 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: some.kind.of.hostname.co
    http: &rules
      paths:
      - path: /path/to
        backend:
          serviceName: some-website-serving-static
          servicePort: 80
      - path: /
        backend:
          serviceName: another-service
          servicePort: 80
```

Hope this helps someone.
