### ISSUE TITLE
ssl-services seems not working

### ISSUE THREAD

**Issue by bappr** [nginxinc/kubernetes-ingress#332]
**Describe the bug**
`ssl-services` does not enable `proxy_pass https://...` in the nginx conf.

**To Reproduce**
1. I have this ingress template:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: "test"
  labels:
    chart: test-0.1.0
    heritage: Tiller
    release: test
spec:
  rules:
  - host: test.kintohub.com
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: 443
        path: /
  tls:
  - hosts:
    - test.kintohub.com
    secretName: ssl-kintohub
```
2. When I push this template on K8S, the certs are mounted correctly in the nginx pod.
But I cannot reach `https://test.kintohub.com` -> Error 400 Bad Request
3. I look at `/etc/nginx/nginx.conf` and I can see that the proxy_pass is set to `http`, not to `https`.
Switching manually from `http` to `https` and reloading the nginx conf works.

**Expected behavior**
Annotation `nginx.org/ssl-services: "test"` should update my nginx conf and replace `proxy_pass http://test.kintohub.com` with `proxy_pass https://test.kintohub.com`

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
`gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.15`
* Version of Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes platform (e.g. Mini-kube or GCP)
GCP
* Using NGINX or NGINX Plus
NGINX
