### ISSUE TITLE
Kubernetes Ingress Exact not prioritized over Prefix

### ISSUE THREAD

**Issue by JonasJes** [nginxinc/kubernetes-ingress#3357]
**Describe the bug**
In Kubernetes we need a new service to handle the root path, but but still a catch everything else on our current frontend.
But it looks like Exact is not prioritized over Prefix as the documentation say it should

> If two paths are still equally matched, precedence will be given to paths with an exact path type over prefix path type.

https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches

**To Reproduce**
1. Have a Kubernetes cluster
2. Have 2 pods and services running in the Kubernetes cluster
3. Deploy following yaml content
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: current-frontend
  labels:
    app: current-frontend
    tier: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - my.domain.com
      secretName: tls-secret
  rules:
    - host: my.domain.com
      http:
        paths:
          - backend:
              service:
                name: current-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-service
  labels:
    app: new-service
    tier: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - my.domain.com
    secretName: tls-secret
  rules:
  - host: my.domain.com
    http:
      paths:
      - backend:
          service:
            name: new-service
            port:
              number: 80
        path: /someendpoint
        pathType: ImplementationSpecific
      - backend:
          service:
            name: new-service
            port:
              number: 80
        path: /
        pathType: Exact
```
4. Go to my.domain.com/someendpoint se new-service being hit
   - Expected
5. Go to my.domain.com/somethingelse se current-frontend being hit
   - Expected
6. Go to my.domain.com/ se the current-frontend being hit
   - Expected new-service to be hit as it has `pathType: Exact`

**Expected behavior**
When 2 ingresses has a path with `/` it is expected that the ingress hits the service with `pathType: Exact` and not the service with  `pathType: Prefix`

**Your environment**
* Version of the Ingress Controller: k8s.gcr.io/ingress-nginx/controller:v1.1.1
* Version of Kubernetes: 1.23.8
* Kubernetes platform: Azure Kubernetes Service

**Additional context**
