### ISSUE TITLE
nginx-ingress routes traffic to not-ready pods

### ISSUE THREAD

**Issue by markjgardner** [nginxinc/kubernetes-ingress#3534]
**Describe the bug**
Ingress continues to route traffic to backend pods that are marked as not ready due to failing readinessProbe.

**To Reproduce**
* Install nginx-ingress chart on cluster:
``` helm install ingress nginx-ingress ```
* Deploy the following workload, service and ingress:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: aspnet
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    app: simple-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpleapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: <ingress-ip>.nip.io
    http:
      paths:
      - backend:
          service:
            name: simple-app
            port:
              number: 80
        path: /
        pathType: Prefix
```
* exec into the three pods and ```touch /tmp/healthy``` to pass the readinessProbe
* Validate the ingress routes traffic to each pod by refreshing the page a few times
* exec into on of the pods and ```rm /tmp/healthy``` and observe pod becomes not ready
* Describe the service and note the pod has been removed from the backends
* Refresh page (clear cache or use new session just to be safe) and observe requests are still routing to not-ready pod

**Expected behavior**
Requests should never route to the not-ready pod.

**Your environment**
* Version of the Ingress Controller == 3.0.1
* Version of Kubernetes == 1.25.5
* Kubernetes platform == AKS
* Using NGINX

**Additional context**
This behavior is not present in https://kubernetes.github.io/ingress-nginx  (requests are never routed to not-ready pods)
