### ISSUE TITLE
404 is displayed after deploying with ingress

### ISSUE THREAD

**Issue by freemankevin** [nginxinc/kubernetes-ingress#3545]
> version
- nginx/nginx-ingress:2.4.2

> deploy
- manifests 

> env
- k8s-v1.20.6，centos7.9

> my service

this is IngressClass.
```shell
kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30680
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  selector:
    app: nginx-ingress
  clusterIP: xxxx
  clusterIPs:
    - xxxx
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
```

this is my service yml.
```yml
kind: Service
apiVersion: v1
metadata:
  name: sg-ui
  namespace: sg-dev
  labels:
    app: sg-ui
spec:
  ports:
    - name: tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: sg-ui
  clusterIP: xxxx
  clusterIPs:
    - xxxx
  type: ClusterIP
  sessionAffinity: None
```

this is my web app pod content and nginx.conf here.
```shell
/usr/share/nginx/html # ls -lh
total 8K
-rw-r--r--    1 root     root         497 Jan 25  2022 50x.html
drwxr-xr-x    5 root     root          85 Feb  9 10:16 gdassets
-rw-r--r--    1 root     root         615 Jan 25  2022 index.html
/usr/share/nginx/html # ls -lh gdassets/
total 76K
-rw-r--r--    1 root     root       66.1K Feb  9 10:07 favicon.ico
-rw-r--r--    1 root     root        6.7K Feb  9 10:07 index.html
drwxr-xr-x    3 root     root          57 Feb  9 10:09 onemap
drwxr-xr-x    7 root     root          83 Feb  9 10:07 static
drwxr-xr-x    3 root     root          57 Feb  9 10:09 system
/usr/share/nginx/html # cat /etc/nginx/conf.d/default.conf
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location /gdassets {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /gdassets/index.html;
    }

    location = /basic_status {
        stub_status;
        access_log off;
    }
```

this is my ingress yml file.
```yml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: sg-dev-ingress
  namespace: sg-dev
spec:
  ingressClassName: nginx
  rules:
    - host: sg.dev.com
      http:
        paths:
          - path: /gdassets
            pathType: Prefix
            backend:
              serviceName: sg-ui
              servicePort: 80
```

this is my [uri:  http://NodeIP:30680/gdassets](http://NodeIP:30680/gdassets)

I want to access $uri or $uri/gdassets  through  ip:port . how should i  implement it ? i use ingress-nginx to implement it , and there seems to be no such problem.
