### ISSUE TITLE
Ingress .spec.defaultBackend doesn't work

### ISSUE THREAD

**Issue by kytart** [nginxinc/kubernetes-ingress#3582]
When I define Ingress with `.spec.defaultBackend`, it gets ignored. I keep getting generic Nginx 404 page for all URLs that don't have defined rules. According to [Kubernetes specification](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend) this should be supported.

Example Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
spec:
  defaultBackend:
    service:
      name: default-svc
      port:
        number: 80
  rules:
    - host: example.dev
      http:
        paths:
          - backend:
              service:
                name: example-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
```

If I open `example.dev`, it will send the request to `example-svc`. But if I open `wrong.dev`, it should send the request to `default-svc` but instead I get a generic Nginx 404 page.

**My environment**:
* Version of the Ingress Controller - 3.0.2 (Helm chart 0.16.2)
* Version of Kubernetes - 1.22
* Kubernetes platform - AWS EKS
* Using NGINX
