### ISSUE TITLE
Not getting http_x_forwarded_proto

### ISSUE THREAD

**Issue by ishaankalra16** [nginxinc/kubernetes-ingress#3635]
I have deployed the nginx ingress controller using the helm chart [nginx-ingress](https://artifacthub.io/packages/helm/nginx/nginx-ingress). Everything seems to be working fine, except the https redirect. Even of adding the annotation `nginx.org/redirect-to-https: true`, it does add the 301 redirect rule based on the value of the `http_x_forwarded_proto`. However, still the redirect seemed to be not working as expected. On further debugging the issue, by sending the requested headers to my application, I was getting empty value for the variable `http_x_forwarded_proto`. This was further confirmed by the logs of the controller. 
These are the helm values by which I have deployed the helm chart onto the Amzon EKS cluster currently running on version 1.25. Helm chart version is 0.16.2.
```
controller:
  enableSnippets: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-eip-allocations: xxxxxxxxxxxxxxxxxxxxxxx
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      service.beta.kubernetes.io/aws-load-balancer-subnets: xxxxxxxxxxxxxxxxxxxxxxxxxx
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    config:
      entries:
        compute-full-forwarded-for: true
        proxy-protocol: true
        real-ip-header: proxy_protocol
        set-real-ip-from: 0.0.0.0/0
        use-forwarded-headers: true
    httpsPort:
      targetPort: 80
```
