### ISSUE TITLE
HostPort in controller container daemonset with HostNetwork: false

### ISSUE THREAD

**Issue by EutiziStefano** [nginxinc/kubernetes-ingress#3655]
**Describe the bug**
The chart inserts "HostPort" in the daemonset also when "HostNetwork" is setted to "false"

**To Reproduce**
1.Install the chart with controller.hostNetwork: false (default)
2. Open the nginx controller daemonset and check:
    ports:
        - name: http
          containerPort: 80
          **hostPort: 80**
        - name: https
          containerPort: 443
          **hostPort: 443**

**Expected behavior**
Setting the controller.hostNetwork: false should not set hostPort in the deployment or daemonset.

**Your environment**
* Helm chart 0.12.1 - nginx 1.21.6   and   Helm chart 0.15.2 - nginx 1.23.2
* Version of Kubernetes 1.23.7
* Kubernetes platform - Kubernetes
* Using NGINX

**Additional context**
This can be fixed in helm chart, inserting in templates/controller-daemonset.yaml a if statement around the two host port:

**AS-IS:**
```
hostNetwork: {{ .Values.controller.hostNetwork }}
      dnsPolicy: {{ .Values.controller.dnsPolicy }}
      containers:
      - name: {{ include "nginx-ingress.name" . }}
        image: {{ include "nginx-ingress.image" . }}
        imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
{{- if .Values.controller.lifecycle }}
        lifecycle:
{{ toYaml .Values.controller.lifecycle | indent 10 }}
{{- end }}
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
```

**TO-BE:**
```
hostNetwork: {{ .Values.controller.hostNetwork }}
      dnsPolicy: {{ .Values.controller.dnsPolicy }}
      containers:
      - name: {{ include "nginx-ingress.name" . }}
        image: {{ include "nginx-ingress.image" . }}
        imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
{{- if .Values.controller.lifecycle }}
        lifecycle:
{{ toYaml .Values.controller.lifecycle | indent 10 }}
{{- end }}
        ports:
        - name: http
          containerPort: 80
{{- if .Values.controller.hostNetwork }}
          hostPort: 80
{{- end }}
        - name: https
          containerPort: 443
{{- if .Values.controller.hostNetwork }}
          hostPort: 443
{{- end }}
```

Thanks
S.
