### ISSUE TITLE
AKS LoadBalancer IP address changed when upgrading from v2 to v3

### ISSUE THREAD

**Issue by jannekem** [nginxinc/kubernetes-ingress#3752]
**Describe the bug**
After upgrading NGINX Ingress Controller my services became unavailable as the LoadBalancer IP address changed on an Azure AKS cluster.

I couldn't find any mention about such a possible side effect from the release notes.

**To Reproduce**
I have reproduced this on two AKS clusters. My services are exposed with `VirtualServers`. After I run `helm upgrade` the VirtualServer `status.externalEndpoints` still shows the old IP address but the service is not reachable anymore. The new IP address can be found from Azure Portal in the "Services and ingresses" page of the AKS cluster instead.

Here are the versions I'm upgrading from/to.

```
$ helm history ingress-controller
REVISION        UPDATED                         STATUS          CHART                   APP VERSION     DESCRIPTION     
5               Fri Nov 18 09:10:41 2022        superseded      nginx-ingress-0.15.1    2.4.1           Upgrade complete
6               Wed Apr 12 09:38:06 2023        deployed        nginx-ingress-0.17.0    3.1.0           Upgrade complete
```

**Expected behavior**
The IP addresses should not change during an upgrade.

**Your environment**
* Version of the Ingress Controller 3.1.0
* Version of Kubernetes 1.25.5
* Kubernetes platform AKS
* Using NGINX

**Additional context**
Helm settings:

```yaml
controller:
  enableSnippets: true
  enableCustomResources: true
  enableCertManager: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1Gi

```
