### ISSUE TITLE
location URI is passed to proxy_pass

### ISSUE THREAD

**Issue by sjenning** [nginxinc/kubernetes-ingress#39]
So I have an ingress path that looks like this:

```yaml
      paths:
      - path: /blog/
        backend:
          serviceName: wordpress
          servicePort: 80
```

The wordpress service connects to a pod running the docker hub wordpress image.  It serves content out of the root URI (/).  However the config sends requests for /blog/ to the backend pod.

Adding a forward slash to the end of the proxy_pass line in the tmpl file and rebuilding the container works for me, but I'll like to either 1) change that upstream in this repo or 2) find an alternate way to do that with the current image.

**Comment by pleshakov** [comment]
We can add a feature that will let you do that.  We can use annotations for that. Something like this:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    nginx.org/usptream-rewrite: "tea-svc /"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /blog
        backend:
          serviceName: tea-svc
          servicePort: 80
```
A request to `cafe.example.com/blog/something` will be send to `tea-svc/something`

There are problems that might appear though. Some applications may return pages with links with absolute URLs. This will cause problems. To fix that, we need to tell NGINX to change a page  before returning it to a client to fix broken links. It can be done with http://nginx.org/en/docs/http/ngx_http_sub_module.html It is difficult though to come up with a nice way describe those rules in annotations in case such a problem appears.
