### ISSUE TITLE
ConfigMap snippets being ignored by the nginx.conf

### ISSUE THREAD

**Issue by declanmc** [nginxinc/kubernetes-ingress#395]
**Describe the bug**
I have a kubernetes cluster, where I have deployed an nginx ingress controller using the helm nginx-ingress chart.

I need to add some custom config to the nginx.conf file that is generated in the nginx-controller-pod, and I am seeing an issue where if I add a one line option such as `proxy-buffer-size: "512k"` I can see this reflected in the nginx.conf file and everything works as expected.

However, if I attempt to add a snippet to accomplish the same thing:

```
location-snippet: |
  proxy_buffer_size "512k";
```
It is as though this is ignored by the nginx.conf file and the `proxy_buffer_size` setting remains at it's default value

**To Reproduce**
1. Deploy [stable/ngnix-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress) to Kuberenetes cluster
2. Apply following Ingress.yaml file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true" 
    ingress.kubernetes.io/secure-backends: "true"    
    ingress.kubernetes.io/force-ssl-redirect: "true"

    nginx.org/location-snippets: |
       proxy_buffer_size 512k;     --This does not update the nginx.conf
spec:
  tls:
  - hosts:
    - my.app.co.uk
    secretName: tls-secret

  rules:
  - host: my.app.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: myappweb-service
          servicePort: 80
```
3. Apply following ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.28.3
    component: controller
    heritage: Tiller
    release: nginx-ingress
  name: nginx-ingress-controller
  namespace: default
data:
  proxy-buffer-size: "512k" -- this works and updates the nginx.conf

  location-snippet: |
    proxy_buffers 4 512k; -- this does not update the nginx.conf

  server-snippet: |       -- this does not update the nginx.conf
    location /messagehub {
      proxy_set_header Upgrade $http_upgrade;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header Connection "upgrade";
      proxy_cache_bypass $http_upgrade;
   }
```

**Expected behavior**
The nginx.conf file running in the nginx-ingress-controller pod on the cluster to be updated with the values in the location-snippet and server-snippet nodes

**Your environment**
* Version of the Ingress Controller - release version or a specific commit:
`helm chart: stable/nginx-ingress  commit hash: f0f62f3`
* Version of Kubernetes:
```
clientVersion:
  buildDate: 2018-09-09T18:02:47Z
  compiler: gc
  gitCommit: a4529464e4629c21224b3d52edfe0ea91b072862
  gitTreeState: clean
  gitVersion: v1.11.3
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-06-29T01:07:01Z
  compiler: gc
  gitCommit: 57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a
  gitTreeState: clean
  gitVersion: v1.9.9
  goVersion: go1.9.3
  major: "1"
  minor: "9"
  platform: linux/amd64
```
* Kubernetes platform: AKS
* Using NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.
