### ISSUE TITLE
Azure CDN 502 Bad gateway after upgrading from 3.0.2 to 3.1.0 or later

### ISSUE THREAD

**Issue by rebepoi** [nginxinc/kubernetes-ingress#4125]
**Describe the bug**
After upgrading to version 3.1.0, our Azure CDN (Premium Verizon) endpoint started to give 502 bad gateway errors. Accessing the origin directly with browser was still working normally. After rolling back to 3.0.2 the CDN started to work again.

**To Reproduce**
1. Deploy kubernetes ingress >= 3.1.0
2. Configure VirtualServer for any application (we reproduced this with SonarQube which runs in our test cluster)
3. Configure Azure CDN with the Premium Verizon pricing tier
4. Create CDN endpoint which uses the VirtualServer host as the origin hostname
5. Accessing through the CDN endpoint hostname will fail with 502

**Expected behavior**
Site should work through CDN

**Your environment**
* Version of the Ingress Controller - 3.1.0 or greater
* Version of Kubernetes 1.26.3
* Kubernetes platform AKS
* Using NGINX

**Additional context**
Helm settings
``` YAML
controller:
  enableSnippets: true
  enableCustomResources: true
  enableCertManager: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1Gi
# override the default service name to avoid changing the IP address of the LoadBalancer
serviceNameOverride: ingress-controller-nginx-ingress
```
VirtualServer and VirtualServerRoute
``` YAML
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: sonarqube
  namespace: ingress
spec:
  host: sonarqube.example.com
  routes:
  - path: /
    route: sonarqube/sonarqube
  tls:
    redirect:
      enable: true
    secret: sonarqube-cert
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  host: sonarqube.example.com
  subroutes:
  - action:
      pass: sonarqube
    path: /
  upstreams:
  - name: sonarqube
    port: 9000
    service: sonarqube-sonarqube
    client-max-body-size: 50m
```
