### ISSUE TITLE
Nginx Ingress Controller with ArgoCD - UI is not responsive

### ISSUE THREAD

**Issue by nhat-tong** [nginxinc/kubernetes-ingress#4132]
**Describe the bug**
We would like to follow GitOps pattern for our deployment in Google Kubernetes Engine (GKE). So, we want to use ArgoCD as our deployment tool. When ArgoCD is installed within the cluster with this implementation of nginx ingress controller, it didn't work correctly. A hard refresh (F5) is needed once ArgoCD application is created/deleted/synchronized in order to refresh ArgoCD UI.
If we switch to another implementation of nginx ingress controller (https://kubernetes.github.io/ingress-nginx), the ArgoCD's refresh worked perfectly!

**To Reproduce**
1. Install nginx ingress controller using Helm: helm install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress --version 0.18.0 -n nginx-ingress
2. Install ArgoCD using Helm: helm install argocd argo/argo-cd --version 5.41.1 -n argocd and then enable insecure flag (server.insecure: "true")  in the configmap "argocd-cmd-params-cm" in order to terminate TLS traffic at nginx ingress controller
3. Create argocd ingress as the following :

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  ingressClassName: "nginx"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
    host: [MY-DOMAIN]
  tls:
  - hosts:
    - [MY-DOMAIN]
    secretName: argocd-tls-secret
```

**Expected behavior**
NGINX should work properly with ArgoCD when application is created/synchronized/deleted. No hard refresh (F5) is required.

**Your environment**
* Version of the Ingress Controller - Chart version 0.18.0
* Version of Kubernetes: 1.26.5-gke.1200
* Kubernetes platform: GCP
* Using NGINX or NGINX Plus: NGINX

**Additional context**
We already tested another implementation of nginx ingress controller (https://kubernetes.github.io/ingress-nginx). It worked really well. However, we prefer this implementation because we intend to use NGINX Plus in the future for advanced functionalities.

Do we missed something ? Thanks
