### ISSUE TITLE
Virtual server with type grpc not working with nginx ingress 0.17.1 version

### ISSUE THREAD

**Issue by nandiniraj** [nginxinc/kubernetes-ingress#4139]
**Describe the bug**
Trying to use virtual server for grpc connections with nginx ingress controller. 
Getting following error:
`Failed to list methods for service "com.akamai.plx.dart.trustblock.v1.TrustBlockService": rpc error: code = Internal desc = unexpected HTTP status code received from server: 400 (Bad Request); transport: received unexpected content-type "text/html"`

From nginx ingress controller logs 
`172.19.73.229 - - [20/Jul/2023:14:06:07 +0000] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2.0" 400 215 "-" "grpcurl/1.8.7 grpc-go/1.48.0" "-"`

**To Reproduce**
1. Deploy backend spring boot application with grpc server with virtual server and service yaml as shown below.
2. Try listing services using any grpc client. For example, grpcurl 
3. Check nginx logs 

**Expected behavior**

**Your environment**
* Version of the Nginx Ingress - 0.17.1
* Version of Kubernetes - 3.1.1
* Using NGINX or NGINX Plus  -  NGINX

From nginx ingress controller logs 
172.19.73.229 - - [20/Jul/2023:14:06:07 +0000] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2.0" 400 215 "-" "grpcurl/1.8.7 grpc-go/1.48.0" "-"

NGINX Ingress Controller with Http2 enabled:

```
kubectl describe configmap spock-system-nginx-ingress -n spock-system
Name:         spock-system-nginx-ingress
Namespace:    spock-system
Labels:       app.kubernetes.io/instance=spock-system.poc
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=nginx-ingress
              app.kubernetes.io/version=3.1.1
              helm.sh/chart=nginx-ingress-0.17.1
Annotations:  <none>

Data
====
map-hash-bucket-size:
----
512
http2:
----
true

BinaryData
====

**Additional context**
virtualserver.yaml

apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: test-api-vs
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{.Values.service.name }}
spec:
  host: {{.Values.subdomainName }}.{{ .Values.global.rootDomainName }}
  ingressClassName: spock-nginx
  tls:
    secret: test-tls-spock
  policies:
    - name: test-api-ingress-mtls-policy
  upstreams:
  - name: test-api-grpc-upstream-vs1
    service: {{ .Values.service.name }}
    port: {{ .Values.service.grpcPort }}
    type: grpc
  - name: {{ .Values.deployment.name }}
    service: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    client-max-body-size : {{ .Values.service.clientMaxBodySize | quote }}
  - name: test-api-prometheus
    service: {{ .Values.service.name }}
    port: {{ .Values.service.managementPort }}

  routes:
  - path: /com.test.plx.dart.trustblock.v1.TrustBlockService
    action:
      pass: test-api-grpc-upstream-vs1
  - path: /grpc.health.v1.Health
    action:
      pass: test-api-grpc-upstream-vs1
  - path: /grpc.reflection.v1alpha.ServerReflection
    action:
      pass: test-api-grpc-upstream-vs1
  - path: /test-api
    location-snippets: |
      proxy_set_header        X-SSL-Client-S-Dn $ssl_client_s_dn;
    action:
      pass: {{ .Values.deployment.name }}
  - path: /actuator
    action:
      pass: test-api-prometheus


service.yaml 

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{.Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.name }}
  ports:
    - name: {{ .Values.deployment.name }}
      protocol: {{ .Values.service.protocol }}
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
    - name: {{ .Values.service.managementPortName }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
    - name: {{ .Values.service.grpcPortName }}
      protocol: {{ .Values.service.protocol }}
      port: {{.Values.service.grpcPort}}
      targetPort: {{.Values.service.grpcPort}}


values.yaml 

# Default values for test-api
# This is a YAML-formatted file.

namespace: dart-api
localDevelopment: false
replicaCount: 2
subdomainName: test-api


serviceAccount:
  name: vault-sa

service:
    name: test-api
    type: ClusterIP
    protocol: TCP
    managementPort: 9090
    managementPortName: test-api-stats
    managementPath: /actuator/prometheus
    managementScrapeInterval: 60s
    clientMaxBodySize: 50m
    port: 8081
    targetPort: 8081
    grpcPort: 8956
    grpcPortName: test-api-grpc


deployment:
  name: test-api
  label: test-api

```
