### ISSUE TITLE
Adding multiple server-snippet

### ISSUE THREAD

**Issue by achandak123** [nginxinc/kubernetes-ingress#414]
**Describe the bug**
Unable to add multiple server-snippet, is it not supported??

**To Reproduce**
Here are the config files

**deployment file**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx/nginx-ingress:1.2.0
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-ingress-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
         #- -v=3 # Enables extensive logging. Useful for trooublshooting.
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/custom-snippets/
      volumes:
      - name: config-volume
        configMap:
          name: cors-config
```

Service file

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <aws ssl arn>
    #    Unfortunately, we cant use ACM certs from another account:(https://forums.aws.amazon.com/thread.jspa?threadID=231116)
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 80
    name: https
  selector:
    app: nginx-ingress

```

ConfigMap

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-config
  namespace: nginx-ingress
data:
  proxy-connect-timeout:  "3600s"
  proxy-read-timeout: "3600s"
  redirect-to-https: "True"
  ```
  
Ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #enable-cors is not supported (https://github.com/nginxinc/kubernetes-ingress/issues/121)
    nginx.org/location-snippets: "include /etc/nginx/custom-snippets/cors.conf;"
    nginx.org/server-snippets: |
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    nginx.org/server-tokens: "False"

spec:
  rules:
  - host: {HOST}
    http:
      paths:
      - path: /v1/blah/
        backend:
          serviceName: blah
          servicePort: 1234

```
See the following in the nginx pod (at conf.d/nginx-ingress-nginx-ingress.conf)

```

server {


	listen 80;






	server_tokens off;

	server_name blah;




	if ($http_x_forwarded_proto = 'http') {
		return 301 https://$host$request_uri;
	}

	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;


	
```

Dont see the following config

```
add_header X-Frame-Options "SAMEORIGIN" always;
```

**Your environment**
* Version of the Ingress Controller - 

1.2.0

* Version of Kubernetes

Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"

* Kubernetes platform (e.g. Mini-kube or GCP)
AWS

* Using NGINX or NGINX Plus

NGINX

**Expected behavior**
Expected to see **strict-transport-security** header in the response.

**Additional context**
Add any other context about the problem here. Any log files you want to share.
