### ISSUE TITLE
target-rewrite issue for sonarqube ingress 

### ISSUE THREAD

**Issue by milesjoe09** [nginxinc/kubernetes-ingress#4183]
**The Issue**
Hi,
I am deploying Sonarqube onto an AKS cluster using the Helm chart
I am using the kubernetes ingress-nginx controller on the cluster

if i deploy everything with a standard ingress just on ‘/’ of my host, it appears to all work fine.
if i deploy the ingress using the target-rewrite, when i browse to sonarqube it just sits on a loading page. because gets for things inside the app are failing.... there must me either missing config for the ingress (that i cant find).. or something is wrong with the target-rewrite mechanism.

the ingress controller logs show:
[04/Aug/2023:12:09:45 +0000] **“GET /api/features/list HTTP/2.0” 404 548 “https:/myapp.co.uk/sonarqube/”** “Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36” 32 0.001 [upstream-default-backend]  127.0.0.1:8181 548 0.001 404 7bd950927105823607011c5f5c307648

**Config**
here is my ingress config:
```
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - name: myapp.co.uk
      path: /sonarqube(/|$)(.*)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/protocol: http
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
```

**Expected behavior**
when i browse to myapp.co.uk/sonarqube i would expect the app to work as all pods are running fine on the cluster, and if i change the ingress to just be on '/' of the host, by changing 'path:' to '/', and removing the target-rewrite annotation, everything works fine. 

**Environment**
- Version of the Ingress Controller - v1.8.1
- Version of Kubernetes - v1.25.6
- Kubernetes platform - AKS
- Using NGINX
