### ISSUE TITLE
Unable to attach security groups with NLB

### ISSUE THREAD

**Issue by bittracer** [nginxinc/kubernetes-ingress#4249]
**Describe the bug**
I am trying to attach the security group to the internet facing nginx ingress controller NLB. But the following annotations does not seem to work.

```
controller:
 service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-111jhgj"  # comma separated to add multiple
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-111jhgj"  # comma separated to add multiple
```

Instead of allowing everyone (0.0.0.0) to access the NLB endpoint, I need this to restrict the traffic to certain IP addresses.

**Expected behavior**

After attaching the security group, the NLB endpoint should be restricted to certain IP's. 

**Your environment**

- Version of the Ingress Controller - 3.2.0 
- Version of Kubernetes - 0.18.0
- Kubernetes platform - AWS
- Using NGINX or NGINX Plus - NGINX
