### ISSUE TITLE
Pass query strings to backend service

### ISSUE THREAD

**Issue by efowel** [nginxinc/kubernetes-ingress#428]
Hi, i would like to know how to pass the query string to a backend service?
Below is a path base ingress rules which will redirect to our "traffic-manager" app nothing match the rules.
But we want to achieve to pass the "path query string" instead of just going to the home page. Can someone help? thanks!

ingress sample

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-dev
          servicePort: http
      - path: /coffee
        backend:
          serviceName: coffee-uat
          servicePort: http
      - path: /.*
        backend:
          serviceName: traffic-manager
          servicePort: http
```
we are using
```image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.12.0```
