### ISSUE TITLE
VirtualServer.tls.redirect.enabled blocks cert-manager ACME validation on new virtualservers

### ISSUE THREAD

**Issue by Tombar** [nginxinc/kubernetes-ingress#4283]
**Describe the bug**
ACME bot for lets encrypt is unable to access the cert-manager ingress upstream service (to validate and issue a cert) when a virtual server is created with tls.redirect.enabled true 

**To Reproduce**

Running nginx ingress 0.17.1 in a k8s cluster, installed from official helm chart with value `enableCertManager: true`

1. Create a new virtual server 
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cert-test
spec:
  host: cert-test.example.org
  routes:
  - action:
      redirect:
        code: 301
        url: https://google.com
    path: /
    route: ""
  tls:
    redirect:
      basedOn: ""
      enable: true
    secret: cert-test.example-tls
    cert-manager:
      cluster-issuer: letsencrypt-production
```

2. see in the logs, how acme bot gets redirect from HTTP to HTTPS instead of being able to fetch /.well-known/acme-challenge/xxxxxYYYYZZZzzz

**Expected behavior**

acme bot is able to access the HTTP upstream from cert-manager at /.well-known/acme-challenge/xxxxxYYYYZZZzzz to issue an valid SSL cert that's later used by the virtualserver for SSL 

**Your environment**

- Version of the Ingress Controller  0.17.1
- Version of Kubernetes 1.23 
- Kubernetes platform EKS
- Using NGINX Plus 

**Additional context**
Add any other context about the problem here. Any log files you want to share.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-plus
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
  labels:
    acme.cert-manager.io/http-domain: "1234"
    acme.cert-manager.io/http-token: "1234"
    acme.cert-manager.io/http01-solver: "true"
  name: cm-acme-http-solver-9qh8f
  namespace: infra
  ownerReferences:
  - apiVersion: acme.cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Challenge
    name: cert-test.example.org-tls-XXX-YYY-AAA-BBB
spec:
  rules:
  - host: cert-test.example.org
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-xvf66
            port:
              number: 8089
        path: /.well-known/acme-challenge/xxxxxYYYYZZZzzz
        pathType: ImplementationSpecific
```
