### ISSUE TITLE
Does the upstream support proxy request to a long domain（not a service name）

### ISSUE THREAD

**Issue by xuziheng1002** [nginxinc/kubernetes-ingress#4368]
upstreams:
  - name: tea
    service: tea-svc.example.com
    port: 80

do it works?
Alternatively, what configuration approach should I use to fulfill my requirements?

**Comment by xuziheng1002** [comment]
I did a test, that is not work...
So if I want proxy request to the backend-server and the server is out of the Kubernetes how cloud I do?

**Comment by brianehlert** [comment]
Please provide your YAML.

Is this what you are looking for?  https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/custom-resources/externalname-services

**Comment by xuziheng1002** [comment]
> Please provide your YAML.
> 
> Is this what you are looking for? https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/custom-resources/externalname-services


following is my yaml:

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
 name: cafe
spec:
  gunzip: true
  host: cafe.example.com
  upstreams:
  - name: gateway-server
     service: gateway-server.example.com
     port: 80
  routes:
  - path: /api
     action:
       pass: gateway-server
  - path: /
    action:
      return:
        code: 200
        type: text/html
        body: '<!DOCTYPE html>
          <html>
          <body>hello world</body>
          <div id="root" style="height: 100%;"></div>
          </body>
          </html>'
```

My intention is to proxy_pass requests matching /api to the server gateway-server.example.com.

The problem is `service: gateway-server.example.com` is not valid for `VirtualServer`.
