### ISSUE TITLE
Improve cert manager integration for VirtualServers when using HTTP01 challenges

### ISSUE THREAD

**Issue by svvac** [nginxinc/kubernetes-ingress#4408]
When using a fairly standard certificate request for a `VirtualServer` using a HTTP01 issuer :

```yaml
spec:
  host: app.example.com
  tls:
    cert-manager:
      cluster-issuer: my-http01-issuer
    redirect:
      enable: true
    secret: my-tls-secret
  # ...
```

The controller correctly creates the `Certificate` object, which in turns triggers issuance of a cert.

The issue is that this creates some kind of a deadlock situation : 

 - The controller considers the `VirtualServer` as invalid because the referenced secret does not exist yet
 - The `Challenge` created by cert-manager is stuck because the ACME challenge is not served by nginx, since the `VirtualServer` is invalid
 - The `Secret` is never created and `app.example.com` is never served.

The fix is easy enough. During the first deployment, wait for the `Certificate` object to be created and patch it to [issue a temporary certificate][0] : 

```yaml
metadata:
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
```

cert-manager will then create the `Secret` using a temporary self-signed cert, which will satisfy the `Challenge` self-check, which will allow the `Order` to complete, updating the `Secret` with the actual issued certificate.

I don't see any way to set this annotation on the generated `Certificate`, neither in the controller config nor in the `VirtualServer` itself.

### Possible solution

Make the controller set the annotation, either unconditionally, or by adding a boolean `spec.tls.cert-manager.issueTemporaryCertificate` flag.

[0]: https://cert-manager.io/docs/usage/certificate/#temporary-certificates-while-issuing
