### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by edingroot** [nginxinc/kubernetes-ingress#448]
Hi,

We just followed [this tutorial](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md) and created two services: `nginx1-7`, `nginx1-8`.
However, we found that the ingress nginx container is not forwarding the http request to the correct backend server (502 Bad Gateway is returned to the client).

This is the error log got from `docker  logs <container_id>`
```
2018/11/20 17:57:10 [error] 5999#5999: *85 connect() failed (111: Connection refused) while connecting to upstream, client: 10.244.0.1, server: cafe.example.c
om, request: "GET /tea HTTP/1.1", upstream: "http://127.0.0.1:8181/tea", host: "cafe.example.com"
```
The upstream ip and port is not same as the target service pods, it is still same as the default values at [nginx.go#L182](https://github.com/nginxinc/kubernetes-ingress/blob/10d27493e0671ac09cc234f38bad0e0af37c133f/internal/nginx/nginx.go#L182).

The following is my ingress config:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: nginx1-7
          servicePort: 80
  - host: n18.my.com
    http:
      paths:
      - path: /cat
        backend:
          serviceName: nginx1-8
          servicePort: 80
```

Could you please help us to figure out?
