### ISSUE TITLE
Multiple Nginx

### ISSUE THREAD

**Issue by Divxtaman** [nginxinc/kubernetes-ingress#457]
Apologize if it's not the right place to ask but I m getting so confused with ingress, I am coming from Docker world and trying to adopt Kubernetes with Ingress for multiple virtual hosts. In my Docker I have setup these containers:

1. nginx:alpine
1. php-fpm (www.site1.example.com)
1. php-fpm (www.site2.example.com)
1. php-fpm (www.site3.example.com)

So I have four containers, my PHP-fpm based containers are using the same nginx container/config so no additional nginx container has been installed. 

Now I am trying to move to Kubernetes same setup, I successfully installed and configured Kubernetes using Ingress, It also setup load balancer successfully.

Now I need to deploy my php-fpm application but as per looking examples over the net, I only found the one which has two images, for example I built one with below:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: app1
  name: app1
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: app1
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: app1
    spec:
      nodeSelector:
        kubernetes.io/hostname: master-1
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: shared-files
        hostPath:
          path: /home/ubuntu/app
      containers:
      - name: app1
        image: php:fpm-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
          subPath: app1
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: shared-files
          mountPath: /var/www/html
          subPath: app1
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
```

So in this installation, there are two container images "php-fpm" and "nginx". 

Now I have multiple domains and I would like to keep them separatey in a container,  which means if I have 10 domains I have to install 10 nginx/php-fpm, I will end up with multiple php-fpm/nginx containers. Is it really that way or I am missing something? Can't I configure only nginx-ingress so no multiple nginx installations required?

Thanks for any guidance
