### ISSUE TITLE
FastCGI support

### ISSUE THREAD

**Issue by Divxtaman** [nginxinc/kubernetes-ingress#458]
Can this work directly with FastCGI? I couldnot find any example.... I have multiple domains and in each deployment I have two container images, nginx and php-fpm, I want to remove the nginx from my application deployment and use annotations or configMap to connect my php-fpm directly from Ingress nginx, I tried below code but its not going through, I am not sure if I am doing it right, any help please.

**Errors**

```
 controller.go:993] Error retrieving endpoints for the service appsvc1: No endpoints for target port 9000 in service appsvc1
2018/12/05 22:40:502018/12/06 00:12:03 [error] 414#414: *114 connect() failed (111: Connection refused) while connecting to upstream, client: 10.244.2.0, server: example.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "example.com"
```

**yml**
```
apiVersion: v1
kind: Service
metadata:
  name: appsvc1
  namespace: nginx-ingress
spec:
  #type: ClusterIP
  ports:
  - port: 80
    targetPort: 9000
    name: http
    protocol: TCP
  selector:
    app: app1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app1
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: php:fpm-alpine
        name: app1
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 9000
          name: web
          protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app1
  namespace: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "4m"
    nginx.org/server-snippets: |
        location ~ \.(php)$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 3000;
      }
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: appsvc1
          servicePort: 80
        path: /

```
some logs
```
$ kubectl get endpoints appsvc1 -n nginx-ingress
NAME      ENDPOINTS                                           AGE
appsvc1   10.244.2.33:9000,10.244.2.33:9000,10.244.2.33:443   81m
```

How can I get the php-fpm to works? how to get the real IP instead 127.0.0.1:9000?
Thanks,

**Comment by Divxtaman** [comment]
I tired to manipulate Ingress-template via configmap and get IP with  `#{{$server.Address}}:{{$server.Port}} ` but unable to set server.Address
(not familiar with Go)

**Error**
`I1206 12:38:00.031181       1 event.go:221] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"nginx-ingress", Name:"nginx-config", UID:"c3f7de91-f953-11e8-87b7-023cf11ef4e8", APIVersion:"v1", ResourceVersion:"103492", FieldPath:""}): type: 'Warning' reason: 'UpdatedWithError' Configuration from nginx-ingress/nginx-config was updated but was not applied: Error generating Ingress Config nginx-ingress-app1: template: ingressTemplate:121:14: executing "ingressTemplate" at <$server.Address>: can't evaluate field Address in type nginx.Server`

**ConfigMap**
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  ingress-template: |
    # configuration for {{.Ingress.Namespace}}/{{.Ingress.Name}}
    {{range $upstream := .Upstreams}}
    upstream {{$upstream.Name}} {
      {{if $upstream.LBMethod }}{{$upstream.LBMethod}};{{end}}
      {{range $server := $upstream.UpstreamServers}}
      server {{$server.Address}}:{{$server.Port}} max_fails={{$server.MaxFails}} fail_timeout={{$server.FailTimeout}};{{end}}
      {{if $.Keepalive}}keepalive {{$.Keepalive}};{{end}}
    }{{end}}

    {{range $server := .Servers}}
    server {
      {{if not $server.GRPCOnly}}
      {{range $port := $server.Ports}}
      listen {{$port}}{{if $server.ProxyProtocol}} proxy_protocol{{end}};
      {{- end}}
      {{end}}
      {{if $server.SSL}}
      {{- range $port := $server.SSLPorts}}
      listen {{$port}} ssl{{if $server.HTTP2}} http2{{end}}{{if $server.ProxyProtocol}} proxy_protocol{{end}};
      {{- end}}
      ssl_certificate {{$server.SSLCertificate}};
      ssl_certificate_key {{$server.SSLCertificateKey}};
      {{if $server.SSLCiphers}}
      ssl_ciphers {{$server.SSLCiphers}};
      {{end}}
      {{end}}
      {{range $setRealIPFrom := $server.SetRealIPFrom}}
      set_real_ip_from {{$setRealIPFrom}};{{end}}
      {{if $server.RealIPHeader}}real_ip_header {{$server.RealIPHeader}};{{end}}
      {{if $server.RealIPRecursive}}real_ip_recursive on;{{end}}

      server_tokens {{$server.ServerTokens}};

      server_name {{$server.Name}};

      {{range $proxyHideHeader := $server.ProxyHideHeaders}}
      proxy_hide_header {{$proxyHideHeader}};{{end}}
      {{range $proxyPassHeader := $server.ProxyPassHeaders}}
      proxy_pass_header {{$proxyPassHeader}};{{end}}
      {{if $server.SSL}}
      {{if not $server.GRPCOnly}}
      {{- if $server.SSLRedirect}}
      if ($scheme = http) {
        return 301 https://$host:{{index $server.SSLPorts 0}}$request_uri;
      }
      {{- end}}
      {{- if $server.HSTS}}
      proxy_hide_header Strict-Transport-Security;
      add_header Strict-Transport-Security "max-age={{$server.HSTSMaxAge}}; {{if $server.HSTSIncludeSubdomains}}includeSubDomains; {{end}}preload" always;{{end}}
      {{end}}
      {{- end}}
      {{- if $server.RedirectToHTTPS}}
      if ($http_x_forwarded_proto = 'http') {
        return 301 https://$host$request_uri;
      }
      {{- end}}

      {{- if $server.ServerSnippets}}
      {{range $value := $server.ServerSnippets}}
      {{$value}}{{end}}
      {{- end}}

      {{range $location := $server.Locations}}
      location {{$location.Path}} {
        {{with $location.MinionIngress}}
        # location for minion {{$location.MinionIngress.Namespace}}/{{$location.MinionIngress.Name}}
        {{end}}
        {{if $location.GRPC}}
        {{if not $server.GRPCOnly}}	
        error_page 400 @grpcerror400;
        error_page 401 @grpcerror401;
        error_page 403 @grpcerror403;
        error_page 404 @grpcerror404;
        error_page 405 @grpcerror405;
        error_page 408 @grpcerror408;
        error_page 414 @grpcerror414;
        error_page 426 @grpcerror426;
        error_page 500 @grpcerror500;
        error_page 501 @grpcerror501;
        error_page 502 @grpcerror502;
        error_page 503 @grpcerror503;
        error_page 504 @grpcerror504;
        {{end}}
        
        {{- if $location.LocationSnippets}}
        {{range $value := $location.LocationSnippets}}
        {{$value}}{{end}}
        {{- end}}

        grpc_connect_timeout {{$location.ProxyConnectTimeout}};
        grpc_read_timeout {{$location.ProxyReadTimeout}};
        grpc_set_header Host $host;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Host $host;
        grpc_set_header X-Forwarded-Port $server_port;
        grpc_set_header X-Forwarded-Proto {{if $server.RedirectToHTTPS}}https{{else}}$scheme{{end}};

        {{- if $location.ProxyBufferSize}}
        grpc_buffer_size {{$location.ProxyBufferSize}};
        {{- end}}

        {{if $location.SSL}}
        grpc_pass grpcs://{{$location.Upstream.Name}}{{$location.Rewrite}};
        {{else}}
        grpc_pass grpc://{{$location.Upstream.Name}}{{$location.Rewrite}};
        {{end}}
        {{else}}
        proxy_http_version 1.1;
        {{if $location.Websocket}}
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        {{- else}}
        {{- if $.Keepalive}}proxy_set_header Connection "";{{end}}
        {{- end}}

        {{- if $location.LocationSnippets}}
        {{range $value := $location.LocationSnippets}}
        {{$value}}{{end}}
        {{- end}}
        #{{$server.Address}}:{{$server.Port}}
        proxy_connect_timeout {{$location.ProxyConnectTimeout}};
        proxy_read_timeout {{$location.ProxyReadTimeout}};
        client_max_body_size {{$location.ClientMaxBodySize}};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto {{if $server.RedirectToHTTPS}}https{{else}}$scheme{{end}};
        proxy_buffering {{if $location.ProxyBuffering}}on{{else}}off{{end}};

        {{- if $location.ProxyBuffers}}
        proxy_buffers {{$location.ProxyBuffers}};
        {{- end}}
        {{- if $location.ProxyBufferSize}}
        proxy_buffer_size {{$location.ProxyBufferSize}};
        {{- end}}
        {{- if $location.ProxyMaxTempFileSize}}
        proxy_max_temp_file_size {{$location.ProxyMaxTempFileSize}};
        {{- end}}
        {{if $location.SSL}}
        proxy_pass https://{{$location.Upstream.Name}}{{$location.Rewrite}};
        {{else}}
        proxy_pass http://{{$location.Upstream.Name}}{{$location.Rewrite}};
        {{end}}
        {{end}}
      }{{end}}
      {{if $server.GRPCOnly}}
      error_page 400 @grpcerror400;
      error_page 401 @grpcerror401;
      error_page 403 @grpcerror403;
      error_page 404 @grpcerror404;
      error_page 405 @grpcerror405;
      error_page 408 @grpcerror408;
      error_page 414 @grpcerror414;
      error_page 426 @grpcerror426;
      error_page 500 @grpcerror500;
      error_page 501 @grpcerror501;
      error_page 502 @grpcerror502;
      error_page 503 @grpcerror503;
      error_page 504 @grpcerror504;
      {{end}}
      {{if $server.HTTP2}}
      location @grpcerror400 { default_type application/grpc; return 400 "\n"; }
      location @grpcerror401 { default_type application/grpc; return 401 "\n"; }
      location @grpcerror403 { default_type application/grpc; return 403 "\n"; }
      location @grpcerror404 { default_type application/grpc; return 404 "\n"; }
      location @grpcerror405 { default_type application/grpc; return 405 "\n"; }
      location @grpcerror408 { default_type application/grpc; return 408 "\n"; }
      location @grpcerror414 { default_type application/grpc; return 414 "\n"; }
      location @grpcerror426 { default_type application/grpc; return 426 "\n"; }
      location @grpcerror500 { default_type application/grpc; return 500 "\n"; }
      location @grpcerror501 { default_type application/grpc; return 501 "\n"; }
      location @grpcerror502 { default_type application/grpc; return 502 "\n"; }
      location @grpcerror503 { default_type application/grpc; return 503 "\n"; }
      location @grpcerror504 { default_type application/grpc; return 504 "\n"; }
      {{end}}
    }{{end}} 
```

**Comment by Divxtaman** [comment]
I was able to make it work by using custom annotations and passing `fastcgi_pass {{$location.Upstream.Name}}` in location block

**Comment by pleshakov** [comment]
the primary use case for the Ingress Controller is HTTP and gRPC traffic, that's why there is no support for fastcgi_pass.
glad that you found a way to support fastcgi_pass.

**Comment by harshmanvar** [comment]
@RazaGR 

> I was able to make it work by using custom annotations and passing `fastcgi_pass {{$location.Upstream.Name}}` in location block

if you can please share your ingress yaml config it's not working for me

my ingress

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: word-cm
  namespace: development
data:
  SCRIPT_FILENAME: "/var/www/html/index.php"
  FASTCGI_PASS : "wordpress-site:9000"
  fastcgi_pass: "wordpress-site:9000"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: wordpress-dev
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/fastcgi_send_timeout: "1800"
    nginx.ingress.kubernetes.io/fastcgi_read_timeout: "1800"
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "development/word-cm"
```

getting log error 

`[error] 5961#5961: *1543902 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 49.34.117.7, server: dev.example.io, request: "GET / HTTP/2.0", upstream: "http://10.8.4.220:9000/", host: "dev.example.io"`

look like upstream is not changing to fastcgi still **HTTP** is there.
