### ISSUE TITLE
How to set rate limit only for specific path on same ingress yaml?

### ISSUE THREAD

**Issue by kycfeel** [nginxinc/kubernetes-ingress#469]
Hi there.
I'm trying to set rate limit for various paths on single ingress yaml file.

I firstly tried to use `nginx.org/location-snippets` but it applied rate limit setting on every paths on the file. I want to apply it on only specific path. Which options or annotations should i use for that?

My current ingress yaml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.org/websocket-services: "<WS_SERVICE>"
    nginx.org/lb-method: "ip_hash"
    nginx.org/server-tokens: "False"
    nginx.org/location-snippets: |
      limit_req zone=nginx_rate_limit burst=1 nodelay;

spec:
  rules:
  - host: <DOMAIN>
    http:
      paths:
      - path: /
        backend:
          serviceName: <API_SERVICE>
          servicePort: <API_PORT>
      - path: /<WS_PATH>
        backend:
          serviceName: <WS_SERVICE>
          servicePort: <WS_PORT>
  tls:
  - secretName: <TLS_NAME>
    hosts:
    - <DOMAIN>
```

and the result of this

```
location / {


		proxy_http_version 1.1;


		limit_req zone=nginx_rate_limit burst=1 nodelay;


		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;

		proxy_pass http://<API_ENDPOINT>;


	}

	location /<WS_PATH> {


		proxy_http_version 1.1;

		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		limit_req zone=nginx_rate_limit burst=1 nodelay;


		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;

		proxy_pass http://<WS_ENDPOINT>;

}
```

I just want to apply rate limit on <API>, not on <WS> together.

Need you help. Thanks.
