### ISSUE TITLE
Cant apply NGiNX configuration (not via ingress or configmaps)

### ISSUE THREAD

**Issue by claudio-bw** [nginxinc/kubernetes-ingress#483]
Hello there.
I can't apply custom NGiNX configurations (client-max-body-size: 20m) for a service.
The controller is simply not parsing the `nginx-configuration` configMap.

**My Setup:**
K8s 1.1 @ AWS EKS
Controller Image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.22.0
NGiNX Version: 1.15.8

Steps:
1. Update `nginx-config.yaml` (name="nginx-configuration") with:
```
kind: ConfigMap
apiVersion: v1
name: nginx-configuration
namespace: ingress-nginx
data:
  use-proxy-protocol: "false"
  client-max-body-size: 20m
metadata:
  annotations:
    nginx.org/client-max-body-size: 20m
    nginx.ingress.kubernetes.io/client-max-body-size: 20m
    nginx.ingress.kubernetes.io/nginx.bodySize: 20m
    ...
```

2. Bounce controller (eg. by deleting the Pod)

3. Exec IT into container and check nginx.conf
`cat /etc/nginx/nginx.conf`

Changes not applied :(

4. Trying now via Ingress Rules (using community edition and normal edition config types..)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: payload-tester-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/client-max-body-size: 20m
    nginx.org/client-max-body-size: 20m
    ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/nginx.bodySize: 20m
```

Changes not applied :(
