### ISSUE TITLE
How to pass full path to pod in k8 ngnix-ingress?

### ISSUE THREAD

**Issue by kkocel** [nginxinc/kubernetes-ingress#486]
I have following helm configuration:
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target:  /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
  paths:
    - /api/ud
    - /oauth2
  hosts:
    - open-brewery.com
  tls:
    - secretName: open-brewery-crt
      hosts:
        - open-brewery.com
```

Which is translated into:

```
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- range $ingressPaths }}
          - path: {{ . | quote }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
````

When I call my pod using `/mypath/` I get to the pod but it does not receive full prefix to the service. 

I would like to pass a path prefix to my pod in order to receive eg. `GET /mypath/foo`, but at the same time have `/otherpath/` stripped away when making a request.
