### ISSUE TITLE
Collect the InstallationID 

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#4882]
UAC:

- Determine if NIC is installed as a Daemonset or a Deployment
- Get the UID of the Daemonset/Deployment

Example of UID from `kubectl get deploy <deployment_name> -o yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
   ....
  creationTimestamp: "2024-03-06T08:35:52Z"
  generation: 2
  labels:
    ....
  name: test-nginx-ingress-controller
  namespace: default
  uid: 3ec77c9f-0ddc-44ab-8d3e-46208077d23f
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: nginx-ingress
```

Example of UID from `kubectl get damonset <daemonset_name> -o yaml`
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    ....
  creationTimestamp: "2024-03-06T11:15:56Z"
  generation: 1
  labels:
   ....
  name: test-nginx-ingress-controller
  namespace: default
  uid: f95aff08-2736-4c84-a031-e8ad66118176
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: nginx-ingress
```

For nginx-gateway-fabric, they use the UID of the Deployment:
https://github.com/nginxinc/nginx-gateway-fabric/blob/f33db51fc9e05ccf98fc8cdae100772a5cc6775e/internal/mode/static/telemetry/collector.go#L244-L248

----------------

# ALL DETAILS and REQUIREMENTS BELOW ARE OBSOLETE !!!

----------------

### All details below here is from our original discussion around generated a `GUID`, which we are now calling the `InstallationID`

We want this GUID to be fully unique to ensure that multiple deployments/daemonsets of NIC on a single cluster can be uniquely identified:

Possible format:
A hash of `ClusterID` + `pod-namespace` + `name` + `kind`

Example GUID before hashing for a `deployment` kind (separated by `/` in this case)
```
d290f1ee-6c54-4b01-90e6-d701748f0851/nginx-ingress/nginx-ingress/deployment
```

Example GUID after hashing for a `deployment` kind
```
echo d290f1ee-6c54-4b01-90e6-d701748f0851/nginx-ingress/nginx-ingress/deployment | md5sum -t
23beab5d71a12ce7ed3db70e9a7beeda
```

Example of GUID for a `daemonset` kind:
```
echo d290f1ee-6c54-4b01-90e6-d701748f0851/nginx-ingress/nginx-ingress/daemonset | md5sum -t
413708edb16319506eba73642b46b9e5
```
