### ISSUE TITLE
Invalid annotations silently ignored.

### ISSUE THREAD

**Issue by lseelenbinder** [nginxinc/kubernetes-ingress#489]
**Describe the bug**
When applying an Ingress with invalid annotations, the controller ignores all annotations and uses the system defaults instead of only ignoring the invalid annotation.

**To Reproduce**
1. Deploy an ingress with a mix of valid and invalid annotations.
2. View actual deployed configuration in pod.
3. None of the valid annotations are applied and all system defaults are used.

**Expected behavior**
Ideally:
1. An error is raised in the nginx-ingress-controller pod logs.
2. All valid annotations are still applied.

Acceptable:
Only (1).

**Your environment**
* Version of the Ingress Controller: v1.4.3
* Version of Kubernetes: v1.11.5
* Kubernetes platform (e.g. Mini-kube or GCP): kubespray
* Using NGINX or NGINX Plus: Nginx

**Additional context**
An example ingress controller that triggers this condition:

```yaml
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: media-proxy
  annotations:
    nginx.org/lb-method: "hash $uri consistent" # this is never applied, even though valid.
    nginx.org/keepalive: 16 # this should be a string value, so it's invalid.
spec:
  tls:
  - hosts:
    - demo.example.com
  rules:
  - host: demo.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: example
          servicePort: http
```
