### ISSUE TITLE
Route to different backends based on HTTP method

### ISSUE THREAD

**Issue by gjcarneiro** [nginxinc/kubernetes-ingress#490]
**Is your feature request related to a problem? Please describe.**

I wanted to route to different  backends based on method.  For example:

1. `POST /v1/orders/` would go to one backend pool;
2. `GET /v1/orders/` would go to another backend pool.

The reason being that sometimes POST needs to be always fast, while GET involves DB queries and can be slow.  I don't want to mix the two in the same backend, for multiple reasons.

**Describe the solution you'd like**

I would be happy with a simple annotation that causes the Ingress to match only certain methods.  For example:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orders-creation
  annotations:
    nginx.org/http-method-match:
        - POST
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /v1/orders
        backend:
          serviceName: tea-post-svc
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orders-query
  annotations:
    nginx.org/http-method-match:
        - "!POST"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /v1/orders
        backend:
          serviceName: tea-get-svc
          servicePort: 80
```  

It's unfortunate that you need 2 Ingress resources, but it seems the simplest approach, otherwise the Kubernetes project would have to be persuaded to alter the Ingress resource schema.

Note: similar issue I opened 2 years ago on the kubernetes/ingress-nginx project (alas, no progress on their side): https://github.com/kubernetes/ingress-nginx/issues/187

**Comment by pleshakov** [comment]
@gjcarneiro 
This is a good use case. Unfortunately, we have no plans for adding any more annotations to the Ingress Controller.

At the same time, we're currently working on creating our own Ingress configuration based on [Custom Resources](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/). This configuration will support advanced routing use cases, such as routing based on request headers, cookies and the method.

**Comment by gjcarneiro** [comment]
A CRD sounds like a good idea to me.  So, if you are working on a CRD, consider this use case.  Thanks!

**Comment by smirzai** [comment]
would a pull request for adding the support through annotation be considered?

**Comment by ashish2007csGit** [comment]
Hi Team I have same requirement to handle backendcall based on http methods .. so accordingly I can do operation e.g create, update , delete

**Comment by pleshakov** [comment]
@smirzai we'd rather not have any additional annotations, because, as I mentioned, we're currently working on creating our own Ingress configuration based on [Custom Resources](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/). This configuration will support advanced routing use cases, such as routing based on request headers, cookies and the method.

However, perhaps you have some simple solution in mind? Can it be expressed through custom annotations https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/custom-annotations.md ?

**Comment by pleshakov** [comment]
I think the following workaround can work until we have method-based routing support through Custom Resources.  To show the workaround, I will use the example from the [first comment](https://github.com/nginxinc/kubernetes-ingress/issues/490#issue-409817414) in this issue. The workaround assumes that the user has some understanding of NGINX configuration.

**Step 1.** Add the following map to `http` context of NGINX configuration. The map will be used for deciding where to route a client request. We can add the map via a ConfigMap:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  http-snippets: |
    map $request_method $cafe_ingress_dest {
        GET '/_get/v1/orders';
        POST '/_post/v1/orders';
        default '/_get/v1/orders'; 
    }
```
Alternatively, it is possible to create a [custom annotation](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/custom-annotations.md) that will add the map to the `http` context of the configuration file for the Ingress resource, so that the map can be defined in the Ingress resource.

**Step2.** Extend the Ingress resource with snippets annotations:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.org/location-snippets: |
       internal;
       rewrite ^ $original_uri break;
     nginx.org/server-snippets: |
       location /v1/orders {
         set $original_uri $uri;
         rewrite ^ $cafe_ingress_dest last;
       }
spec:
  rules:
  - host: "cafe.example.com"
    http:
      paths:
      - path: /_get/v1/orders
        backend:
          serviceName: tea-get-svc
          servicePort: 80
      - path: /_post/v1/orders
        backend:
          serviceName: tea-post-svc
          servicePort: 80

```

**As a result** of Step1 and Step2 the following NGINX configuration will be generated:

in the main NGINX config:
```nginx
   . . .
    map $request_method $cafe_ingress_dest {
        GET '/_get/v1/orders';
        POST '/_post/v1/orders';
        default '/_get/v1/orders';
    }
 . . .
```
in the config for the Ingress resource:
```nginx
upstream default-cafe-ingress-cafe.example.com-tea-post-svc-80 {
 . . .
}
upstream default-cafe-ingress-cafe.example.com-tea-get-svc-80 {
 . . .
}


server {
        listen 80;

        server_name cafe.example.com;

        location /v1/orders {
          set $original_uri $uri;
          rewrite ^ $cafe_ingress_dest last;
        }

        location /_get/v1/orders {
                internal;
                rewrite ^ $original_uri break;
                . . .
                proxy_pass http://default-cafe-ingress-cafe.example.com-tea-get-svc-80;
        }
        location /_post/v1/orders {
                internal;
                rewrite ^ $original_uri break;
                . . . 
                proxy_pass http://default-cafe-ingress-cafe.example.com-tea-post-svc-80;
        }
}
```
This configuration will route post requests to the tea-post svc and all other requests to the tea-get svc.

Note that `/_post/v1/orders` and `/_get/v1/orders` are not accessible to the clients.

More info about NGINX directives and variables that we used:
* http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite
* http://nginx.org/en/docs/http/ngx_http_core_module.html#internal
* http://nginx.org/en/docs/http/ngx_http_map_module.html#map
* http://nginx.org/en/docs/http/ngx_http_core_module.html#var_uri

More info about ConfigMap and Annotations -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md

What do you guys think?

**Comment by Rulox** [comment]
Hey @gjcarneiro 

With the release of 1.5.0 we have introduced the [VirtualServer and VirtualServerRoute](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/virtualserver-and-virtualserverroute.md) custom resources as an alternative of the regular ingress resource.

Check the [example of advancing routing](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/advanced-routing), check the [yaml](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples-of-custom-resources/advanced-routing/cafe-virtual-server.yaml#L24) where you will see a complete example of routing based in method.

Please keep in mind VirtualServer and VirtualServerRoutes are not 100% functional and they might lack some of the capabilities present in regular ingress resources. However, we would like to hear your feedback! Let us know if something like that would solve your problem and if you are missing something else.

Thanks

**Comment by gjcarneiro** [comment]
Wow, that looks very promising indeed, thanks!

**Comment by rkleine** [comment]
Hi @Rulox 

I was trying VirtualServer. Is there any chance to handle "dynamic paths" with regular expression or something similar?, for example: 
(see `path: /*` in `routes`)

```yaml
apiVersion: k8s.nginx.org/v1alpha1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  upstreams:
  - name: tea-put
    service: tea-put-svc
    port: 80
  - name: tea
    service: tea-svc
    port: 80
  routes:
  - path: /*
    rules:
      conditions:
      - variable: $request_method
      matches:
      - values: 
        - PUT
        upstream: tea-put
      defaultUpstream: tea
```
