### ISSUE TITLE
Define ingress rule with same host and path to the same k8s service with different port

### ISSUE THREAD

**Issue by idanleshnovolsky** [nginxinc/kubernetes-ingress#495]
I have the below issue.
I have container in k8s that expose 2 ports: 80 and 89.
The difference between the 2 ports is that port 89 can get parameters in the url.
I have created 2 ingress rules for this service:
1. with hostname "host1", path "/" and port 80.
2. with hostname "host1", path "/" and port 89.

Once i'm trying to curl to host1:80/some/path and look in ingress controller log, i see that request gets to port 89 instead of 80. If i try to curl to port 89, i see in the log that it goes to port 80.

Any idea what can cause this issue?
Is ingress controller supports this scenario?

**Comment by pleshakov** [comment]
@idanleshnovolsky could you possibly provide a few additional examples of requests that must be routed to port 80 and port 89?

**Comment by idanleshnovolsky** [comment]
@pleshakov , Thanks for replying.
All our request to this container routed to port 80 and/or port 89 depends on business logic.
Most of the requests are routed to port 80, the only case we want to route requests to port 89 is if we want to send parameter called ENV to the request.

The request to both ports can be same:
http://host1:89/ESBGatway/Services/test.asmx?ENV=test
http://host1:80/ESBGatway/Services/test.asmx

**Comment by pleshakov** [comment]
@idanleshnovolsky 
this can be accomplished using routing based on regular expressions. However, we currently don't support that in the Ingress Controller.

With that said, there are two workaround I can suggest:
(1)
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  namespace: default
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.org/server-snippets: |
       location ~ ENV=test$ {
          proxy_connect_timeout 60s;
          proxy_read_timeout 60s;
          client_max_body_size 1m;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_buffering on;

          proxy_pass http://default-cafe-ingress--tea-svc-89;
       }
spec:
  backend:
    serviceName: tea-svc
    servicePort: 89
  rules:
  - host: "cafe.example.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: tea-svc
          servicePort: 80
```
Here requests like `cafe.example.com/abc` are routed to the tea svc on port 80 and requests like `cafe.example.com/abc?ENV=test` are routed to the tea svc on port 89. More info about annotations -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md

(2)
In your backend pod deploy an additional container with NGINX that will accept traffic on port 80 and then route it to the ports of your application.  In your Ingress resource you will have one route --  "host1", path "/"-> port 80 of NGINX And then for NGINX in your pod you configure it using native NGINX configuration to proxy traffic to your backend application to the correct port.
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

**Comment by idanleshnovolsky** [comment]
Hi @pleshakov ,
In WA option 1 in the ingress yaml for port 89, you didn't mention host and path like in port 80. Is this made by mistake or this is how it should be?

Another question reg:
nginx.org/server-snippets: |
       location ~ ENV=test$ {
          proxy_connect_timeout 60s;
          proxy_read_timeout 60s;
          client_max_body_size 1m;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_buffering on;

          proxy_pass http://default-cafe-ingress--tea-svc-89;
       }
The location here is ENV=test. If i want that the value for ENV will be something else, how this is impacting the snippet?
Also, how did you chose the value for proxy_pass (http://default-cafe-ingress--tea-svc-89)?

**Comment by pleshakov** [comment]
@idanleshnovolsky 
> In WA option 1 in the ingress yaml for port 89, you didn't mention host and path like in port 80. Is this made by mistake or this is how it should be?

yep, this is how it show be, partly because it is a WA. instead of defining a location using a `path` field in the host part of the spec, we define it via the `nginx.org/server-snippets` annotation and the default backend section of the spec:
```
spec:
  backend:
    serviceName: tea-svc
    servicePort: 89
```

> The location here is ENV=test. If i want that the value for ENV will be something else, how this is impacting the snippet?

Please take a look at this doc http://nginx.org/en/docs/http/ngx_http_core_module.html#location Yes, it is possibly for the ENV to have any value, provided  you have a correct regular expression.

> Also, how did you chose the value for proxy_pass (http://default-cafe-ingress--tea-svc-89)?

the value is constructed using the following rule:
```
<namespace>-<ingress-name>-<host>-<service-name>-<port>
```
In case of `default-cafe-ingress--tea-svc-89`, the host is empty, because the upstream was defined in the default backend part of the Ingress resource.

When working with low-level annotations like snippets, it is useful to see the full generated config of NGINX. For that, please take a look at this https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/troubleshooting.md#checking-the-generated-config
