### ISSUE TITLE
Add support of ${jwt_claim_*} variables for keys to a rateLimit policy resource

### ISSUE THREAD

**Issue by thecoldwine** [nginxinc/kubernetes-ingress#4975]
**Is your feature request related to a problem? Please describe.**
Currently `rateLimit` supports only ${http_}, ${arg_} and ${cookie_} special variables as a key for rate limit. It is possible to use `$jwt_claim_` variables via snippets injected to the configuration, i.e.

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: app
spec:
  host: app.example.com
  http-snippets: |
    limit_req_zone $jwt_claim_sub zone=app_server_req_limit:30m rate=1r/s;
  routes:
  - action:
      proxy:
        upstream: app
    path: /
    location-snippets: |
      limit_req zone=app_server_req_limit burst=5 delay=5;
  upstreams:
  - name: app
    port: 80
    service: app-server-svc
```

**Describe the solution you'd like**
Create a policy resource and use jwt claim as a rate limiting key.

```yaml
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limiting
spec:
  rateLimit:
    rate: 10r/s
    zoneSize: 10M
    key: ${jwt_claim_sub}
```

**Describe alternatives you've considered**
The workaround is provided in the first section.
