### ISSUE TITLE
Update Ingress documentation and examples to networking.k8s.io/v1

### ISSUE THREAD

**Issue by haywoodsh** [nginxinc/kubernetes-ingress#5006]
**Describe the bug**
Under `docs` and `example/ingress-reources` folder, a lot of docs and examples in Markdown are still using the beta version of the Ingress API with deprecated fields such as `serviceName` and `servicePort`, even though `apiVersion` has been updated. For example:

```
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```

It should be updated to use the v1 API like the following:
```
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port:
              number: 80
      - path: /coffee
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 80

```
In the Kubernetes versions we currently support, if users copy and paste these examples and deploy the YAMLs, the Kubernetes API would reject the requests as invalid and return errors such as 
```
 strict decoding error: unknown field "spec.rules[0].http.paths[0].backend.serviceName", unknown field "spec.rules[0].http.paths[0].backend.servicePort", unknown field "spec.rules[0].http.paths[1].backend.serviceName", unknown field "spec.rules[0].http.paths[1].backend.servicePort"
```

Some of the affected pages include:
docs/content/configuration/ingress-resources/basic-configuration.md
docs/content/configuration/configuration-examples.md
examples/ingress-resources/path-regex/README.md

The oldest Kubernetes version we currently support is 1.23, but the beta API is no longer supported in 1.22. See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
