### ISSUE TITLE
Proxy protocol not rewriting remote_addr from DOKS load balancer

### ISSUE THREAD

**Issue by Syntaf** [nginxinc/kubernetes-ingress#5076]
**Describe the bug**
My remote address remains an internal address even after setting up and accepting the proxy protocol from my DOKS (Digital Ocean Kubernetes) load balancer.

**To Reproduce**

1. I followed (only) step 4 of DO's [instructions](https://docs.digitalocean.com/support/how-do-i-enable-proxy-protocol-when-my-load-balancer-sends-requests-to-the-nginx-ingress-controller/) to configure my load balancer to use the proxy protocol.
2. I followed the this repositories [docs](https://github.com/nginxinc/kubernetes-ingress/tree/v3.4.2/examples/shared-examples/proxy-protocol) to setup my ingress to handle the proxy protocol
   ```yaml
   # values.yaml

   # ingress resource & server snippet
   ingress:
     enabled: true
     annotations:
       nginx.org/server-snippets: |
         gzip on;
         gzip_types text/plain text/html application/json;

         server_name *.embolt.app;

         if ($host = "www.embolt.app") {
           return 301 $scheme://embolt.app$request_uri;
         }
      host:
         # ...

   # nginx-ingress configuration
   nginx-ingress:
     controller:
       # ...
       enableSnippets: true
       config:
         entries:
           proxy-protocol: "True"
           real-ip-header: "proxy_protocol"
           set-real-ip-from: "<internal IP>"
      service:
        annotations:
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
   ```
4. I'm still only able to see the internal IP when viewing ingress logs from NGINX using the default log format
   ```
   10.120.0.5 - - [13/Feb/2024:02:05:49 +0000] "GET / HTTP/1.1" 200 4781 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" "-"
   ```

**Expected behavior**
I would have expected to see either the initial address (remote_addr) or final segment of the logs (x_forwarded_for) to have contained the client's IP address.

**Your environment**

- Version of the Ingress Controller - `0.17.1`
- Version of Kubernetes - `1.26.7-do.0`
- Kubernetes platform - Digital Ocean (DOKS)
- Using NGINX or NGINX Plus - NGINX

**Additional context**
* I'm able to confirm that my LB is using the proxy protocol, for example when I removed the proxy protocol configuration from my nginx config but retained the load balancer annotations I received the following error confirming it was using the protocol:
   ```
   10.120.0.5 - - [11/Feb/2024:22:24:58 +0000] "PROXY TCP4 68.224.237.201 138.68.36.61 54359 443" 400 157 "-" "-" "-"
   ```
* My application _works_ fine using the configuration above, I just simply do not seem to have any client IP information
* I'm wondering if this might mean my NGINX server snippets or configuration elsewhere is invalid if the proxy protocol is being read fine but my client addresses still aren't showing up.

Thank you for anyone that might have ideas on this!

**Comment by j1m-ryan** [comment]
Hi @Syntaf. I set up NGINX Ingress Controller on DOKS today to look into this.

I deployed NGINX Ingress Controller `v3.4.2` (this has helm chart version `1.1.2`) along with the example in `examples/ingress-resources/complete-example`

I made one modification to this example, deleting the TLS stuff in `cafe-ingress.yaml`, otherwise it's identical.

I used the following in my config map
```yaml
config:
  entries:
    proxy-protocol: "True"
      real-ip-header: "proxy_protocol"
      set-real-ip-from: "0.0.0.0/0"
```

And added the required annotation you mentioned from the Digital Ocean Kubernetes docs, on the NGINX Ingress Controller service, just as you have done
```
service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
```

I then sent a curl request to my digital ocean kubernetes cluster
curl -H "Host: cafe.example.com" http://redacted/coffee

I then looked in the NIC logs, and saw my personal ip address which I will also redact.
```
XXX.XXX.XXX.XXX - - [13/Feb/2024:16:52:55 +0000] "GET /coffee HTTP/1.1" 200 161 "-" "curl/8.2.1" "-"
```

So it does appear to be working on `v3.4.2`

I saw that you are using the helm chart version `0.17.1` which corresponds to NIC `v3.1.1` which was released in May. I uninstalled NIC  `v3.4.2`. and pulled the helm chart version  `0.17.1`, adjusted the `values.yaml` as above and installed NIC again. I then ran the curl command again against the new external IP of the service

`curl -H "Host: cafe.example.com" http://redacted/coffee`

I got the same result again in the NIC logs, I could see my own IP address.

The only real differences I can see from our setups, is the snippet that you are using. I do not suspect this would cause this issue though. And the other difference being the that you are using an internal ip for `set-real-ip-from`.
