### ISSUE TITLE
Warning in NGINX logs which says "using uninitialized `default_connection_header` variable" when using `rewritePath`

### ISSUE THREAD

**Issue by j1m-ryan** [nginxinc/kubernetes-ingress#5082]
**Describe the bug**
There is a warning in the NGINX logs which looks like this
```
2024/02/13 12:30:28 [warn] 89#89: *23 using uninitialized "default_connection_header" variable, client: 10.244.0.1, server: cafe.example.com, request: "GET /coffee HTTP/1.1", host: "cafe.example.com"
```

**To Reproduce**

1. Modify the `examples/custom-resources/traffic-splitting/cafe-virtual-server.yaml` file to look like this
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee-v1
    service: coffee-v1-svc
    port: 80
  - name: coffee-v2
    service: coffee-v2-svc
    port: 80
  routes:
  - path: /coffee
    splits:
    - weight: 50
      action:
        proxy:
          upstream: coffee-v1 
          rewritePath: /coffee
    - weight: 50
      action:
        pass: coffee-v2

```
2. `kaf examples/custom-resources/traffic-splitting`
3.  `curl cafe.example.com/coffee` a few times
4.  See error in the logs about 50% of the time (due to it being a 50 50 split).

**Expected behavior**
Expectation is that I should be able to `rewrite` inside these location blocks without a warning in the logs about an uninitialized variable

**Your environment**

- Version of the Ingress Controller - `3.5.0-snapshot`
- Version of Kubernetes -  Client Version: v1.28.4 Server Version: v1.28.3
- Kubernetes platform - minikube
- Using NGINX Plus

**Additional context**
@defanator experienced this and provided a few potential solutions here https://github.com/defanator/rewrite-using-uninitialized-variable
Solution 1: move the `set` before the `rewrite` in the go tmpl files
Solution 2: use a `map` instead of a `set`

relevant part of the generated nginx config
```nginx
location /internal_location_splits_0_split_0 {
        set $service "coffee-v1-svc";
        status_zone "coffee-v1-svc";
        internal;


        rewrite ^ $request_uri_no_args;
        rewrite "^/coffee(.*)$" "/coffee$1" break;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
        client_max_body_size 1m;

        proxy_buffering on;
        proxy_http_version 1.1;
        set $default_connection_header close;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $vs_connection_header;
        proxy_pass_request_headers on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host "$host";
        proxy_pass http://vs_default_cafe_coffee-v1;
        proxy_next_upstream error timeout;
        proxy_next_upstream_timeout 0s;
        proxy_next_upstream_tries 0;
    }
```
