### ISSUE TITLE
Allow specification of the `target` or `targets` in a `VirtualServer`'s `externalDNS` properties

### ISSUE THREAD

**Issue by j1m-ryan** [nginxinc/kubernetes-ingress#5196]
**Is your feature request related to a problem? Please describe.**
My problem is that the external ip address of my ingress controller, is not one that is accessible via the internet. It is a local ip address, which is then exposed to the internet via DMZ.

NIC chooses its external IP address (or addresses) when setting the DNSEndpoint entries, however I would like to overwite the target attribute. You can choose other aspects of a DNSEndpoint in the virtualserver so it would be ideal to be able to choose the `target` or `targets` here also

**Describe the solution you'd like**
In the externalDNS struct in the virtualservers
``` yaml
externalDNS:
    enable: true
    target: 1.2.3.4 # Set public ip
```

Alternatively this

``` yaml
externalDNS:
    enable: true
    targets:
      - 1.2.3.4 # setting multiple targets
      - 5.6.7.8
```
I do not myself have a usecase for setting multiple targets so would be happy with one.

**Describe alternatives you've considered**
Using an ingress instead with an externaldns annotation which allows setting the target. This does work for me but I would much prefer to use VirtualServers
```yaml
annotations: # on the ingress resource
    external-dns.alpha.kubernetes.io/target: "1.2.3.4"
```

**Additional context**
`external-dns.alpha.kubernetes.io/target` takes a comma separated list of targets so maybe this is sensible to follow, and have a list rather than a single target.
