### ISSUE TITLE
default route is wrong

### ISSUE THREAD

**Issue by jacek-marchwicki** [nginxinc/kubernetes-ingress#52]
``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
spec:
  tls:
  - hosts:
    - cafe.minikube
    - tea.minikube
    - coffee.minikube
    secretName: cafe-secret
  rules:
  - host: tea.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: tea-svc
          servicePort: 80
  - host: coffee.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: coffee-svc
          servicePort: 80
  - host: cafe.minikube
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```

in this example:
- `https://cofee.minikube/` gives `coffee-rc-XYZ` (correct)
- `https://cafe.minikube/coffee` gives `coffee-rc-XYZ` (correct)
- `https://cafe.minikube/tea` gives `tea-rc-XYZ` (correct)
- `https://wrong.minikube/` gives `coffee-rc-XYZ` (WRONG) it should return 404

**Comment by pleshakov** [comment]
Currently, the controller doesn't include the default server, which catches all HTTP/HTTPS requests with a host header that doesn't match any of the Ingress hosts. Thx for pointing that out.  We'll add it.

**Comment by pleshakov** [comment]
@jacek-marchwicki 
I can suggest the following solution. We define an Ingress resource that exposes a service that handles all requests with a value of the host header that doesn't match any of the existing Ingress hosts. We also setup SSL termination to handle HTTPS requests.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-ingress
annotations:
  nginx.org/default-server: "true"
spec:
  tls:
    - secretName: default-secret
  backend:
    serviceName: default-service
    servicePort: 80
```
Note that we don't define any Ingress rules, just a default backend without a hostname. The ` nginx.org/default-server` annotation tells NGINX to create a default server.

This way you can create a custom service that returns 404s or other things if you want.

Let me know you thoughts.
