### ISSUE TITLE
Add support for unbuffered upload (proxy-request-buffering)

### ISSUE THREAD

**Issue by fy-gualtiero-testa** [nginxinc/kubernetes-ingress#527]
NGINX 1.7.11 has introduced the "proxy-request-buffering" option to disable NGINX upload buffering. See also https://trac.nginx.org/nginx/ticket/251

I would like to have the possibility to control the "proxy-request-buffering" value in the Ingress YAML annotation or ConfigMap.

Without this feature, Ingress prevents my application to be notified when client starts an upload and, conseguently, to show an upload progress bar.

**Comment by pleshakov** [comment]
@fy-gualtiero-testa thanks for the suggestion.

Could you consider using `location-snippets` annotation or configmap key as a workaround? See  https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md#snippets-and-custom-templates

For example:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-with-annotations
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/location-snippets: "proxy_request_buffering on;"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```
