### ISSUE TITLE
Epic - Support APIKey authentication

### ISSUE THREAD

**Issue by brianehlert** [nginxinc/kubernetes-ingress#5292]
### Discussed in https://github.com/nginxinc/kubernetes-ingress/discussions/5089

<div type='discussions-op-text'>

<sup>Originally posted by **brianehlert** February 13, 2024</sup>
NGINX Plus offers a number of capabilities that align with API Gateway use cases.
One of those capabilities is APIKey based authentication.

This would introduce a new APIKey Policy object, the necessary configuration / NJS functions, the ability to associate a key or set of keys with a server or location block, support for VirtualServer and VirtualServerRoute, and a pattern for customers to follow when defining a single or set of APIKeys that is consistent with the NGINX implementation.

NGINX Ingress Controller supports both single and multi-tenant use cases.
In the single tenant use case, one team is responsible for the ingress controller configuration and all of the managed hostnames and paths.
In this case a single team would maintain the secret(s) that contain the key(s) and the header the application supports when passing the key(s) in the request.

In the multi-tenant use case, there might be multiple application teams that define different unique keys for their users, but share a single ingress controller deployment.

It is believed that the complicated workflow is supporting how customers allocate and assign key(s) in a way that is compatible with Kubernetes and that allows the customer to segment key management among multiple teams.
The ingress controller should not be a key management system itself.  It should not generate or assign keys, but rather support the use if APIKeys as a method of enforcement for allow/deny of access to server and location blocks.
</div>

Initial Policy proposal:

```yaml
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: api-key-policy
spec:
  apiKeyAuth:
    header: my-app-api-key
    secret: api-key
```

(imagine the values are base64 strings)

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: nginx-keys-secret
type: Opaque
data:
  keys: [1,22,333,4444,55555,666666,7777777]
apiVersion: v1
kind: Secret
metadata:
  name: nginx-keys-secret
type: Opaque
data:
  keys:
  - 1
  - 22
  - 333
  - 4444
  - 55555
  - 666666
  - 7777777
```

Additional suggestions and learnings can be extracted from: https://docs.nginx.com/nginx-management-suite/acm/how-to/policies/apikey-authn/#create-an-api-key-authentication-policy which contains some good high value options.
A consideration needs to be made for supporting multiple APIKeys on a single server or location.

```[tasklist]
### Tasks
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5351
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5484
```
