### ISSUE TITLE
App-ingress service always gives 404 default backend on the load balancer IP address

### ISSUE THREAD

**Issue by Msarnaot** [nginxinc/kubernetes-ingress#533]
**Describe the bug**
I followed the coffee and tea example provided, for my own deployment. This is on google cloud GKE. The expected result is when I go to my app ingress service exposed LB URL it should take me to the app, however it's serving a 404 default backend page each time. Furthermore, going to the Nginx LB service external exposed URL does not take me to the monitoring page as per the instructions here: https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#42-service-with-the-type-loadbalancer

**To Reproduce**
The following is my app ingress service yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
        nginx.org/rewrites: serviceName=my-nodeport-service rewrite=/
        nginx.org/ssl-services: my-nodeport-service
  creationTimestamp: 2019-04-04T18:00:54Z
  generation: 8
  name: my-app-ingress-service
  namespace: default
  resourceVersion: "18144114"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/my-app-ingress-service
  uid: 96f1d696-5703-11e9-954d-42010a800146
spec:
  rules:
  - host: my-host
    http:
      paths:
      - backend:
          serviceName: my-nodeport-service-name
          servicePort: 80
        path: /
  tls:
  - hosts:
    - my-host
    secretName: my-cert
status:
  loadBalancer:
    ingress:
       - ip: xx.xxx.xx.xxx

```
**Expected behavior**
When going to the app ingress service LB url I should be taken to the app

**Your environment**
* Ingress controller: "nginx/nginx-ingress:edge"
* GCP
* Using NGINX 

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by pleshakov** [comment]
Hi @Msarnaot 

Could you try to add the `kubernetes.io/ingress.class: "nginx"` annotation to your Ingress resource? It looks like the Google Cloud HTTP load balancer was allocated for your Ingress resource and you got the response from it. More info about this annotation -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/multiple-ingress-controllers.md

To access `my-host` through the NGINX  Ingress Controller, use the external IP of `nginx-ingress` service, created in https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#42-service-with-the-type-loadbalancer. For example, you can run the following command:
```
curl --resolve my-host:443:<the-extenal-ip> https://my-host:443 --insecure
```
See also https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example

>  Furthermore, going to the Nginx LB service external exposed URL does not take me to the monitoring page as per the instructions here: 

The monitoring dashboard is available with NGINX Plus, the commercial version of NGINX.

Also, you might find this doc useful -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/troubleshooting.md

**Comment by Msarnaot** [comment]
Hi @pleshakov 

Thank you for your prompt response! 

> The monitoring dashboard is available with NGINX Plus, the commercial version of NGINX.
That makes sense thank you

I added that annotation to my apps ingress resource, however I am still getting the same 404 response. 
Here is the full list of annotations on my ingress resource:

```
ingress.kubernetes.io/backends: {"k8s-xxxxx":"HEALTHY","k8s-xxxxxx":"HEALTHY"}
ingress.kubernetes.io/forwarding-rule: k8s-fw-ingress_resource-xxx
ingress.kubernetes.io/https-forwarding-rule: k8s-fws-ingress_resource-xxxx
ingress.kubernetes.io/https-target-proxy: k8s-tps-ingress_resource-xxxx
ingress.kubernetes.io/ingress.class: nginx
ingress.kubernetes.io/ssl-cert: k8s-ssl-xxxx
ingress.kubernetes.io/static-ip: k8s-fw-ingress_resource-xxxxx
ingress.kubernetes.io/target-proxy: k8s-tp-ingress_resource-xxxxx
ingress.kubernetes.io/tls-acme: true
ingress.kubernetes.io/url-map: k8s-um-ingress_resource-xxxx
nginx.org/rewrites: serviceName=my-nodeport-service rewrite=/
nginx.org/ssl-services: my-nodeport-service 
kubectl.kubernetes.io/last-applied-configuration: view data
```

I ran the following command to reach the host:
`curl --resolve my-host:xx.xxx.xx.xxx https://my-host:443 --insecure
`
And got the following result:
`curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to my-host:443 `
I'm using an SSL created with lets encrypt, I'm not sure if that's relevant, however the SSL is valid.

Can you please recommend how to best handle what's happening?

**Comment by pleshakov** [comment]
@Msarnaot 
I suggest to delete your current Ingress resource and recreate it again with the `kubernetes.io/ingress.class: "nginx"` annotation. all those `ingress.kubernetes.io` annotations were set by the Ingres Controller for Google HTTP load balancer.

After you create the Ingress resource, you can check its events to see if NGINX applied that configuration. See https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/troubleshooting.md#checking-the-events-of-an-ingress-resource

Could you try to connect to the http port -- `curl --resolve my-host:80:xx.xxx.xx.xxx https://my-host:80` ?

**Comment by Msarnaot** [comment]
@pleshakov 

I deleted the old ingress resource and recreated it with `kubernetes.io/ingress.class: "nginx"`. I then checked the events of the ingress resource, and got a normal event as per the documentation:

`Normal  AddedOrUpdated  59s   nginx-ingress-controller  Configuration for default/ingress-resource was added or updated`
I no longer receive 404 default backend response when I go to the loadbalancer IP address.

I then checked the events of the config map as per the documentation, and there were no events. I received the following from the describe ConfigMap command: 

```
Name:         nginx-config
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","data":{"proxy-protocol":"True","real-ip-header":"proxy_protocol","set-real-ip-from":"0.0.0.0/0"},"kind":"ConfigMap","metadata":{"an...

Data
====
proxy-protocol:
----
True
real-ip-header:
----
proxy_protocol
set-real-ip-from:
----
0.0.0.0/0
Events:  <none>
```

I also received the same response with curl at the http port:
`curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to my-host:80 `

Is there something wrong with the config map? I still am not able to reach the App. The following is the config map implemented:

```
apiVersion: v1
data:
  proxy-protocol: "True"
  real-ip-header: proxy_protocol
  set-real-ip-from: 0.0.0.0/0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"proxy-protocol":"True","real-ip-header":"proxy_protocol","set-real-ip-from":"0.0.0.0/0"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-config","namespace":"default"}}
  creationTimestamp: 2019-04-04T18:17:27Z
  name: nginx-config
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/nginx-config
```

**Comment by pleshakov** [comment]
@Msarnaot the configmap keys `proxy-protocol`, `real-ip-header`, `set-real-ip-from` only make sense if you expose the Ingress Controller through AWS ELB. On GKE, they will cause errors. Could you remove them from the configmap?

> I also received the same response with curl at the http port:
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to my-host:80

my bad. could you change `https` to `http` in the curl command?:
```
curl --resolve my-host:80:xx.xxx.xx.xxx http://my-host:80
```

Just to double check. Have you successfully deployed the loadbalancer service?
```
kubectl apply -f service/loadbalancer.yaml
```

If you hit its externalIP using curl, `curl http://<external-ip>`, you should get a 404 page from NGINX.

**Comment by Msarnaot** [comment]
@pleshakov 

I removed the keys you mentioned, and now I receive 404 not found when I go to the nginx load balancer service external IP address (Yes I had successfully deployed the Nginx loadbalancer service).

Curl at both http and https is giving me a 404 not found at the Nginx loadbalancer IP address.

However, I am still not able to reach my deployed app through the app ingress IP address. From my understanding the ingress resource IP address that I can get but running `kubectl get ing` will take me to the host app. Please let me know if that is wrong, or if I am missing a step.

**Comment by pleshakov** [comment]
@Msarnaot 
To get the IP from `kubectl get ing` command, it is necessary to enable the reporting Ingress status feature. See https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/report-ingress-status.md

> Curl at both http and https is giving me a 404 not found at the Nginx loadbalancer IP address.

It might be the case that the backend application returns 404. To confirm that, you can check the logs (https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/troubleshooting.md#checking-the-ingress-controller-logs) and see if you have an access log line with the 404 status.

**Comment by Msarnaot** [comment]
@pleshakov 

I do have the reporting ingress status feature in the ingress controller deployment. However, for the external-service argument, should the service name be the nginx loadbalancer service that exposes the controller? Below is my Nginx-controller deployment yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-ingress","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx-ingress"}},"template":{"metadata":{"labels":{"app":"nginx-ingress"}},"spec":{"containers":[{"args":["-nginx-configmaps=$(POD_NAMESPACE)/nginx-config","-default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret","-v=3","-report-ingress-status","-external-service=nginx-ingress"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}}],"image":"nginx/nginx-ingress:edge","imagePullPolicy":"Always","name":"nginx-ingress","ports":[{"containerPort":80,"name":"http"},{"containerPort":443,"name":"https"}]}],"serviceAccountName":"nginx-ingress"}}}}
  creationTimestamp: 2019-04-04T18:20:36Z
  generation: 5
  labels:
    app: nginx-ingress
  name: nginx-ingress
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-ingress
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-ingress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-ingress
    spec:
      containers:
      - args:
        - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
        - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
        - -v=3
        - -report-ingress-status
        - -external-service=nginx-ingress
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: nginx/nginx-ingress:edge
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nginx-ingress
      serviceAccountName: nginx-ingress
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-04-04T18:20:36Z
    lastUpdateTime: 2019-04-04T18:20:36Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-04-04T18:20:36Z
    lastUpdateTime: 2019-04-05T23:32:19Z
    message: ReplicaSet "nginx-ingress-xxxx" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

I checked the logs for the ingress controller deployment using the command and couldn't find an access log line with the 404 status. 

I also checked my apps deployment logs and everything seems fine there.
