### ISSUE TITLE
How to enable cors？

### ISSUE THREAD

**Issue by shouziws** [nginxinc/kubernetes-ingress#5524]
1.Nginx ingress version ： 3.5.0

2.When I use th ingress configuration, the directory for the “nginx/etc/nginx/conf. d/” file is as follows. the file name 'bladex-archer.conf' is exists
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archer
  namespace: bladex
  annotations:
    nginx.org/rewrites: "serviceName=archer rewrite=/"
spec:
  ingressClassName: nginx
  rules:
    - host: archer.xinchangde.covermusic.cn
      http:
        paths:
          - backend:
              service:
                name: archer-ui
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: archer
                port:
                  number: 80
            path: /api/
            pathType: Prefix
status:
  loadBalancer: {}
```
<img width="487" alt="image" src="https://github.com/nginxinc/kubernetes-ingress/assets/33045888/01c02349-ab32-445b-bb1e-0382a86ef86a">
<img width="1117" alt="image" src="https://github.com/nginxinc/kubernetes-ingress/assets/33045888/9e782234-ae4c-4845-bb86-bfc9c39eb83b">

3.When I use the ingress configuration, the directory for the “nginx/etc/nginx/conf. d/” file is as follows. the file name 'bladex-archer.conf' is not exists
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archer
  namespace: bladex
  annotations:
    nginx.org/rewrites: "serviceName=archer rewrite=/"
    nginx.org/location-snippets: |
      if ($request_method = 'OPTIONS') {
         add_header 'Access-Control-Allow-Origin' '*';
         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
         add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
         add_header 'Access-Control-Max-Age' 1728000;
         add_header 'Content-Type' 'text/plain; charset=utf-8';
         add_header 'Content-Length' 0;
         return 204;
      }
      if ($request_method = 'POST') {
         add_header 'Access-Control-Allow-Origin' '*' always;
         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
         add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
         add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
      }
      if ($request_method = 'GET') {
         add_header 'Access-Control-Allow-Origin' '*' always;
         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
         add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
         add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: archer.xinchangde.covermusic.cn
      http:
        paths:
          - backend:
              service:
                name: archer-ui
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: archer
                port:
                  number: 80
            path: /api/
            pathType: Prefix
status:
  loadBalancer: {}
```
<img width="1134" alt="image" src="https://github.com/nginxinc/kubernetes-ingress/assets/33045888/40ccaf7c-1b98-4fea-b2dd-c08790e4f58b">
