### ISSUE TITLE
Config key default-server-return does not redirect as expected

### ISSUE THREAD

**Issue by davesheldon** [nginxinc/kubernetes-ingress#5659]
**Describe the bug**
The config key "default-server-return" does not appear to be working when using the nginx-ingress helm chart

**To Reproduce**
Chart: https://kubernetes.github.io/ingress-nginx
Target Revision 4.10.1

values.yaml:

```
controller:
  allowSnippetAnnotations: true              
  ingressClassResource:
    name: cluster-ingress-nginx
    enabled: true
    default: true
    controllerValue: k8s.io/ingress-nginx                
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: {our-ip}
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  metrics:
    enabled: true
  extraArgs:
    enable-ssl-passthrough: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 50
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 200
  podAnnotations:
    linkerd.io/inject: enabled
  config:
    default-server-return: 302 https://nginx.org
```

Pinging https://{our-domain} results in {our-ip}, and all of our defined ingresses are working as expected. But when navigating to https://{our-domain}/{nonexistent-route} we still get the canned nginx 404 page.

**Expected behavior**

We should get redirected to https://nginx.org

**Your environment**

- Version of the Ingress Controller: whichever is the default for the helm chart I assume
- Version of Kubernetes: 1.29.4
- Kubernetes platform (e.g. Mini-kube or GCP): Azure Kubernetes Service
- Using NGINX or NGINX Plus: NGINX
