### ISSUE TITLE
Multiple paths with same host creates multiple servers with same server name (a.k.a. merging not working)

### ISSUE THREAD

**Issue by kalise** [nginxinc/kubernetes-ingress#579]
**Describe the bug**
We have to publish different services under the same hostname, e.g.:

`https://company.name/examples/servlets`
`https://company.name/examples/jsp`
`https://company.name/examples/websocket`

With multiple ingresses, NGINX creates multiple servers with same server name. This leads to work only for the first service, leaving 404 for the others. Mergeable Ingress Types as currently [implemented](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types) is not helpful because Ingresses are in different namespaces and there is not master/slave role.

**To Reproduce**
1. Deploy following three Ingresses

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    run: tomcat-0001
  namespace: development
  name: tomcat-0001-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - company.name
  rules:
  - host: company.name
    http:
      paths:
      - path: /examples/servlets
        backend:
          serviceName: tomcat-0001
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    run: tomcat-0002
  namespace: production
  name: tomcat-0002-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - company.name
  rules:
  - host: company.name
    http:
      paths:
      - path: /examples/jsp
        backend:
          serviceName: tomcat-0002
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    run: tomcat-0003
  namespace: production
  name: tomcat-0003-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - company.name
  rules:
  - host: company.name
    http:
      paths:
      - path: /examples/websocket
        backend:
          serviceName: tomcat-0003
          servicePort: 8080
```

2. Login to the NGINX ingress controller pod and view the configurations under `/etc/nginx/conf.d/`:

```
# configuration for production/tomcat-0002
upstream production-tomcat-0002-company.name-tomcat-0002-8080 {
        random two least_conn;
        server 10.244.6.21:8080 max_fails=1 fail_timeout=10s;
}

server {
        listen 80;
        listen 443 ssl;
        ssl_certificate /etc/nginx/secrets/wildcard;
        ssl_certificate_key /etc/nginx/secrets/wildcard;
        server_tokens on;
        server_name company.name;
        if ($scheme = http) {
                return 301 https://$host:443$request_uri;
        }
        location /examples/jsp {
                proxy_http_version 1.1;
                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;
                proxy_pass http://production-tomcat-0002-company.name-tomcat-0002-8080;
        }
}

# configuration for production/tomcat-0003

upstream production-tomcat-0003-company.name-tomcat-0003-8080 {
        random two least_conn;
        server 10.244.6.20:8080 max_fails=1 fail_timeout=10s;
}


server {
        listen 80;
        listen 443 ssl;
        ssl_certificate /etc/nginx/secrets/wildcard;
        ssl_certificate_key /etc/nginx/secrets/wildcard;
        server_tokens on;
        server_name company.name;
        if ($scheme = http) {
                return 301 https://$host:443$request_uri;
        }
        location /examples/websockets {
                proxy_http_version 1.1;
                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;
                proxy_pass http://production-tomcat-0003-company.name-tomcat-0003-8080;
        }
}

# configuration for development/tomcat-0001
upstream development-tomcat-0001-company.name-tomcat-0001-8080 {
        random two least_conn;
        server 10.244.7.28:8080 max_fails=1 fail_timeout=10s;
}

server {
        listen 80;
        listen 443 ssl;
        ssl_certificate /etc/nginx/secrets/wildcard;
        ssl_certificate_key /etc/nginx/secrets/wildcard;
        server_tokens on;
        server_name company.name;
        if ($scheme = http) {
                return 301 https://$host:443$request_uri;
        }

        location /examples/servlets {
                proxy_http_version 1.1;
                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;
                proxy_pass http://development-tomcat-0001-company.name-tomcat-0001-8080;
        }
}
```
3. See errors
```
curl -k https://company.name/examples/servlets -> 404 Not Found
curl -k https://company.name/examples/jsp -> 200 Ok
curl -k https://company.name/examples/websocket -> 404 Not Found
```

**Expected behavior**
Want to access all the exposed services.

**Your environment**
* Version of the Ingress Controller: `nginx/nginx-ingress:1.5.0`
* Version of Kubernetes: `1.14.1`
* Kubernetes platform: `On Prem`
* Using NGINX

**Additional context**
Here how NGINX is deployed
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress
  namespace: infra
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      serviceAccountName: nginx-ingress
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      hostNetwork: true
      containers:
      - image: nginx/nginx-ingress:1.5.0
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: prometheus
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /nginx-health
            port: 80
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /nginx-health
            port: 80
            scheme: HTTP
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/nginx-certs
          - -wildcard-tls-secret=$(POD_NAMESPACE)/nginx-certs
          - -v=3 # Enables extensive logging. Useful for troubleshooting.
          - -use-ingress-class-only # always set annotation "kubernetes.io/ingress.class: nginx"
          - -nginx-status
          - -nginx-status-allow-cidrs=10.0.0.0/8
          - -report-ingress-status
          - -enable-leader-election
          - -enable-prometheus-metrics
          - -prometheus-metrics-listen-port=9090
          - -enable-custom-resources
          - -health-status
```
