### ISSUE TITLE
Default installation returns 404

### ISSUE THREAD

**Issue by vmalloc** [nginxinc/kubernetes-ingress#598]
I followed the manifest installation guide step by step, running on EKS with the stock ELB configuration, to which I have the following annotations attached:
```
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:<MY ARN>"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

```

Then I created my service:
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
```

And then an ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: my-service
              servicePort: 80
            path: /
```
Trying to deploy it all, and then `curl`ing into the elb external address, I get a 404, even though my app should have served a default page.

Any help on debugging this or understanding what's going on would be greatly appreciated.

Thanks in advance!
