### ISSUE TITLE
Unable to perform SSL termination on ELB

### ISSUE THREAD

**Issue by vmalloc** [nginxinc/kubernetes-ingress#601]
I'm trying to deploy nginx-ingress where the AWS load balancer performs the SSL termination (I need that because my certs are stored on ACM), and then forward traffic to the nginx controller. How am I supposed to deploy this kind of setup?

What I did so far is set up an overrides file:
```
controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <CERT ARN>
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
```
And then install nginx-ingress:
```
helm install -f overrides.yml stable/nginx-ingress
```
From what I can gather, this causes ELB to send cleartext requests to the controller, causing an 400 error...

This is my ingress resource:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: myapp-service
              servicePort: 80
            path: /
```
How can I make this work? Is there a better scheme for deploying nginx-ingress with ACM-issued certificates?
Thanks in advance!
