### ISSUE TITLE
Ingress Controller Path and Rewrites

### ISSUE THREAD

**Issue by jsebastianmal** [nginxinc/kubernetes-ingress#6017]
I currently have an ingress driver installed on my EKS cluster where it created a Route 53 record with ACM and pointed it to my NLB and it works fine; I have created a deployment (Castlemock) and its service and when I do a portforward it works fine, but I create my ingress resource like the one attached below and it does not work, when I do a portforward castlemock works with localhost:8080/castlemock

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /castlemock
  name: approot
  namespace: sebas
spec:
  ingressClassName: nginx
  rules:
  - host: castlemock.dev.XXXXXX.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: castlemock
            port: 
              number: 80
```
and I get in the browser ERR_TOO_MANY_REDIRECTS

Thanks everyone for your help 

greetings..
