### ISSUE TITLE
nginx.org/rewrites regular $1 rewrite is not supported

### ISSUE THREAD

**Issue by datavisorrunziyang** [nginxinc/kubernetes-ingress#6033]
Hi team, I tried to replace ingress - nginx with nginx - ingress controller. When replacing ingress, I found that nginx ingress does not seem to be able to use regular expressions to rewrite URLs. Can you provide any help?

I'm not sure if there is something wrong with the way I use it or does it not support this method at present?

k8s version: 1.27
nginx-ingress: 3.6.1

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/path-regex: case_insensitive
    nginx.org/rewrites: serviceName=nginx-deployment-v1 rewrite=/$1
  generation: 9
  name: nginx-deployment-nc
  namespace: nginx
  uid: 01b766ca-4c53-4ae7-946d-7b38a5c3fa76
spec:
  ingressClassName: nginx-ingress
  rules:
  - host: example-testnc.com
    http:
      paths:
      - backend:
          service:
            name: nginx-deployment-v1
            port:
              number: 80
        path: /nginx(/|$)(.*)
        pathType: ImplementationSpecific
```

**Comment by vepatel** [comment]
hi @datavisorrunziyang, thanks for open an issue! Please have a look at our docs: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#request-uriheader-manipulation and example: https://github.com/nginxinc/kubernetes-ingress/tree/v3.6.1/examples/ingress-resources/rewrites on rewrites using ingress.
Is there a specific pattern you're looking for while using rewrites? Can you please provide us with an example scenario to better understand?

**Comment by datavisorrunziyang** [comment]
thanks @vepatel reply 

I can provide the original yaml file based on ingress-nginx ingress. If the ingress class is changed to nginx - ingress, can you tell me how to modify the conversion?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
    nginx.ingress.kubernetes.io/session-cookie-name: DVFP
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ui-ingress
  namespace: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: nginx-example.api.com
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 8080
        path: /nginx/ui(/|$)(.*)
        pathType: ImplementationSpecific
```
