### ISSUE TITLE
proxy_pass hard-coded to HTTP

### ISSUE THREAD

**Issue by jmastr** [nginxinc/kubernetes-ingress#61]
I have a setup in which I use SSL for inter-container communtication. To have the nginx-ingress-rc working I need to be able to set:
```
proxy_pass https://...
```
(not `http://`)

Since Kubernetes does not hold that information, my suggestion is: If a container opens port 443 (instead of 80 or whatever) we assume, that SSL is spoken.

For this suggestion I have already a patch. Let me know if you are interested in having it.

**Comment by pleshakov** [comment]
Hi @jmastr,

It's a feature that's important to add. Thanks for bringing it up. 

However, instead of making assumptions about backend containers, I'd rather explicitly define which backend services require SSL connections (we can use Annotations for that), like in the following example:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    nginx.org/ssl-backends: "tea-svc,coffee-svc"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 443
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 8443
```
