### ISSUE TITLE
Helm chart >0.10.4 not found

### ISSUE THREAD

**Issue by JuanSeBestia** [nginxinc/kubernetes-ingress#6147]
**Describe the bug**
I have a Kubernetes cluster with version 1.18.3, I want to install a NIC compatible with this. On the [documentation](https://docs.nginx.com/nginx-ingress-controller/technical-specifications/) said that 0.10.4 fit with my needs, but on the OCI repository are not charts available.

Searching on the OCI repo I saw this:
``` bash
skopeo list-tags docker://ghcr.io/nginxinc/charts/nginx-ingress

    "Tags": [
        "0.0.0-edge",
        "0.16.2",
        "artifacthub.io",
        "0.17.0",
        "0.17.1",
        "0.18.0",
        "0.18.1",
        "1.0.0",
        "1.0.1",
        "1.0.2",
        "1.1.0",
        "1.1.1",
        "1.1.2",
        "1.1.3",
        "1.2.0",
        "1.2.1",
        "1.2.2",
        "1.3.0",
        "1.3.1"
    ]
```

**To Reproduce**
```bash
helm pull oci://ghcr.io/nginxinc/charts/nginx-ingress --version 0.10.4
>>No results found
```

**Expected behavior**
Be available all the charts documented

**Your environment**

- Version of the Ingress Controller - CHART version 0.10.4
- Version of Kubernetes 1.18.3
- Kubernetes platform bare metal
- Using NGINX

**Comment by vepatel** [comment]
HI @JuanSeBestia, that version of chart was release before we switched to oci repo, you can try building it from source after checking out the corresponding tag or download it from https://github.com/nginxinc/helm-charts/tree/master/stable.

Our recommendation would be to use something more recent (both k8s and NIC) as that K8s is EOL'd a while back https://kubernetes.io/releases/

**Comment by JuanSeBestia** [comment]
Hi @vepatel, Thanks for your answer, I found available on repo on https://helm.nginx.com/stable. it works for me. would be wonderful found the other old versions on the new one repo, but is okay I understand is not desired support too old versions.

I want to update my K8s, but for the moment I can't, I hope do it soon.

FYI. I want the repo because I want to use Kustomize to install it like this, also with OCI is a little difficult but possible

```yaml
# to install use --enable-helm
# kubectl kustomize . --enable-helm | kubectl apply -f -
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
## helm install nginx-ingress nginx-stable/nginx-ingress --namespace nginx-ingress-system --version 0.10.4
helmCharts:
  - name: nginx-ingress
    repo: https://helm.nginx.com/stable
    releaseName: cloud-connect-nginx
    version: 0.10.4

resources:
  # Chart not install the CRDs :(, maybe because is old
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.12.4/deployments/helm-chart/crds/appprotect.f5.com_aplogconfs.yaml
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.12.4/deployments/helm-chart/crds/appprotect.f5.com_appolicies.yaml
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.12.4/deployments/helm-chart/crds/appprotect.f5.com_apusersigs.yaml
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.12.4/deployments/helm-chart/crds/k8s.nginx.org_globalconfigurations.yaml
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.12.4/deployments/helm-chart/crds/k8s.nginx.org_policies.yaml
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.12.4/deployments/helm-chart/crds/k8s.nginx.org_transportservers.yaml
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.12.4/deployments/helm-chart/crds/k8s.nginx.org_virtualserverroutes.yaml
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.12.4/deployments/helm-chart/crds/k8s.nginx.org_virtualservers.yaml
```
