### ISSUE TITLE
VirtualServer with SSL services?

### ISSUE THREAD

**Issue by trungdq88** [nginxinc/kubernetes-ingress#620]
**Is your feature request related to a problem? Please describe.**
Currently, I don't see there is an option to create a `VirtualServer` with secured service. When define the upstream with port 443, I see this error:
![image](https://user-images.githubusercontent.com/4214509/61196963-b59a3200-a704-11e9-914d-1274bd8f3832.png)

**Describe the solution you'd like**
Be able to use SSL services in `VirtualServer`, maybe use the same annotation as in `Ingress`?
```yml
apiVersion: k8s.nginx.org/v1alpha1
kind: VirtualServer
metadata:
  name: secure-app-virtual-server
  annotations:
    nginx.org/ssl-services: "secure-app"
spec:
  host: example.com
  tls:
    secret: secure-app-certs
  upstreams:
  - name: secure-app
    service: secure-app
    port: 443
  routes:
  - path: /
    upstream: secure-app
```
