### ISSUE TITLE
Support Websocket upstream for VirtualServer

### ISSUE THREAD

**Issue by trungdq88** [nginxinc/kubernetes-ingress#623]
**Is your feature request related to a problem? Please describe.**
Currently, I can not define a WebSocket upstream with `VirtualServer`.

**Describe the solution you'd like**
I think WebSocket should be supported by default, or opt-in like this:
```yaml
apiVersion: k8s.nginx.org/v1alpha1
kind: VirtualServer
metadata:
  name: hac-virtual-server
spec:
  host: {{ .Values.appDomain }}
  upstreams:
  - name: hac-autocomplete-upstream
    service: autocomplete
    port: 8374
    websocket: true
    lb-method: ip_hash
```
