### ISSUE TITLE
Cannot proxy docker registry2 service

### ISSUE THREAD

**Issue by ycyin** [nginxinc/kubernetes-ingress#6291]
Unable to successfully proxy docker registry2 service ([Distribution Registry](https://distribution.github.io/distribution/)) using Ingress through ingress-controller, using NodePort type Service can work normally, using Ingress cannot work properly, and in I also have no problems with another cluster (using kubernetes/nginx-ingress). Did I miss something?

![image](https://github.com/user-attachments/assets/e832306d-6b3a-4ca1-ac4e-c30b48fd913e)

Cluster: K8s v1.17
ingress controller：nginx/nginx-ingress:1.12.4
helm chart: nginx-ingress-0.10.4

/etc/nginx/conf.d/default-registry.conf：
```nginx
# configuration for default/registry

upstream default-registry-registry.custom.be-registry-service-5000 {
        zone default-registry-registry.custom.be-registry-service-5000 256k;
        random two least_conn;

        server 102.0.38.140:5000 max_fails=1 fail_timeout=10s max_conns=0;

}


server {

        listen 80;

        server_tokens off;

        server_name registry.custom.be;

        set $resource_type "ingress";
        set $resource_name "registry";
        set $resource_namespace "default";

        location / {
                set $service "registry-service"; 


                proxy_http_version 1.1;


                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                proxy_send_timeout 60s;
                client_max_body_size 1024m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;

                proxy_pass http://default-registry-registry.custom.be-registry-service-5000;

        }
}

```

deployment.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registry
    spec:
      affinity: {}
      containers:
      - env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        - name: REGISTRY_HTTP_SECRET
          value: 4f3c2e1a5b6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2
        image: registry:2.7.1
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 5000
          name: 5000tcp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-images
        - mountPath: /auth
          name: registry-auth
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: registry-images
        persistentVolumeClaim:
          claimName: pvc-registry-images2
      - name: registry-auth
        secret:
          defaultMode: 420
          secretName: registry-htpasswd
```       

service and ingress：
```
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: default
spec:
  ports:
  - name: port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  annotations:
    nginx.org/client-max-body-size: 1024m
  name: registry
  namespace: default
spec:
  rules:
  - host: registry.custom.be
    http:
      paths:
      - backend:
          serviceName: registry-service
          servicePort:  5000
        path: /
```
