### ISSUE TITLE
Introduce annotation for rewrite rule

### ISSUE THREAD

**Issue by jmastr** [nginxinc/kubernetes-ingress#63]
See #60

Instead of hard-coding the rewrite rule one could introduce a further annotation like in #61.

**Comment by pleshakov** [comment]
I think we can add something like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    nginx.org/rewrites: "serviceName=tea rewrite=/;serviceName=coffee-svc rewrite=/beans/"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea/
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee/
        backend:
          serviceName: coffee-svc
          servicePort: 80
```
Requests to the tea service are rewritten as follows:

- /tea -> gets redirected to /tea/ first
- /tea/ -> /
- /tea/abc -> /abc

Requests to the coffee service are rewritten as follows:

- /coffee -> gets redirected to /coffee/ first
- /coffee/ -> /beans/
- /coffee/abc -> /beans/abc

To accomplish that the following NGINX configuration can be used:
```nginx

location /tea/ {
  proxy_pass http://tea-svc/;
}

location /coffee/ {
  proxy_pass http://coffee-svc/beans/;
}
```
See http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass for details.

However, rewrites don't guarantee that the application will work. Often applications return web pages with absolute links so that the rewriting of response bodies is also necessary.
