### ISSUE TITLE
TCP/UDP Load Balancing

### ISSUE THREAD

**Issue by azelezni** [nginxinc/kubernetes-ingress#637]
I've followed the guide for [TCP/UDP Load Balancing](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/tcp-udp) and after many hours still couldn't get it to work.

I have a Kubernetes cluster deployed using Rancher RKE, and Nginx ingress installed manually.

I want to expose a PostgreSQL deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:10.6
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: tcp
  selector:
    app: postgresql
```

I've configured nginx-ingerss daemonSet ports:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx/nginx-ingress:1.5.0-alpine
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: postgres
          containerPort: 15432
          hostPort: 15432
        - name: mongo
          containerPort: 17017
          hostPort: 17017
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
          - -health-status
```
And nginx-ingress service:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: nginx-ingress
```
And finally I updated the configMap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  http-snippets: |
    set_real_ip_from 10.127.0.0/16;
    real_ip_header X-Forwarded-For;
  stream-snippets: |
    upstream postgres-amber-tcp {
        server postgresql.amber.svc.cluster.local:5432;
    }
    server {
        listen 5432;
        proxy_pass postgres-amber-tcp;
    }

```

And just for good measure I restarted the nginx-ingress pods.

When I try to access the port `nc -nv 127.0.0.1 5432` from any node I just get connection refused, but ports 80 & 443 work fine.

Also, this line from the guide `Make sure to expose port 5353 of the Ingress controller both for TCP and UDP traffic.` could be explain batter, should I expose both the container ports and the service? just the service? just the container? a little explanation would be great.
