### ISSUE TITLE
nginx.org/server-snippets location not whitelisting single ip addresses to specific location

### ISSUE THREAD

**Issue by pkelleratwork** [nginxinc/kubernetes-ingress#656]
**Describe the bug**
trying to whitelist three ranges and two sever specific ips outside the three ranges. ranges works, specific ips are not.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whitelist-ingress
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/proxy-read-timeout: "7200"
    ingress.kubernetes.io/proxy-send-timeout: "7200"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/session-cookie-name: "route"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "xxx.xxx.xxx.xxx/24,yyy.yyy.yyy.yyy/24,zzz.zzz.zzz.zzz/24"
    nginx.org/server-snippets: |
      location / {
        allow  aaa.aaa.aaa.aaa;
		allow  bbb.bbb.bbb.bbb; 
        deny all;
      }
spec:
  tls:
    - hosts:
      - yadayada.website.com
      secretName: tls-secret
  rules:
  - host: yadayada.website.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
      - path: /api
        backend:
          serviceName: api
          servicePort: 80
```

**To Reproduce**
1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**
the ranges and specific ip should pass thru

**Your environment**
* Version of the Ingress Controller - release version or a specific commit v0.25
* Version of Kubernetes aws 1.12
* Kubernetes platform (e.g. Mini-kube or GCP) aws
* Using NGINX or NGINX Plus nginx

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by pkelleratwork** [comment]
nvm - i figured it out. i added the specific ip addys to the range - 
```
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/proxy-read-timeout: "7200"
    ingress.kubernetes.io/proxy-send-timeout: "7200"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/session-cookie-name: "route"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "xxx.xxx.xxx.xxx/24,yyy.yyy.yyy.yyy/24,zzz.zzz.zzz.zzz/24,aaa.aaa.aaa.aaa,bbb.bbb.bbb.bbb "
```
