### ISSUE TITLE
Prevent a VirtualServerRoute from being used multiple times in a Virtual Server to avoid reload failure

### ISSUE THREAD

**Issue by haywoodsh** [nginxinc/kubernetes-ingress#6611]
**Is your feature request related to a problem? Please describe.**

Currently, NIC allows a configuration that results in generating the same location block /coffee and the same upstream twice, which causes NGINX to trigger a "duplicate upstream" error upon reload:
```
- path: /coffee
  route: coffee/coffee
- path: /
  route: coffee/coffee
```

Disallow a VSR being used mulitple times to prevent reload failure
**Describe the solution you'd like**
Prevent 
**Describe alternatives you've considered**
(WIP)

**Additional context**
(WIP)

**Comment by haywoodsh** [comment]
Another [emerg] error can also be caused by different VSRs (`coffee/coffee` and `coffee/coffee2`) having the same location path `/coffee`:


```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
  namespace: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  routes:
  - path: /
    route: coffee/coffee2
  - path: /tea
    route: tea/tea
  - path: /coffee
    route: coffee/coffee

```

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffee
  namespace: coffee
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  subroutes:
  - path: /coffee
    action:
      pass: coffee

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffee2
  namespace: coffee
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  subroutes:
  - path: /coffee
    action:
      pass: coffee
```


```
  Warning  AddedOrUpdatedWithError  12s                    nginx-ingress-controller  Configuration for cafe/cafe was added or updated ; but was not applied: error reloading NGINX for VirtualServer cafe/cafe: nginx reload failed: command /usr/sbin/nginx -s reload -e stderr stdout: ""
stderr: "2025/12/11 01:06:55 [notice] 41#41: js vm init njs: 0000AAAAE2DFEC00\n2025/12/11 01:06:55 [emerg] 41#41: duplicate location \"/coffee\" in /etc/nginx/conf.d/vs_cafe_cafe.conf:100\n"
```
