### ISSUE TITLE
Valid webpage certificate returns SSL_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by Mr-Reca** [nginxinc/kubernetes-ingress#683]
**Describe the bug**
I configured an Ingress to redirect to another website (Google for testing it), and it's returning HTTP 502 Bad Gateway. I use a self-signed Secret for TLS.

**To Reproduce**
1. Deploy the following YAML file
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redirect-ingress
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.google.com
spec:
  tls:
  - hosts:
    - google.test.<my-domain>.com
    secretName: redirect-secret
  rules:
  - host: google.test.<my-domain>.com
    http:
      paths:
      - path:
        backend:
          serviceName: default-backend
          servicePort: 80
```

I also tried with the property:
```
nginx.ingress.kubernetes.io/ssl-redirect: "false"
```

nginx-ingress works if I'm deploying my services (an nginx, a hello-world app, etc.).

**Expected behavior**
Expected redirection to https://google.com

**Your environment**
* Version of the Ingress Controller - latest version cloned yesterday (nginx-ingress:edge)
* Version of Kubernetes - v1.15.3
* Kubernetes platform (e.g. Mini-kube or GCP) - Local k8s cluster
* Using NGINX or NGINX Plus - NGINX

**Additional context**
Output of  ```kubectl log <nginx-ingress> -n nginx-ingress```
```
2019/09/05 11:24:42 [error] 203#203: *99 connect() failed (111: Connection refused) while connecting to upstream, client: <my-ip>, server: google.test.<my-domain>.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8181/", host: "google.test.<my-domain>.com"
172.28.0.247 - - [05/Sep/2019:11:24:42 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0" "-"

```

**Comment by Rulox** [comment]
Hi @Mr-Reca 

I see you are using the annotation `nginx.ingress.kubernetes.io/permanent-redirect`. That [annotation](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md) is part of the [Community K8S Ingress Controller](https://github.com/kubernetes/ingress-nginx) which is different from this project.

[Here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md) you can find the differences between the two projects and how to tell which one you are using.

If you are using the Community one, I suggest you to open the issue there. If you are using our NGINX Ingress Controller, I am afraid that annotation won't work. The annotations that we support are detailed [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md).

Let me know if there's anything else I can do.

**Comment by Mr-Reca** [comment]
Hi @Rulox 

The repo I cloned is this one (nginxinc/kubernetes-ingress). I realized I read the K8s documentation, and I have to read this one. Thank you for the link.

I can try (as a bugfix) to deploy another nginx service and write a nginx.conf with the redirection. Or is there a way to do it?

Is it possible to add this annotation as a feature in this project?

Thank you so much for your help

**Comment by Rulox** [comment]
Hey @Mr-Reca no problem, I know it's a bit confusing.

We are not planning to add more annotations for now, as we are focusing in the VirtualServer and VirtualServerRoute CRDs.

However, yes, there are ways you can achieve what you are trying. Based on your example, you can use location snippets [annotation](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md#snippets-and-custom-templates):

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redirect-ingress
  annotations:
    nginx.org/location-snippets: return 301 https://google.com;
spec:
  tls:
  - hosts:
    - google.test.<my-domain>.com
    secretName: redirect-secret
  rules:
  - host: google.test.<my-domain>.com
    http:
      paths:
      - path:
        backend:
          serviceName: default-backend
          servicePort: 80
```

Note the `nginx.org/location-snippets: return 301 https://google.com;` annotation. This will add a `return 301 https://google.com` to all the location blocks of your ingress resource ( in your case is only one, with `/`)

Would this approach work for you?
