### ISSUE TITLE
502 Bad Gateway issue with some containers

### ISSUE THREAD

**Issue by lsparey** [nginxinc/kubernetes-ingress#685]
I'm getting a bad gateway response using nginx ingress with containers running a C++ REST API app

1. Setup nginx ingress using the [install guide](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md)

2. Apply the following config files
`$ kubectl apply -f common/ns-and-sa.yaml`
`$ kubectl apply -f common/default-server-secret.yaml`
`$ kubectl apply -f common/nginx-config.yaml`
`$ kubectl apply -f deployment/nginx-ingress.yaml`
`$ kubectl apply -f service/loadbalancer.yaml`

3. Deploy a [hello world app written in C++](https://github.com/lsparey/hello-cpprest) which listens on http://localhost:8888/ and replies with a simple JSON response

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-cpprest
  name: hello-cpprest-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-cpprest
    spec:
      containers:
      - image: lsparey/hello-cpprest:1.00
        name: hello-cpprest
        ports:
        - containerPort: 8888
        resources: {}
```
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-cpprest
  name: hello-cpprest-service
spec:
  ports:
  - port: 8888
  selector:
    app: hello-cpprest
```

4. Create the ingress resource
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-cpprest
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hello-cpprest.localtest.me
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-cpprest-service
          servicePort: 8888
```

5. Requests to http://hello-cpprest.localtest.me return 502 Bad Gateway from nginx

* Docker desktop for Windows (2.1.0.2) running Kubernetes (1.14.6)
* image: nginx/nginx-ingress:edge

Ingress controller logs report 
`connect() failed (111: connection refused) while connecting to upstream`
Although everything else, such as the pod IP, looks correct

Things I've tried:
A. Port forwarding to the pod -> 8888:8888 works without any issues
B. Nginx running on my desktop (with many different configs trying to match what is used within in the ingress controller) pointing to the port forwarded pod in kubernetes always works without issue (I've seen some cases of localhost resolving to IPV6 and then failing to connect)
C. Creating a service and manual endpoint within kubernetes pointing to an instance of the app running on my desktop works without issue going through the ingress controller
D. Setting the image of the pod to a node/express based container which does the same thing works end to end without any issues
`$ kubectl set image deployment/hello-cpprest-deployment hello-cpprest=lsparey/hello-express:1.00`
And immediately breaks again when switching the image back
E. Setting the image of the container to another C++ (Boost Beast) based app also fails
F. Kuberetes version of nginx ingress controller (default setup in install guide) has the same issue - 502 from openresty
