### ISSUE TITLE
How would I implement customer DH parameters for DHE ciphers

### ISSUE THREAD

**Issue by df-mreidel** [nginxinc/kubernetes-ingress#69]
I'm asking upfront before creating a pull-request. We need to pass in custom DH parameters by supplying `ssl_dhparam <file>` to the nginx config. I could create a patch that simply supports setting `ssl_dhparam` and it would then require the user to make sure he mounts `<file>` into the container at the given location.

On the other hand, you might prefer that the value to `ssl-dhparam`/`nginx.org/ssl-dhparam` is not a filename, but rather the name of a namespace/secret and we look for the key dhparam.pem - very much like certificates are handled right now. So let's explain by examples.

# Variant 1: filename
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress
  namespace: kube-system
data:
  ssl-dhparam: ciphers/dh4096.pem
```
And then mount that file to `/etc/nginx/ciphers/dh4096/pem` in the DaemonSet or Deployment

# Variant 2: reference to a secret
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress
  namespace: kube-system
data:
  ssl-dhparam: kube-system/dh-params
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: dh-params
  namespace: kube-system
type: Opaque
data:
  dhparam.pem: ABC==
```

The second variant would require the controller to automagically create the file from the reference, but it would also allow for a seamless update of these parameters - for whatever reason.

Of course variant 1 is easier to implement, so I would like to know, which version you prefer?

**Comment by pleshakov** [comment]
It'd be great if you could implement the Variant 2!

For future extensions that support similar directives that require a file, we can have a similar approach deploying the file in a Kubernetes resource and we can reuse this implementation.

It makes more sense to me to deploy a dh-params file in a ConfigMap resource, since this file is not secret.

**Comment by df-mreidel** [comment]
Referencing a ConfigMap from inside a ConfigMap seems rather unnecessary. Shall I then treat the value as the content of the file to write? Like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress
  namespace: kube-system
data:
  ssl-dhparam: |
    -----BEGIN DH PARAMETERS-----
    ABC==
    -----END DH PARAMETERS-----
```
Are you really sure dhparams don't need to be kept secret?
