### ISSUE TITLE
[Bug]: VirtualServer > Action.Return.type overwritten when URI contains an extension

### ISSUE THREAD

**Issue by yaronuliel** [nginxinc/kubernetes-ingress#6943]
### Version

edge

### What Kubernetes platforms are you running on?

Minikube

### Description: 
When defining a `VirtualServer` resource - you can set a preconfigured response - one of the fields it supports is `type` which according to the [docs](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#action:~:text=code%3A%20200-,type%3A%20text/plain,-body%3A%20%22Hello) sets "The MIME type of the response"

In fact - it only sets the `default_type` ([nginx docs](https://nginx.org/en/docs/http/ngx_http_core_module.html#default_type)) ([location in source code](https://github.com/nginxinc/kubernetes-ingress/blob/8e28c37617cbe33fe37f25876179f89eb3529948/internal/configs/virtualserver.go#L2277)) - the implications are that despite setting the desired `Content-Type` value - when the URI ends with an extension - nginx "guesses" the `Content-Type` based on the map in `/etc/nginx/mime.types`

### Expected Behavior
When defining a `type` in a route with `return` action - it should always return that type as `Content-Type`, and should ignore not use the extension in the URI to assume the content type

### Steps To Reproduce:

1. Apply this following `VirtualServer` yaml (set `host` according to your installation):

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtual-server-bug-demo
spec:
  host: vs-bug-demo.localhost
  routes:
  - path: /
    action:
        return:
          body: "Not Found"
          code: 404
          type: text/plain
```

2. Browse to http://vs-bug-demo.localhost/not-found - All good, response is 404 with content type`text/plain` 
3. Browse to http://vs-bug-demo.localhost/not-found/somelinkwith.mp4 - Server response with `Content-type: video/mp4` (body still contains the string "Not Found" - which cause the browser to show an invalid video player)

**Comment by jjngx** [comment]
@yaronuliel could you please share generated NGINX config? This will help us investigate the issue.

**Comment by yaronuliel** [comment]
@jjngx 
The applied yaml was 
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtual-server-bug-demo
spec:
  host: vs-bug-demo.localhost
  routes:
  - path: /
    action:
        return:
          body: "Not Found"
          code: 404
          type: text/plain
```

The created resource yaml is:

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"k8s.nginx.org/v1","kind":"VirtualServer","metadata":{"annotations":{},"name":"virtual-server-bug-demo","namespace":"vs-demo"},"spec":{"host":"vs-bug-demo.localhost","routes":[{"action":{"return":{"body":"Not Found","code":404,"type":"text/plain"}},"path":"/"}]}}
  creationTimestamp: "2024-12-24T18:48:42Z"
  generation: 1
  name: virtual-server-bug-demo
  namespace: vs-demo
  resourceVersion: "424986"
  uid: ec36b225-364a-4761-a755-6fde9c4ec690
spec:
  host: vs-bug-demo.localhost
  routes:
  - action:
      return:
        body: Not Found
        code: 404
        type: text/plain
    path: /
status:
  externalEndpoints:
  - hostname: localhost
    ports: '[80,443]'
  message: 'Configuration for vs-demo/virtual-server-bug-demo was added or updated '
  reason: AddedOrUpdated
  state: Valid
```


The config generated in the nginx controller in `/etc/nginx/conf.d/vs_vs-demo_virtual-server-bug-demo.conf` is:

```
server {
    listen 80;
    listen [::]:80;


    server_name vs-bug-demo.localhost;

    set $resource_type "virtualserver";
    set $resource_name "virtual-server-bug-demo";
    set $resource_namespace "vs-demo";

    server_tokens "on";


    location @return_0 {
        default_type "text/plain";

        # status code is ignored here, using 0
        return 0 "Not Found";
    }



    location / {
        set $service "";


        error_page 418 =404 "@return_0";
        proxy_intercept_errors on;
        proxy_pass http://unix:/var/lib/nginx/nginx-418-server.sock;
        set $default_connection_header close;
    }
}
```

The problem caused by using `default_type` - which means that nginx will "guess" the content type if the request has an extension. and `text/plain` will only be used as default (when there is no extension, or the extension is not in nginx's mapping)
