### ISSUE TITLE
Add sizeLimit to emptyDir configuration

### ISSUE THREAD

**Issue by atombrella** [nginxinc/kubernetes-ingress#7053]
**Is your feature request related to a problem? Please describe.**

https://github.com/nginxinc/kubernetes-ingress/blob/93eec0dc5998872a2ac8552ec5034a6f96c5bcde/charts/nginx-ingress/templates/_helpers.tpl#L352

I think it'd be nice if these emptyDir had a sizeLimit (maybe configurable). It's supported since Kubernetes 1.22

https://kubernetes.io/docs/concepts/storage/volumes/?emptydir#emptydir

```yaml
{{- if eq (include "nginx-ingress.readOnlyRootFilesystem" .) "true" }}
- name: nginx-etc
  emptyDir: {}
- name: nginx-cache
  emptyDir: {}
- name: nginx-lib
  emptyDir: {}
- name: nginx-log
  emptyDir: {}
{{- end }}
```

**Describe the solution you'd like**

Either maybe some sane defaults. One volume is used for configuration files that shouldn't take up much space (10Mb seems like a good value). For the others, I'm not sure what would be good.

**Describe alternatives you've considered**

I don't like to edit anything else than value-files from the Helm chart.
