### ISSUE TITLE
store TLS secret in any namespace

### ISSUE THREAD

**Issue by aminebizid** [nginxinc/kubernetes-ingress#706]
Is it possible to have my tls secret in any other namespace than the POD namespace?
```
  tls:
  - hosts:
    - sslexample.foo.com
    secretName: any_namespace/testsecret-tls
```
