### ISSUE TITLE
[Bug]: Bad ApiKey policy causing crashloopback and nginx pods to not work.

### ISSUE THREAD

**Issue by benshalev849** [nginxinc/kubernetes-ingress#7082]
### Version

3.7.0

### What Kubernetes platforms are you running on?

Openshift

### Steps to reproduce

We have been experimenting with the apiKey policy, when creating it wrong it causes an exception on the Nginx code and it to infinetly crash loop back.
The only fix to this is to completely delete the bad api key policy and roll out the pods, this is a major flaw and bug that can cause entire systems to go down.
This happens when the policy is defined wrong in a namespace that the nginx watches.

Steps to reproduce:
1) Create an Nginx IC and make it watch your wanted namespace
2) Create the following yaml:
```
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: test-crash
  namespace: <connected_namespace>
spec:
  apiKey:
    clientSecret: <some name does not matter>
```

Since there is no Supplied in (Which is not required in order to create the policy) this will cause the nginx to entirely crash and stop working causing downtime to all apps connected and a crashloopbackoff to those pods.
