### ISSUE TITLE
Enable CORS release capabilities in `kind: Ingress`

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#7089]
### Overview
When configuring CORS (Cross Origin Resource Sharing) in NGINX Ingress Controller today, it is possible through response and request header manipulation in VirtualServer

For example
```yaml
responseHeaders:
  add:
    - name: Access-Control-Allow-Credentials
      value: "true"
    - name: Access-Control-Allow-Headers
      value: "X-Forwarded-For"
    - name: Access-Control-Allow-Methods
      value: "PUT, GET, POST, OPTIONS"
    - name: Access-Control-Allow-Origin
      value: "*"
    - name: Access-Control-Max-Age
      value: "seconds"
```

The goal of this issue is to allow users to configure these same headers with `kind: Ingress`

### Acceptance Critera
- [ ] Expose annotations to configure CORS related headers
- [ ] Ensure annotations are validated
