### ISSUE TITLE
provide set of examples of very typical usecases

### ISSUE THREAD

**Issue by goodidea-kp** [nginxinc/kubernetes-ingress#732]
**Is your feature request related to a problem? Please describe.**

I need to redirect non-www to www.
How clear how to do it using annotations. Nothing is working for me.
Please help with examples.

**Describe the solution you'd like**
need more examples to cover typical use cases: redirect, rewrite, hande big file sizes etc

**Describe alternatives you've considered**

**Additional context**

**Comment by pleshakov** [comment]
@goodidea-kp 
Please see an example before:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.org/server-snippets: |
      server_name cafe.example.com;

      if ($host = cafe.example.com) {
        return 302 $scheme://www.cafe.example.com$request_uri;
      }
spec:
  tls:
  - hosts:
    - www.cafe.example.com
    secretName: cafe-secret
  rules:
  - host: www.cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```

Here we used `nginx.org/server-snippets` [annotation](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md) to configure a server_name and a redirect.

As a result, requests to https://cafe.example.com are redirected to https://www.cafe.example.com
