### ISSUE TITLE
How to create Custom Error Pages for 404, 503 errors?

### ISSUE THREAD

**Issue by jjburr** [nginxinc/kubernetes-ingress#752]
Is it possible to create a default backend for custom error pages like you can do with the community version of nginx ingress? https://kubernetes.github.io/ingress-nginx/examples/customization/custom-errors/

**Comment by pleshakov** [comment]
Hi @jjburr 

Unfortunately, it is not possible out of the box.

Using the server snippets annotation or configmap key -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md#snippets-and-custom-templates -- it is possible to insert the error_page directives that can intercept errors and serve errors page from a dedicated service. 

In the example below we intercept 404 errors from tea and coffee services and then serve an error page from the `errors-svc` service in the default namespace :
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/server-snippets: |
      proxy_intercept_errors on;
      error_page 404 = @errorpages;
      
      location @errorpages {
        proxy_set_header X-Code $status;
        proxy_pass http://errors-svc.default.svc.cluster.local;
      }
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```

Note that the original status code is passed in the `X-Code` header to the errors-svc service.

See also  http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page and http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors
