### ISSUE TITLE
http-snippet is not being loaded

### ISSUE THREAD

**Issue by itninja-hue** [nginxinc/kubernetes-ingress#759]
**Describe the bug**
anything passed in http-snippet in the configmap is not being loaded inside nginx.conf

**To Reproduce**
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
  data:
  proxy-protocol: "True"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "0.0.0.0/0"
  http-snippet: |
    server {
      listen 80;
      server_name _;
      if ($http_x_forwarded_proto = 'http'){
        return 301 https://$host$request_uri;
      }
    }
````

**Expected behavior**
configuration get loaded.

**Your environment**
* Version of the Ingress Controller - 1.5.7
* Version of Kubernetes 1.13
* Kubernetes platform EKS
* Using NGINX 

**Additional context**
I am terminating ssl inthe elb level.

**Comment by Rulox** [comment]
Hi @itninja-hue 

I can see a typo in your configmap, it should be `http-snippets` notice the last `s`, and you have `http-snippet` in singular. Could you try again adding a `s` and let me know if this works?

Additionally, I am sure is just an error of copy/paste, but `data` key is not indented properly. Your Configmap should look like this:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  proxy-protocol: "True"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "0.0.0.0/0"
  http-snippets: |
    server {
      listen 80;
      server_name _;
      if ($http_x_forwarded_proto = 'http'){
        return 301 https://$host$request_uri;
      }
    }
```
