### ISSUE TITLE
document auth_request example

### ISSUE THREAD

**Issue by nabheet** [nginxinc/kubernetes-ingress#873]
**Is your feature request related to a problem? Please describe.**
I cannot find an example of using `auth_request` module http://nginx.org/en/docs/http/ngx_http_auth_request_module.html with this ingress controller. We have security set up similar to https://github.com/nginxinc/nginx-ldap-auth. We also have multiple locations exposed in the same server. And multiple domains/servers on the same port (443) with TLS.

**Describe the solution you'd like**
I would like to understand how to combine master/minion set up with the auth_request module.

**Describe alternatives you've considered**
Cannot find any documentation for the ingress controller. Currently we are using nginx docker images directly with the nginx.conf mounted into the container.

**Comment by Rulox** [comment]
Hi @nabheet !

There are a lot of directives in NGINX configuration and it is impossible for us to provide examples in the documentation for all of them, I hope you can understand.

However, your use case is valid. In your case, would [location/server snippets annotations](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#snippets-and-custom-templates) work for your Ingress (master and minion) Resources? With these snippets you can add any type of configuration to your servers (like a new /auth location) and your locations (like the `auth_request` directive you need).

For instance, in an Ingress Resource like this one (note annotations):
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.org/location-snippets: |
      auth_request /auth;
    nginx.org/server-snippets: |
      location = /auth {
        return 200;
      }
  name: cafe-ingress
  namespace: default
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - backend:
          serviceName: tea-svc
          servicePort: 80
        path: /tea
      - backend:
          serviceName: coffee-svc
          servicePort: 80
        path: /coffee
  tls:
  - hosts:
    - cafe.example.com
    secretName: cafe-secret
```

The NGINX config in the Ingress Controller for this particular server `cafe.example.com` would be (I removed useless generated config for simplicity):

```nginx
server {
	listen 80;
	listen 443 ssl;
        # generated config here...
	server_tokens "on";
	server_name cafe.example.com;
	status_zone cafe.example.com;

	location = /auth {
	  return 200;
	}

	location /tea {
		proxy_http_version 1.1;
		auth_request /auth;
                 # generated config here...
		proxy_pass http://default-cafe-ingress-cafe.example.com-tea-svc-80;
	}
	location /coffee {
		proxy_http_version 1.1;
		auth_request /auth;
                 # generated config here...
		proxy_pass http://default-cafe-ingress-cafe.example.com-coffee-svc-80;
	}
}
```

Note that snippets must be valid NGINX config. If the config is not valid, NGINX will fail to reload and you will see an error in the Ingress Controller pod logs.

Let me know if this would work for you, thanks!
