### ISSUE TITLE
Basic Auth Annotations Changed?

### ISSUE THREAD

**Issue by plainlystated** [nginxinc/kubernetes-ingress#879]
**Describe the bug**
Basic auth annotations no longer working (at GKE).  Have the annotations changed?

**To Reproduce**
1. apply annotations (below)
2. curl the ingress IP

**Expected behavior**
I expect these annotations to enable & require basic-auth on this ingress object.  This manifest worked with an older version of the helm library (chart: nginx-ingress-1.27.0, app: 0.26.1):
```
annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
```

I've also tried with the annotations omitting "nginx." (eg `ingress.kubernetes.io/auth-type: basic`).

I have the basic-auth secret in both the nginx-ingress namespace, and the namespace of my ingress resource.

**Your environment**
On GKE, with the latest stable ingress from helm:
```
nginx@nginx-ingress-nginx-ingress-7f4fdc49d9-59pnl:/$ /nginx-ingress --version
Version=1.6.3 GitCommit=b9378d56
```

**Additional context**
Add any other context about the problem here. Any log files you want to share.
