### ISSUE TITLE
Redirect to HTTPS in ConfigMap does not take effect

### ISSUE THREAD

**Issue by darren-teo** [nginxinc/kubernetes-ingress#884]
**Describe the bug**
I am using nginx with virtual server. I have set both ```redirect-to-https:"true"``` and ```ssl-redirect: "true"``` in the configmap. However the redirect doesn't take effect. Is this the expected behaviour with virtual servers?

**To Reproduce**
1. Apply configmap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-cm
  namespace: default
data:
  http2: "true"
  redirect-to-https: "true"
  ssl-redirect: "true"
  ssl-protocols: TLSv1.2 TLSv1.3
  ssl-prefer-server-ciphers: "true"
  ssl-ciphers: ECDH+aRSA+AESGCM:ECDH+aRSA+SHA384:ECDH+aRSA+SHA256:ECDH:EDH+CAMELLIA:EDH+aRSA:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED:!ECDSA
  set-real-ip-from: 0.0.0.0/0
  real-ip-header: X-Forwarded-For
```
2. Configmap update applied at pod:
```I0313 03:54:54.840639       1 event.go:255] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"default", Name:"nginx-ingress-cm", UID:"4707c477-73dc-4dcf-89c7-8958ad52fbf3", APIVersion:"v1", ResourceVersion:"1841609", FieldPath:""}): type: 'Normal' reason: 'Updated' Configuration from default/nginx-ingress-cm was updated```
3. HTTP is still accessible:
```
$ curl -I http://example.example.com
HTTP/1.1 200 OK
Server: nginx/1.17.9
Date: Fri, 13 Mar 2020 04:19:07 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Frame-Options: ALLOW-FROM
Vary: Accept-Encoding
```
**Your environment**
* Version of the Ingress Controller - 1.6.3-alpine
* Version of Kubernetes: v1.16.6
* Using NGINX

**Comment by pleshakov** [comment]
Hi @darren-teo 

For VirtualServer, it is necessary to use the `redirect` field to configure TLS redirects. Please see https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserver-tls

Also, here https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#customization-via-configmap you will find a list of the ConfigMap keys that don't apply for VirtulaServers.

**Comment by darren-teo** [comment]
Thank you. However, i find the documentation is not clear and concise. Redirection works now after adding the following to VirtualServer configuration:
```
  tls:
    basedOn: scheme
    redirect:
      code: 301
      enable: true
    secret: top-tls-secret
```
I notice from this link provided, https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#customization-via-configmap, ```hsts``` is not supported at the configMap. Where do I define this in VirtualServer?
