### ISSUE TITLE
Set default service for failed requests in ConfigMap

### ISSUE THREAD

**Issue by achetronic** [nginxinc/kubernetes-ingress#892]
**The problem**
I am part of a team that are developing some microservices with kubernetes. The problem is when a service fails and NGINX ingress controller shows that ugly page where we would like to show our ones. We have several ingress (1 per service) managing subdomains with let's encrypt certificates and when a service is not available, we don't have any way to show a custom error page because Laravel can only show error pages when available, but, what if not? 

**The solution:** 
We developed a microservice just with the mission to show personalized error pages and would like to set a default service to throw all requests that can not be proccessed by the service the user is asking for. Like a type of general config annotation or tag in configMap or something like it with the name of default service.

Aha! Link: https://nginx.aha.io/features/IC-106

**Comment by Rulox** [comment]
Hi @achetronic 

I think what you are looking for are error pages (instead of the default backend). There are 2 possibilities here:

1. Use [location or server snippets](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#snippets-and-custom-templates) in your Ingress Resource annotations in order to add some NGINX Configuration snippets using the [error page directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page). Check the following example:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-with-annotations
  annotations:
    nginx.org/server-snippets: |
        error_page 500 /500_error.php;  
        error_page 401 =301 http://example.com/forbidden.html;
spec:
  rules:
  - host: cafe.example.com
    http:
. . . etc
```
With this configuration for example, if your service responds to NGINX with a 500, NGINX will redirect the request to `500_error.php`. Additionally, it is possible to redirect the request to an external URL, check the example and how I've set that any 401 should return a 301 redirect to `http://example.com/forbidden.html;`.

As you say you have 1 ingress per service, I think this is the best approach for you.


2. Alternatively, instead of using Ingress Resources, try our VirtualServer and VirtualServerRoute CRDs, they define the [errorPages feature](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs-web/configuration/virtualserver-and-virtualserverroute-resources.md#errorpage). However, this is only available in the `edge` version of the Ingress Controller and will be part of the next release 1.7.0 (target is April for the next release). Learn more about our release process [here](https://github.com/nginxinc/kubernetes-ingress#nginx-ingress-controller-releases).

Let me know if this makes sense, thanks!
