### ISSUE TITLE
Customize Ingress to use specific ssl ciphers

### ISSUE THREAD

**Issue by dhatri308** [nginxinc/kubernetes-ingress#922]
We are trying to customize our Ingress resource. I do not see an annotation to add ssl ciphers at ingress level. ssl ciphers belong to http context. We know that we can customize nginx using ConfigMap. However, we have a scenario where we bypass nginx but want to add ssl ciphers at Ingress level. Below is our ingress yaml, is there a way to add ssl ciphers ?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 
  namespace: ...
  labels:
    app: ...
    io.kompose.ingress: 
  annotations:
    nginx.org/ssl-services: ...
    nginx.org/server-snippets: |...
    nginx.org/location-snippets: |...
spec:
  tls:....
```
We tried adding it to server-snippets. We do see ciphers in server context in /etc/nginx/conf.d/  but when we run Nmap it does not return the updated list of ciphers.
We also have added ssl-ciphers in Nginx ConfigMap and see that /etc/nginx/nginx.conf has the updated ciphers in http context. However, we have one Ingress resource which bypasses nginx so it is not being applied.
