### ISSUE TITLE
Enable virtualserver traffic  rewrite to direct all non-www to www  

### ISSUE THREAD

**Issue by FourTimes** [nginxinc/kubernetes-ingress#923]
Hi,

Apologies is this is not the place for this question, but I can't seem to find an answer anywhere else. As the question states, I'm trying to redirect all traffic from example.com to www.example.com using an Ingress resource on Kubernetes. I'd like to avoid having to use and configure NGINX

**Comment by ksummersill2** [comment]
@FourTimes There is actually an annotation that you can use per the documentation. However. I am having issues myself getting the actual annotations to work. 
[https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/]

**Comment by pleshakov** [comment]
Hi @FourTimes 

Unfortunately, It is not supported in the Ingress resource.

However, it is possible to configure a redirect  if you create a VirtualServer resource:
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: example
spec:
  host: example.com
  routes:
  - path: /
    action:
      redirect:
        code: 302
        url: http://www.example.com
```
Please see the doc  https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#action-redirect
