### ISSUE TITLE
Support for k8s 1.18 Ingress Class?

### ISSUE THREAD

**Issue by TheSithPadawan** [nginxinc/kubernetes-ingress#924]
How will nginx support the Ingress Class for the new k8s update?

```
apiVersion: "networking.k8s.io/v1beta1"
kind: "IngressClass"
metadata:
  name: "external-lb"
spec:
  controller: "example.com/ingress-controller" --> how should we specify nginx ingress controller?
  parameters: --> what parameters are needed?
    apiGroup: "k8s.example.com/v1alpha"
    kind: "IngressParameters"
    name: "external-lb"
```
Thank you!
