### ISSUE TITLE
Disable permanent redirect 308 http to https leading to failure of ACME Challenge

### ISSUE THREAD

**Issue by siddth09** [nginxinc/kubernetes-ingress#926]
**Is your feature request related to a problem? Please describe.**
We are using AKS, cert-manager and nginx-ingress controller to secure our ingress using certificates issued from ACME server. We are able to create account on our ACME server using the following YAML

```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ACME
spec:
  acme:
    server: https://<FQDN>/acme/directory
    email: a@a.com
    privateKeySecretRef:
      name: acme-secret
    solvers:
    - http01:
        ingress:
          class: nginx
```
But the issue arises while solving the challenge due to permanent redirect 308 from http to https. Ingress used is as below:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: ACME
spec:
  tls:
  - hosts:
    - test35-demo-aks-ingress.eastus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: test35-demo-aks-ingress.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: aks-helloworld
          servicePort: 80
        path: /(.*)
```

Error received using kubectl describe challenge -n cert-manager is
```
Status:
Presented: false
Processing: false
Reason: The remote server returned an error: (308) Permanent Redirect.
State: invalid
Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Normal Started 7m40s cert-manager Challenge scheduled for processing
```
Our logs show that server is trying to access the “ACME Server Trying to access challenge @ http://test35-demo-aks-ingress.eastus.cloudapp.azure.com/.well-known/acme-challenge/NGYzYmNlMWEtMzVlOC00YzU5LTgzNzUtMWQ1YjMwM2I1YWRm”. But due to permanent redirect from http to https we are unable to validate the above mentioned URL

**Describe the solution you'd like**
I should, be able to access http://test35-demo-aks-ingress.eastus.cloudapp.azure.com/.well-known/acme-challenge/NGYzYmNlMWEtMzVlOC00YzU5LTgzNzUtMWQ1YjMwM2I1YWRm to validate the challenge.

**Describe alternatives you've considered**
Used annotation nginx.ingress.kubernetes.io/ssl-redirect: "false" but this gives 404 error
