### ISSUE TITLE
Path forwarding not working 

### ISSUE THREAD

**Issue by saivikas408** [nginxinc/kubernetes-ingress#942]
Hello Guys 

I am using EKS cluster, i have installed nginx ingress controller by following this link
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/

 till now everything is fine all the pods are running fine

```
ubuntu@ip-172-31-7-200:~/kubernetes-ingress/deployments$ kubectl get all -n nginx-ingress
NAME                      READY   STATUS    RESTARTS   AGE
pod/nginx-ingress-8wkfp   1/1     Running   0          21h
pod/nginx-ingress-vpknq   1/1     Running   0          21h


NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)                      AGE
service/nginx-ingress   LoadBalancer   10.100.207.182   afe337d862763471da76327f6d00ecc9-1402291892.us-east-2.elb.amazonaws.com   80:32036/TCP,443:32695/TCP   21h

NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/nginx-ingress   2         2         2       2            2           <none>          21h
```

Now I have two apps in default namespace  and its respective services (nginx-deploy-main and my-service1)

and i have ingress resource as below

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: host-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: afe337d862763471da76327f6d00ecc9-1402291892.us-east-2.elb.amazonaws.com
    http:
      paths:
      - backend:
         serviceName: nginx-deploy-main
         servicePort: 80
        path: /
      - backend:
         serviceName: my-service1
         servicePort: 8080
        path: /test
```

when i access
http://afe337d862763471da76327f6d00ecc9-1402291892.us-east-2.elb.amazonaws.com/  --  No error i can see web page

when i access with below path --
http://afe337d862763471da76327f6d00ecc9-1402291892.us-east-2.elb.amazonaws.com/test
 i am getting 404 Not Found  --> i have path set as /test in ingress resource yaml.

My environment:  

Version of the Ingress Controller - release version or a specific commit : 

```
ubuntu@ip-172-31-7-200:~/kubernetes-ingress/deployments$ kubectl -n nginx-ingress exec -it nginx-ingress-8wkfp -- bash
nginx@nginx-ingress-8wkfp:/$ ./nginx-ingress -version
Version= GitCommit=

```
* Version of Kubernetes : v1.16.8-eks-e16311
* Kubernetes platform : Amazon EKS
* Using NGINX or NGINX Plus  : Nginx

plesae help me , am I missing some thing

**Comment by saivikas408** [comment]
when I tried to check the version of nginx-ingress , i got below output , version and gitcomit are empty !!
did i do any thing wrong while setting up controller., Please help me

```
ubuntu@ip-172-31-7-200:~/kubernetes-ingress/deployments$ kubectl -n nginx-ingress exec -it nginx-ingress-8wkfp -- bash
nginx@nginx-ingress-8wkfp:/$ ./nginx-ingress -version
Version= GitCommit=
```

**Comment by pleshakov** [comment]
Hi @saivikas408 

> when i access with below path --
http://afe337d862763471da76327f6d00ecc9-1402291892.us-east-2.elb.amazonaws.com/test
i am getting 404 Not Found --> i have path set as /test in ingress resource yaml.

Does `my-service1` expect requests to have a URI starting with `/test` or `/` ? If the latter is the case, you might need to use a rewrite annotation -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/rewrites - and update the path as well, as shown below:
```
annotations:
  nginx.org/rewrites: "serviceName=my-service1 rewrite=/"
. . .
      - backend:
         serviceName: my-service1
         servicePort: 8080
        path: /test/
```

You can also take a look at the Ingress Controller  [logs](https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/logging/) and see whether the backend responded with `404` or NGINX.

> ubuntu@ip-172-31-7-200:~/kubernetes-ingress/deployments$ kubectl -n nginx-ingress exec -it nginx-ingress-8wkfp -- bash
nginx@nginx-ingress-8wkfp:/$ ./nginx-ingress -version
Version= GitCommit=

This looks like a bug in our build system -- those values were supposed to be populated. We will fix that. Thanks for reporting!

**Comment by saivikas408** [comment]
Thanks @pleshakov 

its working now !! 

 i have added  this to ingress resource
 
```
annotations:
  nginx.org/rewrites: "serviceName=my-service1 rewrite=/"
. . .
      - backend:
         serviceName: my-service1
         servicePort: 8080
        path: /test/
```
