### ISSUE TITLE
rewrite-target does not seem to rewrite anymore on GKE

### ISSUE THREAD

**Issue by romainr** [nginxinc/kubernetes-ingress#962]
**Describe the bug**
The [rewrite-target](https://kubernetes.github.io/ingress-nginx/examples/rewrite/) used to work but now we are always getting a 404.

**To Reproduce**
1. On GKE cluster
2. Install latest stable nginx ingress with Helm 3 `helm upgrade nginx-ingress nginx-stable/nginx-ingress --install`
3. Install a dummy service and use below ingress. Note: same with this [GKE Tutorial](https://cloud.google.com/community/tutorials/nginx-ingress-gke).

This returns a 404:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: aa.com
    http:
      paths:
      - backend:
          serviceName: service-ui
          servicePort: 9000
        path: /(.*)
```

`x.x.x.x - - [21/May/2020:14:42:42 +0000] "GET / HTTP/1.1" 404 556 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
`

Commenting `rewrite-target:` and having just `path: /` works with a 200:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
   # nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: aa.com
    http:
      paths:
      - backend:
          serviceName: service-ui
          servicePort: 9000
     #   path: /(.*)
        path: /
```

`x.x.x.x - - [21/May/2020:15:08:29 +0000] "GET / HTTP/1.1" 200 823 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
`

**Expected behavior**
Expecting a proper redirect to the / URL service.

Note: there are more routes to redirect, e.g. /api(.*), but omitting them in the example yaml to keep it short.

**Your environment**
* Version of the Ingress Controller

```
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
nginx-ingress	default  	4       	2020-05-21 07:41:43.297364515 -0700 PDT	deployed	nginx-ingress-0.5.0	1.7.0 
```

Version that used to work:
`nginx-ingress	1       	Wed Nov 20 12:32:47 2019	DEPLOYED	nginx-ingress-1.24.3	0.26.1     	default`

* Kubernetes platform
GCP GKE, tried from 1.14 to 1.16.8-gke.15

**Additional context**
Initial setup was done roughly one year ago, a brand new setup with latest version seems to not work today. 
Not directly related but seems like ingress hostnames are also now required in order to avoid a [`Ingress rule contains empty host`](https://github.com/GoogleCloudPlatform/community/issues/1274)

Thank you and feel free to ask for any more clarifying questions.
