### ISSUE TITLE
Location Snippets Templates

### ISSUE THREAD

**Issue by edahlseng** [nginxinc/kubernetes-ingress#984]
**Is your feature request related to a problem? Please describe.**
I'm looking to add OAuth support (à la the [Kubernetes community's NGINX ingress-controller](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/)), and from my question in #482 it looks like a combination of custom annotations and custom templates could do just that. Nevertheless, using a custom template is a scary option to consider, as then I'm on the hook for keeping the template up to date with upstream changes as this project evolves.

**Describe the solution you'd like**
If I could have the power of custom templates in snippets, then I could easily add the authentication features I'm looking for without needing to maintain a full-blown template. As far as I can tell, this isn't currently possible. Given that, I'm proposing adding a `location-snippet-templates` ConfigMap key, which inserts right after `location-snippets`, but has access to the full templating features available in the `ingress-template` key. Example:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  location-snippet-templates: |
    {{if index $.Ingress.Annotations "custom.nginx.org/feature-a"}}
    # Insert config for feature A if the annotation is set
    {{end}}
```

**Describe alternatives you've considered**
One alternative is to treat the current `location-snippets` key as a template (just changing how it's interpreted during template rendering), but that could have unintended consequences since it changes how an existing key is used.

**Additional context**
N/A
