### ISSUE TITLE
Enable CORS when using VirtualServer

### ISSUE THREAD

**Issue by JoseFMP** [nginxinc/kubernetes-ingress#990]
When using Ingress it is possible to configure with annotation the ingress to allow CORS. However, there is no possibility to enable CORS when using VirtualServer. It would be great to have.

**Comment by pleshakov** [comment]
Hi @JoseFMP 

Thanks for the feature request!

Right now it should be possible to add CORS by using `location-snippets` [ConfigMap key](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#snippets-and-custom-templates). For example:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  location-snippets: |
    if ($request_method = 'OPTIONS') {
       add_header 'Access-Control-Allow-Origin' '*';
   . . .
```
That snippet will insert the CORS NGINX config into the generated config for all VirtualServers in the location blocks.

In the next release 1.8, which we target for the mid July, we will include more extensibility options for VirtualServers, including snippets, so that a snippet can be applied per VirtualServer, not globally like in the ConfigMap.

At the same time, the CORS feature should be implemented in a way that don't require using snippets, like the annotation you mentioned. However, note that we don't have a CORS annotation in our Ingress Controller. Perhaps you meant [a different NGINX Ingress Controller](https://github.com/kubernetes/ingress-nginx).

I suggest leaving this issue open. We'll use it to track this feature.

**Comment by JoseFMP** [comment]
@pleshakov Thank you so much for this workaround. I am gonna try it.
Yes in general I was a bit disappointed using `VirtualServers`. Not really disappointed... but it is really inconvenient to use since all the documentation out there, including annotations for ingress, etc... works only for ingress. I feel like right now using VirtualServer is not a good way to go... but let me see how it goes.

**Comment by JoseFMP** [comment]
@pleshakov With ingress it works, but with `VirtualServer` unfortunately that snippet does not work. NGINX keeps saying 
```
stderr: "nginx: [emerg] \"proxy_connect_timeout\" directive is not allowed here in
```

However I only added `Access-Control-Allow-Origin`

**Comment by JoseFMP** [comment]
I can confirm, if I remove `location-snippets` from the config, NGINX starts fine again. If I add it, it won't even starts (shuts down the whole cluster as no incoming traffic any more).

I think this is a huge limitation, not being able of using CORS with VirtualServers is a pain...

**Comment by JoseFMP** [comment]
@pleshakov What would be the way, if I am using `VirtualServer` to use annotations to enable CORS? According to NGINX controller documentation (I mean, the documentation on NGINX site and I am talking about the controller from NGINX, not that one from Kubernetes) the annotations apply to Ingress. I do not see annotations for `VirtualServer`.

**Comment by JoseFMP** [comment]
@pleshakov Sorry, in your original post there was a missing curly brace ;) I added it and now the NGINX error is gone and the header appears correctly. I can't wait to get version 1.8

**Comment by pleshakov** [comment]
@JoseFMP glad you made it work 🎉 !

btw, if you're changing the config map, it is possible to see if the change resulted in a successful NGINX reload by looking at the events for that configmap -- https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-events-of-the-configmap-resource

> What would be the way, if I am using VirtualServer to use annotations to enable CORS?

Here is an example of using snippets. This is currently being implemented:
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
  namespace: cafe
spec:
  http-snippets: |
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=1r/s;
    proxy_cache_path /tmp keys_zone=one:10m;
  host: cafe.example.com
  tls:
    secret: cafe-secret
  server-snippets: |
    limit_req zone=mylimit burst=20;
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    location-snippets: |
      proxy_cache one;
      proxy_cache_valid 200 10m;
    action:
      pass: tea
  - path: /coffee
    action:
      pass: coffee
```
