### ISSUE TITLE
Can't redirect to other Ingress

### ISSUE THREAD

**Issue by riupie** [nginxinc/kubernetes-ingress#992]
By default, if I want to expose my dashboard I will expose it via Ingress controller like below where I can access it via port 80:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.org/ssl-services: kubernetes-dashboard
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /
```

Then, if I want to use oauth2 so it will authenticate to my oauth2-proxy(integrated with Dex), with flow:
Access dashboard-->redirect to Dex login form--> authenticated-->back to dashboard.
I will add this config to my dashboard ingress:

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.org/ssl-services: kubernetes-dashboard
    nginx.ingress.kubernetes.io/auth-url: "https://dashboard.example.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://dashboard.example.com/oauth2/start?rd=https://$host$request_uri$is_args$args"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /
```
And add 1 ingress for my oauth2-proxy:

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "tls-ca-issuer"
    ingress.kubernetes.io/force-ssl-redirect: "true"
  name: oauth-proxy
  namespace: auth-system
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 8080
        path: /oauth2
  tls:
  - hosts:
    - dashboard.example.com
    secretName: kubernetes-dashboard-external-tls
```
But, when I access dashboard.example.com, it will show 404 not found. Even, it never hit oauth2-proxy pods. My ingress pod logs:

```
2020/06/12 16:04:39 [notice] 11#11: signal 17 (SIGCHLD) received from 1125
2020/06/12 16:07:46 [error] 1130#1130: *1988 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 10.244.2.1, server: dashboard.example.com, request: "GET / HTTP/1.1", host: "dashboard.example.com"
10.244.2.1 - - [12/Jun/2020:16:07:46 +0000] "GET / HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "-"
```
Is there something wrong on my config so it wont redirected?

## My Environment

All inside VMs, each TLS certificate for website is self signed.
