### ISSUE TITLE
default backend for mergeable Ingress resources 

### ISSUE THREAD

**Issue by lotsoftick** [nginxinc/kubernetes-ingress#993]
**Describe the bug**
i'm using mergeable Ingress resources and have problem with default backend (/)
i have 3 services , all use the same host

**Expected behavior**
service1: `/` (react app, all locations except below 2, should render this app)
service2: `/api/service1` 
service3: `/api/service2`

but result is not what i expected
`/` works 
`/djsaj`  instead of service 1 it shows 404 (standard error)
`/api/service2`   works, shows service2
`/api/service2aaa`  instead of service1  it shows service2 again, the same for service 3

here is the generated master.conf
```
upstream service1-mydomain.com-80 {
	zone service1-80 256k;
	random two least_conn;
	server 10.244.0.97:80 max_fails=1 fail_timeout=10s max_conns=0;
}
upstream service2-mydomain.com-80 {
	zone service2-80 256k;
	random two least_conn;
	server 10.244.0.122:80 max_fails=1 fail_timeout=10s max_conns=0;
}
upstream service3-mydomain.com-80 {
	zone service3-80 256k;
	random two least_conn;
	server 10.244.0.60:80 max_fails=1 fail_timeout=10s max_conns=0;
}
server {
	listen 80;
	server_tokens on;
	server_name mydomain.com;

	location / {
		...
		proxy_pass http://service1-mydomain.com-80;
	}
	location /api/service2 {
		...
		proxy_pass http://service2-mydomain.com-80;	
	}
	location /api/service3 {
		...
		proxy_pass http://service3-mydomain.com-80;	
	}
}
```
master ingress

```
kind: Ingress
metadata:
  name: ingress-master
  annotations:
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
    - host: mydomain.com
```

```
kind: Ingress
metadata:
  name: service1-ingress
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: service1
              servicePort: 80
```

```
kind: Ingress
metadata:
  name: service2-ingress
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /api/service2
            backend:
              serviceName: service2
              servicePort: 80
```

**Your environment**
* Version of the Ingress Controller - the last one 
* Version of 1.17.5
* Kubernetes on digitalocean 
* Using NGINX
