### ISSUE TITLE
Prefix match not working with VirtualServer

### ISSUE THREAD

**Issue by JoseFMP** [nginxinc/kubernetes-ingress#999]
I am using this configuration file:
```
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  routes:
  - path: /tea
    action:
      pass: tea
```
I am using 1.7.0. I do not have any other ingress controller.

### Problem
All the requests I make to `/tea` arrive correctly to the pod. So I assume NGINX ingress controller is working fine. However, if I make a request to `/tea/cool` NGINX won't forward anything to the upstream. I only have one upstream "tea"

### Expected behavior
Requests to `/tea/cool/` are forwarded to the upstream the exact same way the requests to `/tea` are being forwarded.
